Beispielkomponente zu tutorials hinzugefügt
public-ui/kolibri pull request #2780
Opened 2023-03-24 06:39 UTC by Wolfram-Zell

2023-03-24 12:05 UTC, deleonio requested changes

2023-03-24 12:05 UTC, deleonio commented on packages/components/src/components/accordion/component.tsx
> +		setTimeout(() => {
Warum hast du den clean Timeout entfernt?

2023-03-24 12:07 UTC, Wolfram-Zell commented on packages/components/src/components/accordion/component.tsx
> +		setTimeout(() => {
timeout wird nur einmal aufgerufen, den in sich selbst zu löschen hat keine Auswirkung.

2023-03-27 08:45 UTC, deleonio commented on packages/components/src/components/accordion/component.tsx
> +		setTimeout(() => {
Hast Du dazu eine spezifikation?

ich lösche die immer stumpf

2023-03-27 08:46 UTC, merged