3029 anomalie bei den radio beispiel im designer untersuchen
public-ui/kolibri pull request #3030
Opened 2023-04-26 07:59 UTC by Wolfram-Zell

2023-04-26 08:16 UTC, deleonio requested changes

2023-04-26 08:16 UTC, deleonio commented on packages/components/src/components/input-radio/component.tsx
> -						/**
Warum wird der Kommentar gelöscht?

Kannst Du kurz erklären, was warum geändert wurde.

2023-04-26 08:17 UTC, Wolfram-Zell commented on packages/components/src/components/input-radio/component.tsx
> -						/**
Der Kommentar erschien mir nicht zum aktuellen Code zu gehören.

2023-04-26 08:23 UTC, deleonio commented on packages/components/src/components/input-radio/component.tsx
> -										ref={this.state._value === option.value ? this.catchRef : undefined}
@laske185 hast du das eingebaut?

2023-04-26 11:30 UTC, laske185 commented on packages/components/src/components/input-radio/component.tsx
> -										ref={this.state._value === option.value ? this.catchRef : undefined}
Nein

2023-04-26 11:43 UTC, laske185 approved these changes

2023-04-26 11:43 UTC, laske185 commented on packages/components/src/components/input-radio/component.tsx
> -										ref={this.state._value === option.value ? this.catchRef : undefined}
Ich verstehe diese Stelle auch nicht. Insofern denke ich auch, dass sie weg kann und auch für den Bug verantwortlich sein könnte.

2023-04-26 11:46 UTC, laske185 commented on packages/components/src/components/input-radio/component.tsx
> -						/**
Das scheint mir auch so. Hier wird nichts gemappt. Nur die Inputs für alle Optionen erzeugt.

2023-04-26 12:44 UTC, deleonio commented on packages/components/src/components/input-radio/component.tsx
> -										ref={this.state._value === option.value ? this.catchRef : undefined}
Das sollte drin bleiben. Weil es den Fokus von außen ermöglich.

2023-04-26 12:44 UTC, deleonio commented on packages/components/src/components/input-radio/component.tsx
> -	private ref?: HTMLInputElement;
Das sollte drin bleiben. Weil es den Fokus von außen ermöglich.

2023-04-27 05:16 UTC, deleonio commented
Das Fokus-Propergation ist wichtig und kann nicht entfernt werden.

Das Entfernen des onClick Handlings hat gereicht, um das Problem zu lösen.

2023-04-27 05:16 UTC, closed without merging