fix #3151 - story generation for windows
public-ui/kolibri pull request #3152
Opened 2023-05-24 13:39 UTC by marienfeldtom

Behebt Syntax Fehler bei Erzeugung von StoryBook Stories unter Windows.

2023-05-24 15:18 UTC, marienfeldtom commented
I have read the CLA Document and I hereby sign the CLA

2023-05-24 15:19 UTC, marienfeldtom commented
recheck

2023-05-25 04:51 UTC, deleonio requested changes

2023-05-25 04:51 UTC, deleonio commented on packages/storybook/scripts/autogen.stories.js
> +		const tag = camel2KebabCase(line.replace(new RegExp(`^(${prefix})([a-z]+)`), '$2'));
`new RegExp` ist sehr imperformant und könnte außerhalb der Loop instanziiert werden.

2023-05-25 06:14 UTC, marienfeldtom commented on packages/storybook/scripts/autogen.stories.js
> +		const tag = camel2KebabCase(line.replace(new RegExp(`^(${prefix})([a-z]+)`), '$2'));
@deleonio Done.

2023-05-25 11:13 UTC, deleonio approved these changes

2023-05-25 13:21 UTC, merged