3500 refact  icononly als  hidelabel umsetzen
public-ui/kolibri pull request #3513
Opened 2023-06-12 06:53 UTC by Wolfram-Zell

2023-06-12 12:51 UTC, laske185 requested changes

2023-06-12 12:51 UTC, laske185 commented on packages/components/src/components/badge/component.tsx
> +	@Prop({ reflect: true }) public _hideLabel?: boolean = false;
Hier beim Badge vergessen _iconOnly auf deprecated zu stellen.

2023-06-12 12:51 UTC, laske185 commented on packages/components/src/components/link-button/component.tsx
> +	@Prop({ reflect: true }) public _hideLabel?: boolean = false;
Hier beim LinkButton vergessen _iconOnly auf deprecated zu stellen.

2023-06-12 13:11 UTC, deleonio requested changes

2023-06-12 13:11 UTC, deleonio commented on packages/components/src/components/breadcrumb/component.tsx
> +	private readonly renderLink = (link: LinkProps, index: number): JSX.Element => {
Warum das Refactoring?

2023-06-12 13:11 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +
Deprecation an `_iconOnly` noch setzen.

2023-06-12 13:11 UTC, deleonio commented on packages/components/src/components/button/component.tsx
>  		this.validateIconOnly(this._iconOnly);
- [x] `this.validateHideLabel(this._hideLabel | this._iconOnly);`
- [x] `this.validateIconOnly(this._iconOnly);` entfernen

2023-06-12 13:11 UTC, deleonio commented on packages/components/src/components/split-button/component.tsx
> +		if (!this._hideLabel) {
Warum wird das hier vorvalidiert? Das sollte doch der Validator machen.
Bzw. die `validateHideLabel` aufrufen.

2023-06-13 04:59 UTC, Wolfram-Zell commented on packages/components/src/components/breadcrumb/component.tsx
> +	private readonly renderLink = (link: LinkProps, index: number): JSX.Element => {
Für verbesserte Lesbarkeit.

2023-06-13 12:41 UTC, deleonio requested changes

2023-06-13 12:41 UTC, deleonio commented on packages/components/src/components/span/component.tsx
> +		if (!this._hideLabel) {
Achtung auch hier wie oben beschrieben korrigieren.

2023-06-13 12:41 UTC, deleonio commented on packages/components/src/components/span/component.tsx
>  		this.validateIconOnly(this._iconOnly);
auch hier aufpassen

2023-06-13 12:41 UTC, deleonio commented on packages/components/src/components/link/component.tsx
> +		this.validateHideLabel(this._hideLabel);
```tsx
public componentWillLoad(): void {
		this.validateAriaControls(this._ariaControls);
		this.validateAriaCurrent(this._ariaCurrent);
		this.validateAriaExpanded(this._ariaExpanded);
		this.validateAriaLabel(this._ariaLabel);
		this.validateAriaSelected(this._ariaSelected);
		this.validateDisabled(this._disabled);
		this.validateDownload(this._download);
		this.validateHideLabel(this._hideLabel | this._iconOnly);
		this.validateHref(this._href);
		this.validateIcon(this._icon);
		this.validateIconAlign(this._iconAlign);
		// this.validateIconOnly(this._iconOnly); remove
		this.validateLabel(this._label);
		this.validateOn(this._on);
		this.validateRole(this._role);
		this.validateSelector(this._selector);
		this.validateStealth(this._stealth);
		this.validateTabIndex(this._tabIndex);
		this.validateTarget(this._target);
		this.validateTargetDescription(this._targetDescription);
		this.validateTooltipAlign(this._tooltipAlign);
		this.validateUseCase(this._useCase);
	}
```

2023-06-13 12:41 UTC, deleonio commented on packages/components/src/components/button/component.tsx
> +		return;
```tsx
public validateIconOnly(value?: boolean): void {
  this.validateHideLabel(value)
```

2023-06-13 12:41 UTC, deleonio commented on packages/components/src/components/span/component.tsx
> +		return;
Hier auf hideLabel weiterleiten.

2023-06-14 09:41 UTC, deleonio approved these changes

2023-06-14 09:42 UTC, merged