improve radio selection via mouse click
public-ui/kolibri pull request #3525
Opened 2023-06-13 08:29 UTC by laske185

Clicking the kol-input into a kol-imput-radio element selects the radio button.

2023-06-13 12:20 UTC, deleonio requested changes

2023-06-13 12:20 UTC, deleonio commented on packages/components/src/components/input-radio/component.tsx
> +			input.checked = true;
Mal on Change bedenken?

2023-06-14 06:55 UTC, Wolfram-Zell requested changes
Das kol-input in das label zu setzen ist keine Lösung weil?
<label><kol-input ...><input slot="input" ...></kol-input></label>

2023-06-14 06:55 UTC, Wolfram-Zell commented on packages/components/src/components/input-radio/component.tsx
> +			this.state._value == value;
Einmal "=" zu viel?

2023-06-14 08:20 UTC, laske185 commented
Es muss erst mal geklärt werden, wie das Verhalten sein soll. Grundproblematik war, dass der Radio-Button an sich 44px breit und hoch sein muss. Optisch wird er dies jedoch nie sein, daher wollte ich mehr Fläche zum Klicken erzeugen. Das ganze Element klickbar zu machen ist aber zu viel und bringt nur ein Event-Chaos.

2023-06-14 08:20 UTC, closed without merging