remove redundant documentation
public-ui/kolibri pull request #3526
Opened 2023-06-13 10:37 UTC by Wolfram-Zell

!! Do not merge before docu branch is merged !!

2023-06-13 12:23 UTC, deleonio requested changes

2023-06-13 12:23 UTC, deleonio commented on docs/ARCHITECTURE.md
Die Dateien bleiben vorerst erhalten.

2023-06-13 12:23 UTC, deleonio commented on docs/GET_STARTED.md
Die Dateien bleiben vorerst erhalten.

2023-06-14 13:14 UTC, Wolfram-Zell commented
docu ist hinzugefügt

2023-06-19 07:17 UTC, deleonio requested changes
@Wolfram-Zell bitte mal den Konflikt eliminieren.

Danke

2023-06-19 07:28 UTC, Wolfram-Zell commented
> @Wolfram-Zell bitte mal den Konflikt eliminieren.
> 
> Danke

@deleonio bitte mergen

2023-06-19 07:40 UTC, merged