Feature/skip nav without shadow
public-ui/kolibri pull request #3540
Opened 2023-06-15 08:53 UTC by laske185

2023-06-16 04:22 UTC, deleonio requested changes

2023-06-16 04:22 UTC, deleonio commented on packages/components/src/components/skip-nav/component.tsx
> +								<kol-link-wc {...link}></kol-link-wc>
Lass mal stealth drin?!

2023-06-16 05:51 UTC, laske185 commented on packages/components/src/components/skip-nav/component.tsx
> +								<kol-link-wc {...link}></kol-link-wc>
die Logik ist im Skip-Nav jetzt drin. Stealth kann entfernt werden.

2023-06-19 07:20 UTC, Wolfram-Zell requested changes

2023-06-19 07:20 UTC, Wolfram-Zell commented on packages/components/src/components/skip-nav/style.css
> +	position: unset;
Der Layout-shift hier ist gewünscht?

2023-06-19 07:20 UTC, Wolfram-Zell commented on packages/themes/bmf/src/index.ts
> +	'KOL-SKIP-NAV': `kol-link-wc > a > kol-span-wc {
Bitte Klassen verwenden. (auch bei den folgenden)

2023-06-19 07:20 UTC, Wolfram-Zell commented on packages/themes/bmf/src/index.ts
> +		cursor: pointer;
Bitte sortieren. (auch bei den folgenden)

2023-06-19 07:25 UTC, merged