button: _value is now string
public-ui/kolibri pull request #3549
Opened 2023-06-16 11:00 UTC by Wolfram-Zell

2023-06-19 07:07 UTC, deleonio requested changes

2023-06-19 07:07 UTC, deleonio commented on packages/components/src/types/button-link.ts
>  		on: KoliBriButtonCallbacks<unknown>;
Bitte hier auch auf String wechseln.

2023-06-19 07:32 UTC, Wolfram-Zell commented on packages/components/src/types/button-link.ts
>  		on: KoliBriButtonCallbacks<unknown>;
Falls du Zeile 110 meinst, da steht bei mir folgendes:
![image](https://github.com/public-ui/kolibri/assets/117265922/8000b135-7776-4fe1-a457-fab98f50c795)

2023-06-20 13:45 UTC, deleonio approved these changes

2023-06-20 13:45 UTC, deleonio commented on packages/components/src/types/button-link.ts
>  		on: KoliBriButtonCallbacks<unknown>;
Nein ich meine Zeile 69, 91 und 109 `KoliBriButtonCallbacks<unknown>`sollte `KoliBriButtonCallbacks`sein und der Typ `string` für dem Value im Typ gesetzt werden.

2023-06-20 13:45 UTC, deleonio commented on packages/components/src/components/tabs/component.tsx
> +						_value={index.toString()}
Das sieht komisch aus. Das haben wir noch nie hier verwendet.

`${index}` // "" + index

2023-06-21 06:52 UTC, deleonio approved these changes
Passt.

2023-07-25 13:50 UTC, closed without merging