Feature/refactor aria label
public-ui/kolibri pull request #3620
Opened 2023-06-21 07:34 UTC by Wolfram-Zell

2023-06-21 08:37 UTC, deleonio commented on packages/components/src/components/button/test/html.mock.ts
> +	}${ariaLabel} class="${variant}" type="${type}">
Kommentar für mich: später noch einmal prüfen

2023-06-22 07:37 UTC, deleonio requested changes

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
> +	@Prop() public _label?: string;
required

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
> +		if (!this._label) {
kein if

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
>  		this.validateAriaLabel(this._ariaLabel);
`||` notation

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/icon/test/html.mock.ts
> +    <i ${props._label ? `aria-label="${props._label}"` : 'aria-hidden="true"'} class="${props._icon}" part="icon" role="img"></i>
Das ist für mich nicht das Gleiche.

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/icon/types.ts
> +	label: string;
required

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> -							_ariaLabel={this.state._smartButton._ariaLabel}
Drin lassen.

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/breadcrumb/component.tsx
> +		if (!this._label) {
if weg

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/breadcrumb/component.tsx
>  		this.validateAriaLabel(this._ariaLabel);
- `this.validateAriaLabel(this._ariaLabel);` weg
- `this.validateLabel(this._label || this._ariaLabel);` verwenden

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/breadcrumb/readme.md
> -Achten Sie im Sinne der optimalen Barrierefreiheit darauf, das Attribut `_aria-label` korrekt auszuzeichnen. Beachten Sie diesen Hinweis insbesondere dann, wenn Sie die Option `_icon-only` verwenden
`_icon-only` gleich zu `_hide-label` ändern

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/breadcrumb/test/html.mock.ts
> +		<nav aria-label="${props._label || ''}">
Warum wurde die Notation geändert?

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/breadcrumb/types.ts
> +	label: string;
Label muss required sein.

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/breadcrumb/types.ts
> -	ariaLabel: string;
Intern muss `label` regired sein.

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/button/component.tsx
> +					aria-label={this.state._hideLabel ? undefined : this.state._label}
JavaScript ist eine nicht typisierte Sprache:

=== false ist was anders als einfach nur den Wahrheitswert abfragen.

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/button/component.tsx
> +		if (!this._label) {
if weg!

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/input/component.tsx
> +							_ariaLabel={this._smartButton._label || this._smartButton._ariaLabel}
sollte nur Label reichen. Das ist eine Interne Komponente, die kann vollständig refactoriert werden

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +	@Prop() public _label?: string;
pflicht

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +		if (!this._label) {
if weg

2023-06-22 07:37 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
>  		this.validateAriaLabel(this._ariaLabel);
falsche notation

2023-06-22 07:41 UTC, Wolfram-Zell commented on packages/components/src/components/icon/component.tsx
> +	@Prop() public _label?: string;
Würde das nicht alle aktuellen Anwendungen kaputtmachen, die das noch nicht verwenden, sondern nur aria-label?

2023-06-22 07:44 UTC, Wolfram-Zell commented on packages/components/src/components/icon/component.tsx
> +		if (!this._label) {
Die Ansage war: wenn _label, dann wird _aria-label ignoriert, ohne if überschreibt _aria-label _label. 
Der Code ist so strukturiert, dass durch Löschen aller _aria-label relevanten Codestellen es sauber entfernt werden kann, ohne anderen Code anfassen zu müssen.

2023-06-22 07:44 UTC, Wolfram-Zell commented on packages/components/src/components/icon/component.tsx
>  		this.validateAriaLabel(this._ariaLabel);
siehe oben

2023-06-22 07:47 UTC, Wolfram-Zell commented on packages/components/src/components/icon/test/html.mock.ts
> +    <i ${props._label ? `aria-label="${props._label}"` : 'aria-hidden="true"'} class="${props._icon}" part="icon" role="img"></i>
Isses auch nicht: wenn _aria-label undefined ist wäre es mit der alten Variante ausgegeben werden, so nicht mehr. Eine Überprüfung, ob es ein string ist wäre eine Alternative.

2023-06-22 07:47 UTC, Wolfram-Zell commented on packages/components/src/components/icon/types.ts
> +	label: string;
siehe oben

2023-06-22 07:48 UTC, Wolfram-Zell commented on packages/components/src/components/badge/component.tsx
> -							_ariaLabel={this.state._smartButton._ariaLabel}
Der button ignoriert _ariaLabel, da er _label gesetzt bekommt.

2023-06-22 07:50 UTC, Wolfram-Zell commented on packages/components/src/components/breadcrumb/readme.md
> -Achten Sie im Sinne der optimalen Barrierefreiheit darauf, das Attribut `_aria-label` korrekt auszuzeichnen. Beachten Sie diesen Hinweis insbesondere dann, wenn Sie die Option `_icon-only` verwenden
-> #3661

2023-06-22 07:51 UTC, Wolfram-Zell commented on packages/components/src/components/breadcrumb/test/html.mock.ts
> +		<nav aria-label="${props._label || ''}">
Da _label aktuell noch nicht Pflicht ist und kein undefined in einem Templatestring stehen darf.

2023-06-22 07:53 UTC, Wolfram-Zell commented on packages/components/src/components/button/component.tsx
> +					aria-label={this.state._hideLabel ? undefined : this.state._label}
Wenn _hideLabel nicht gesetzt (also undefined) ist soll das ariaLabel angezeigt werden?

2023-06-23 17:06 UTC, deleonio requested changes
Ich habe noch nicht alles gereviewed. Aber erstmal wieder ein bisschen.

Danke

2023-06-23 17:06 UTC, deleonio commented on packages/components/src/components/link-group/types.ts
> +	ariaLabel: string;
Im State sollte ariaLabel nicht mehr gebracuht werden.

2023-06-23 17:06 UTC, deleonio commented on packages/components/src/components/modal/types.ts
> +} & AriaLabel;
Im State sollte es raus können.

2023-06-23 17:06 UTC, deleonio commented on packages/components/src/types/button-link.ts
>  	ariaLabel: string;
im state sollte raus können

2023-06-28 11:33 UTC, laske185 commented on packages/components/src/components/breadcrumb/component.tsx
> +		if (!this._label) {
Das verstehe ich nicht. Die Prüfung ist legitim, da das aria-label bei nachträglichen Änderungen das label sonst überschreiben würde.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/breadcrumb/test/html.mock.ts
> +		<nav aria-label="${props._label || ''}">
Kann ich nachvollziehen. Wenn label Pflicht wird, ist es ein breaking change. Wenn es Pflicht sein muss, würde zur Folge haben, dass die Änderung erst zur V2 rein darf.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/breadcrumb/types.ts
> +	label: string;
Siehe vorheriges Statement: Kann ich nachvollziehen. Wenn label Pflicht wird, ist es ein breaking change. Wenn es Pflicht sein muss, würde zur Folge haben, dass die Änderung erst zur V2 rein darf.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/button/component.tsx
> +		if (!this._label) {
Siehe vorherige Stelle:
Die Prüfung ist legitim, da das aria-label bei nachträglichen Änderungen das label sonst überschreiben würde.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/icon/component.tsx
> +	@Prop() public _label?: string;
Siehe vorherige Aussage: würde ein breaking change provozieren.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/icon/component.tsx
> +		if (!this._label) {
Finde ich legitim. Siehe andere stellen,

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/icon/test/html.mock.ts
> +    <i ${props._label ? `aria-label="${props._label}"` : 'aria-hidden="true"'} class="${props._icon}" part="icon" role="img"></i>
Hier sollte zusammen drauf geschaut werden.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/icon/types.ts
> +	label: string;
Siehe vorherige. Breaking change.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/link-group/component.tsx
> +	@Prop() public _label?: string;
Breaking change

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/link-group/component.tsx
> +		if (!this._label) {
überschreiben des label sonst möglich

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/link-group/component.tsx
>  		this.validateAriaLabel(this._ariaLabel);
Ist an sich komplett egal, da die Funktion prüft, ob label gesetzt ist.

2023-06-28 11:44 UTC, laske185 commented on packages/components/src/components/link-group/types.ts
> +	ariaLabel: string;
Sollte beim validieren bereits auf label switchen.

2023-06-28 12:53 UTC, deleonio requested changes

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/button/component.tsx
> +					aria-label={this.state._hideLabel ? undefined : this.state._label}
Muss Aria-Label nicht eher raus, weil es ja mittels Aria-Labelledby gesetzt wird? Oder umgekehrt?

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/button/test/html.mock.ts
> +	}${ariaLabel} class="${variant}" type="${type}">
Das `aria-label` wurde anscheinden noch nie gesetzt. Spricht für `aria-label` raus?

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/button/test/html.mock.ts
> +	}${ariaLabel} class="${variant}" type="${type}">
Fehlt da nicht auch noch aria-labelledby, wenn aria-label gesetzt ist?

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
> +	@Prop() public _label?: string;
`!` muss required werden.

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/nav/types.ts
> +	ariaLabel: string;
kann hier raus

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/types/button-link.ts
>  	ariaLabel: string;
kann weg

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
> +	@Prop() public _label?: string;
Bitte TODO für v2 einbauen, das Label required sein muss.

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
> +		const ariaShow = typeof this.state._label === 'string' && this.state._label.length > 0;
a11yHint(`_label und _aria-label nicht leer ...`)

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
> -		_ariaLabel: '…', // ⚠ required
`_label: '…', // ⚠ required`

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +	@Prop() public _label!: string;
muss bis  v2 optional

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/link-group/types.ts
> +	label: string;
bis v2 optional

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/modal/types.ts
> +	label: string;
muss optional

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/nav/component.tsx
> +	@Prop() public _label!: string;
optional

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/nav/component.tsx
> +		removeAriaLabel(this.state._label);
Bitte Kommentar einfügen, dass Navs nicht doppelt bezeichnet werden.

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/components/nav/types.ts
> +	label: string;
optional

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/types/button-link.ts
> +	PropLabel;
Optional Label wieder entfernen.

2023-06-28 12:53 UTC, deleonio commented on packages/components/src/types/button-link.ts
> +	PropLabel;
Optional Label wieder entfernen.

2023-06-29 11:04 UTC, Wolfram-Zell commented on packages/components/src/components/nav/component.tsx
> +		removeAriaLabel(this.state._label);
siehe: https://github.com/orgs/public-ui/projects/2/views/25?pane=issue&itemId=32055697

2023-06-29 11:20 UTC, Wolfram-Zell commented on packages/components/src/components/icon/component.tsx
> +		const ariaShow = typeof this.state._label === 'string' && this.state._label.length > 0;
Die Komponente ist schon so gebaut, dass sie ohne ariaLabel auskommt und dann aria-hidden setzt. Ich denke das ist so gewünschtes Verhalten?

2023-06-29 11:21 UTC, Wolfram-Zell commented on packages/components/src/components/icon/component.tsx
> -		_ariaLabel: '…', // ⚠ required
siehe oben

2023-06-30 11:31 UTC, Wolfram-Zell commented on packages/components/src/components/button/test/html.mock.ts
> +	}${ariaLabel} class="${variant}" type="${type}">
Braucht der Button ein aria-label? Falls ja, sollte der Test das auch überprüfen, fall nein, muss das auch beim kol-button selber entfernt werden.

2023-06-30 12:19 UTC, Wolfram-Zell commented on packages/components/src/components/button/test/html.mock.ts
> +	}${ariaLabel} class="${variant}" type="${type}">
`aria-label` und `aria-hidden` werden nur gesetzt, wenn `_hide-label=true` ist, was aktuell im Test nicht überprüft wird. Dafür lege ich mal neues Ticket an.

2023-07-03 05:50 UTC, Wolfram-Zell commented on packages/components/src/components/button/component.tsx
> +					aria-label={this.state._hideLabel ? undefined : this.state._label}
Nach meinen Recherchen ist aria-labelledby zu bevorzugen und nur wenn es kein sichtbares Element gibt, sollte aria-label verwendet werden. -> Das aria-label kann hier also raus

2023-07-03 06:55 UTC, deleonio requested changes

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/breadcrumb/types.ts
> +	label: string;
wie besprochen, müsste das auch erstmal optional sein

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/@else/all/component.tsx
> +				<kol-link-group _ariaLabel="" _label="" _links={[]}></kol-link-group>
Hier kann _ariaLabel schon raus.

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/button-link/component.tsx
> +	@Prop({ mutable: true, reflect: false }) public _label?: string;
`{ mutable: true, reflect: false }` das kann raus, weil es den Sycn von AriaLabel und Label nicht mehr gibt

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/button/component.tsx
> +	@Prop({ mutable: true, reflect: false }) public _label?: string;
{ mutable: true, reflect: false } das kann raus, weil es den Sycn von AriaLabel und Label nicht mehr gibt

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/icon/component.tsx
> +		watchString(this, '_label', value, { required: true });
Bitte `validateLabel` verwenden.

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +	@Prop() public _label!: string;
Achtung: muss glaube optional sein

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/nav/component.tsx
> +		removeAriaLabel(this.state._label);
Trotzdem, bitte den Kommentar einfügen.

2023-07-03 06:55 UTC, deleonio commented on packages/components/src/components/button/test/html.mock.ts
> +	}${ariaLabel} class="${variant}" type="${type}">
Ja, ich Frage mich nur, wieso der Testfall vorher noch nicht auftrat.

2023-07-05 06:05 UTC, merged