3556 inputs select textarea css klassen ergänzen
public-ui/kolibri pull request #3727
Opened 2023-06-26 08:09 UTC by Wolfram-Zell

2023-06-26 15:54 UTC, deleonio requested changes

2023-06-26 15:54 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +			<Host class={{ 'hide-label': this.state._hideLabel }}>
Nicht am Host, weil sonst das Styling außerhalb des Shadow root ist.

2023-06-27 07:09 UTC, deleonio requested changes
Hallo Wolfram,

mir ist eben beim Reviewen aufgefallen, dass wir die Klasse nur an den Komponenten einführen sollten, wo sie auch als State geführt werden.

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +						'hide-label': !!this.state._hideLabel,
`hideLabel` - ist kein Property des State

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +		_hideLabel: false,
muss raus

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/badge/test/html.mock.ts
> +			_hideLabel: false,
muss raus

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/badge/types.ts
> +	hideLabel: boolean;
muss raus

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/button-link-text-switch/component.tsx
> +			class={{ 'hide-label': !!this._hideLabel }}
ist kein property vom state

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/button-link-text-switch/component.tsx
> +			class={{ 'hide-label': !!this._hideLabel }}
ist kein property vom state

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/button-link-text-switch/component.tsx
> +		<kol-span-wc class={{ 'hide-label': !!this._hideLabel }} _hideLabel={this._hideLabel === true} _icon={text._icon} _label={text._label}></kol-span-wc>
ist kein property vom state

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/button-link/component.tsx
> +					class={{ 'hide-label': !!this._hideLabel }}
nicht an den wc komponenten, das muss die button componente machen

ist kein property vom state

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/button/shadow.tsx
> +						'hide-label': !!this._hideLabel,
ist kein property vom state

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/input/component.tsx
> +						'hide-label': !!this._hideLabel,
nicht teil des states

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/link-button/component.tsx
> +			<Host class={{ 'hide-label': !!this._hideLabel }}>
ist kein property vom state

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/link-button/component.tsx
> +			<Host class={{ 'hide-label': !!this._hideLabel }}>
muss in die link component

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/link/shadow.tsx
> +					class={{ 'hide-label': !!this._hideLabel }}
ist kein property vom state

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/link/test/html.mock.ts
>      <a${typeof props._ariaExpanded === 'boolean' ? ` aria-expanded="${props._ariaExpanded ? 'true' : 'false'}"` : ''}${
muss dann eher an den `a`

2023-06-27 07:09 UTC, deleonio commented on packages/components/src/components/split-button/component.tsx
> +						'hide-label': !!this._hideLabel,
hier nicht dran machen. 

componente wird nicht umschlossen

2023-06-27 09:44 UTC, Wolfram-Zell commented on packages/components/src/components/badge/component.tsx
> +						'hide-label': !!this.state._hideLabel,
hideLabel/iconOnly von kol-badge zu entfernen ist nicht Teil dieses Tickets -> bitte extra Ticket erstellen

2023-06-29 03:45 UTC, deleonio approved these changes

2023-06-29 03:45 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +						'hide-label': !!this.state._hideLabel,
Ich habe geschrieben, dass das Property `hideLabel` kein State-Property ist und somit die Klassen in dieser Komponente nicht gesetzt werden muss.

2023-06-29 03:45 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +		_hideLabel: false,
Bitte die Review-Hinweise beachten und in Zweifel Kontakt aufnehmen.

2023-06-29 03:45 UTC, merged