4084 redo readmemd with kol components
public-ui/kolibri pull request #4086
Opened 2023-07-13 09:04 UTC by Wolfram-Zell

2023-07-14 04:26 UTC, deleonio requested changes

2023-07-14 04:26 UTC, deleonio commented on packages/components/src/components/abbr/readme.md
> +- <kol-link _href="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr" _label="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr"><kol-link>
Hi @Wolfram-Zell,

wir können das noch etwas optimieren, wenn `_href` und `_label` gleich sind:

```html
<kol-link _href="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr"><kol-link>
```

2023-07-14 05:02 UTC, Wolfram-Zell commented on packages/components/src/components/abbr/readme.md
> +- <kol-link _href="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr" _label="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr"><kol-link>
Hatte ich getestet, war noch nicht live.

2023-07-18 05:22 UTC, deleonio requested changes

2023-07-18 05:22 UTC, deleonio commented on packages/components/src/components/abbr/readme.md
> +- <kol-link _href="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr" _label="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr"><kol-link>
Du kannst das gerne so umsetzen, wie ich geschrieben habe. Wenn das nicht funktioniert, dann haben wir gleich ein Repo-Beispiel, um das Problem zu suchen.

2023-07-18 05:22 UTC, deleonio commented on packages/components/src/components/abbr/readme.md
> +- <kol-link _href="https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr"><kol-link>
Hier fehlt überall `_target="_blank"`

2023-07-20 04:29 UTC, merged