Add avatar component (WIP)
public-ui/kolibri pull request #4178
Opened 2023-07-20 13:57 UTC by sdvg

2023-07-20 14:01 UTC, sdvg commented
I have read the CLA Document and I hereby sign the CLA

2023-07-20 17:18 UTC, deleonio commented
@sdvg bitte einmal pullen, ich musste Konflikte im `main` lösen. Danke

2023-07-20 17:50 UTC, deleonio requested changes
Fix format: `npm run format -- -w`

2023-07-21 09:55 UTC, deleonio approved these changes

2023-07-21 09:56 UTC, merged