Add basic workspace setup
public-ui/kolibri pull request #4533
Opened 2023-08-04 11:59 UTC by sdvg

2023-08-04 12:24 UTC, sdvg commented on package.json
> +		"postinstall": "#lerna exec --stream -- pnpm i --no-frozen-lockfile",
Deaktiviert, da es Probleme gemacht hat. Ich konnte auch nicht nachvollziehen, warum es notwendig ist. Kann vielleicht entfernt werden?

2023-08-04 13:41 UTC, sdvg commented
Die CI-Pipeline hat gerade noch ein Problem, das ich lokal nicht vollziehen kann. 🧐
Davon abgesehen ist der PR bereit für ein erstes Review.

2023-08-09 05:57 UTC, laske185 submitted a review, later dismissed

2023-08-14 12:47 UTC, laske185 commented
Es werden verschiedene Prettier-Versionen verwendet. Vielleicht hilft ein downgrade auf Version 2 mit anschließendem Re-Formatieren.

2023-08-16 05:49 UTC, deleonio commented
@sdvg  - Achtung, ich muss noch einmal den Konflikt lösen. Bitte warten.

2023-08-23 12:01 UTC, laske185 commented on package.json
> +		"postinstall": "#lerna exec --stream -- pnpm i --no-frozen-lockfile",
Die Zeile habe ich nun entfernt, da pnpm automatisch alle Projekte installiert. Ein install auf ein einzelnes Projekt ist nicht mehr möglich.

2023-08-23 12:02 UTC, laske185 commented
Das `lint` aus dem designer entfernt, da es hier zu Problemen kommt. Dies wird im Ticket https://github.com/public-ui/kolibri/issues/4830 wieder eingeführt gemacht.

2023-08-23 12:39 UTC, deleonio requested changes

2023-08-23 12:39 UTC, deleonio commented on packages/samples/react/tsconfig.json
> +		"types": ["mocha", "node", "react", "react-dom"],
Warum?

2023-08-23 12:41 UTC, laske185 commented on packages/samples/react/tsconfig.json
> +		"types": ["mocha", "node", "react", "react-dom"],
Weils sonst nicht baut

2023-08-23 12:42 UTC, deleonio commented on packages/samples/react/tsconfig.json
> +		"types": ["mocha", "node", "react", "react-dom"],
Warum?

2023-08-23 13:02 UTC, laske185 commented on packages/samples/react/tsconfig.json
> +		"types": ["mocha", "node", "react", "react-dom"],
Geht doch wieder...

2023-08-24 04:12 UTC, deleonio approved these changes

2023-08-24 04:13 UTC, deleonio requested changes
@laske185 - Da sind jetzt noch Konflikte.

2023-08-28 13:24 UTC, deleonio commented
@Chrisdo82 😯

2023-08-28 13:43 UTC, merged