Fix import paths for react-vite-app
public-ui/kolibri pull request #4703
Opened 2023-08-17 12:00 UTC by sdvg

2023-08-17 13:17 UTC, deleonio requested changes

2023-08-17 13:17 UTC, deleonio commented on packages/create-kolibri/templates/react-vite-app/index.html
> +		<link rel="stylesheet" href="/node_modules/@public-ui/themes/assets/bundes/style.css" />
Hi @sdvg,

das muss über die `assets` laufen, dass sonst `npm run build` mit Vite nicht geht. Danke für die Erinnerung - daran.

Am besten doch statt `npm start` auch `npm run build` antesten.

2023-08-18 10:02 UTC, sdvg commented on packages/create-kolibri/templates/react-vite-app/tsconfig.json
> +		"skipLibCheck": true,
`tsc` hat einige Fehler in Jest/Mocha gemeldet. libCheck ausschalten schien mir die praktischstes Lösung für diesen Anwendungsfall, ich kann dem Problem aber auch auf den Grund gehen.

2023-08-18 11:48 UTC, deleonio requested changes

2023-08-18 11:48 UTC, deleonio commented on packages/create-kolibri/pnpm-lock.yaml
package lock bite nicht commiten

2023-08-18 11:59 UTC, deleonio approved these changes

2023-08-18 11:59 UTC, merged