Tree component
public-ui/kolibri pull request #4706
Opened 2023-08-17 14:48 UTC by sdvg

2024-01-30 15:48 UTC, sdvg reviewed
- [x] "Draft" Markierung in Sample und Readme hinzufügen
- [ ] Der Collapse/Expand Button sollte bei Klick nicht den darunter liegenden Link aktivieren

2024-02-02 09:00 UTC, laske185 requested changes

2024-02-02 09:00 UTC, laske185 commented on packages/components/src/components/tree-item/component.tsx
> +		this.linkElement.focus();
Anstatt die Warnung zu ignorieren, wäre es besser, sie zu beheben:
```ts
@Method() async focusLink() {
	this.linkElement.focus();
	await Promise.resolve();
}
```
oder
````ts
@Method() async focusLink() {
	return new Promise<void>((resolve) => {
		this.linkElement.focus();
		resolve();
	});
}
``

Gleiches bei allen folgenden Methoden, die kein `await` haben.

2024-02-02 09:00 UTC, laske185 commented on packages/components/src/components/tree-item/style.css
Können wir die Datei weglassen, wenn die Komponente keine Basis-Styles hat oder lieber einen leeren Layer definieren, damit es konsistent ist?

2024-02-02 09:00 UTC, laske185 commented on packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tree-basic-firefox-linux.png
Die Snapshots haben jetzt nicht so richtig funktioniert.

Liegt das am FF?

2024-02-05 13:09 UTC, sdvg commented on packages/components/src/components/tree-item/style.css
Wenn ich den Style ganz entferne, werden auch die Theme-Styles nicht mehr geladen. Ich habe mich daher für den "leeren Layer" entschieden.

2024-02-05 16:50 UTC, sdvg commented on packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tree-basic-firefox-linux.png
Was ein Fehler in der Konfiguration, ist korrigiert.

2024-02-05 16:58 UTC, sdvg commented on packages/components/src/components/tree-item/component.tsx
> +		this.linkElement.focus();
Ich würde hier etwas anders argumentieren:

Die ESLint-Regel ergibt normalerweise Sinn, weil das Async-Keyword an Funktionen unnötig ist, die keine `await`-Aufrufe enthalten. In unserem Fall ist die Funktion aber nur `async`, weil Stencil es so validiert. Normalerweise würden wir das Keyword weglassen. Der Inhalt der Methode ist vollständig synchron und erfordert kein async/await.

Nun könnten wir das Linting-Problem, wie du beschreibst, umgeben, indem wir auf irgendeine Art noch ein Promise erstellen und zurückgeben. Notwendig ist das Promise für die Funktionalität aber eigentlich nicht.

Ich bin daher der Meinung, dass es sinnvoller wäre, die - hier überflüssige - Regel mit einem Kommentar zu deaktivieren, als eigentlich unnötigen (und schlimmstenfalls irritierenden) Code zu schreiben.

2024-02-08 07:54 UTC, laske185 approved these changes

2024-02-08 07:54 UTC, merged