Add aria-labels to pagination
public-ui/kolibri pull request #4726
Opened 2023-08-18 13:14 UTC by sdvg

2023-08-18 13:16 UTC, sdvg commented on packages/components/src/components/pagination/component.tsx
> +				aria-label={translate('kol-page-current', { placeholders: { page: String(page) } })}
Passt das wohl so, oder müsste das aria-label eigentlich auf dem `<button>` direkt platziert sein? Dafür haben wir, soweit ich sehe, keine Option mehr bzw. sie wurde deprecated.

2023-08-18 13:17 UTC, sdvg commented on packages/components/src/components/pagination/component.tsx
> +				aria-label={translate('kol-page-current', { placeholders: { page: String(page) } })}
Laut originaler Ticket-Beschreibung ist das Attribut aber wohlmöglich gar nicht notwendig, nachdem ich auch das aria-label in L68 umgesetzt habe:

> In diesem Fall ist der Zusatz "Seite 1" nicht notwendig und die Ausgabe der Buttons kann bleiben wie sie gerade ist.

Hier bräuchte ich noch mal Feedback, bitte.

2023-08-18 14:04 UTC, deleonio requested changes

2023-08-18 14:04 UTC, deleonio commented on packages/components/src/components/pagination/component.tsx
> +				aria-label={translate('kol-page-current', { placeholders: { page: String(page) } })}
Es muss auf den Button. Was wir aber so nicht mehr unterstützen, da das sichtbare Label dem nicht sichtbaren entsprechen muss. Ich schaue mir das noch mal genau an, was wir machen können.

2023-08-18 14:04 UTC, deleonio commented on packages/components/src/components/pagination/component.tsx
> +				<div aria-label={translate('kol-pagination')}>
Ein `aria-*` erfordert m.W.n immer auch eine `role`, wenn es kein HTML-Tag ala `form` ist. Hier sollte es eher weg. Ich glaube die Aufgabe ist tricky, da wir am Schalter kein aria-label mehr unterstützen.

2023-08-21 14:28 UTC, deleonio submitted a review, later dismissed

2023-08-22 05:45 UTC, deleonio approved these changes

2023-08-22 05:45 UTC, merged