feat: markdown support for badgets
public-ui/kolibri pull request #5099
Opened 2023-09-05 13:50 UTC by laske185

Badge's label supports the markdown notation.

Closes: #5025

2023-09-05 14:55 UTC, deleonio requested changes

2023-09-05 14:55 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +						_allowMarkdown
@laske185: Brauchen wir das Property überhaupt? Wenn _label bisher reiner Text war, dann kann das doch immer durch den Parser und es kommt wieder nur reiner Text raus?!

2023-09-06 05:55 UTC, laske185 commented on packages/components/src/components/badge/component.tsx
> +						_allowMarkdown
Wir wollen es explizit nur für das Badge zulassen, daher dieses Flag.

2023-09-06 06:32 UTC, deleonio requested changes

2023-09-06 06:32 UTC, deleonio commented on packages/components/src/components/badge/component.tsx
> +						_allowMarkdown
Okay können wir später weiter entwickeln.

2023-09-06 06:32 UTC, deleonio commented on packages/components/src/components/component-list.ts
> +	KolMarkdownRendererWc,
Bitte die Komponente bitte als Funktion umsetzen.

2023-09-06 07:15 UTC, laske185 commented on packages/components/src/components/component-list.ts
> +	KolMarkdownRendererWc,
Done.

2023-09-06 07:18 UTC, deleonio approved these changes

2023-09-06 07:45 UTC, merged