style(KolButton, KolLinkButton): increase font-size
public-ui/kolibri pull request #5510
Opened 2023-11-01 08:17 UTC by Chrisdo82

2023-11-01 14:01 UTC, deleonio requested changes
Hi Christian,

kannst Du bitte die Snapshots aktualisieren.

- https://github.com/public-ui/kolibri/actions/runs/6717334391

Dort kannst Du ganz unten die Abweichungen herunterladen "Artefakt".

Um die Snapshots zu aktualisieren.

gehe einfach ins Submodul: `packages/themes/bmf` - `pnpm test-update`

2023-11-01 17:38 UTC, Chrisdo82 commented
@deleonio  Habe ich soeben versucht, bekomme da aber wieder mal einen Fehler `Error: Command failed: npm run build -- --output-path=/var/folders/xy/_psf9hsj4nzd_rpcwgsqyt5m0000gn/T/kolibri-visual-testing-build-b2e462f6-3a7e-4bb2-a78e-f292626b276c`

2023-11-06 06:22 UTC, deleonio commented
Hi @Chrisdo82, der aktuelle PR geht in den `develop` als in die v2. Ist das korrekt?

Ansonsten muss der PR auf `release/1.7` geändert werden.

2023-11-06 08:20 UTC, Chrisdo82 commented
Ich wusste nicht dass der develop die v2 ist. Ändern geht aber nicht, sonst habt ihr alle Changes von v2 auch in der 1.7

2023-11-06 08:37 UTC, deleonio commented
Hi @Chrisdo82,

die Änderungen sollen ja eh in v1 und in v2 gehen. Dann moven wir die Änderungen noch einmal separat in v1.

Wenn Du zukünftig in v1 und v2 was bringen möchtest, dann kannst Du genau diese Abzweigung nutzen, wo v1 und v2 noch identisch waren: `release/v1to2-branch`

Solange dabei keine Konflikte auftreten, kannst du eine Änderungen problemlos in beide Releases mergen.

2023-11-06 09:16 UTC, Chrisdo82 commented
macht ihr das oder soll ich nochmal einen PR mit den Änderungen erstellen?

2023-11-09 10:02 UTC, deleonio requested changes
Bitte nicht die locks einchecken.

2023-11-09 12:04 UTC, Chrisdo82 commented
Eine Contribution Guideline in der sowas drin steht, wäre für die Zukunft echt hilfreich. 

Ich möchte doch einfach nur die Styles updaten

2023-11-09 12:10 UTC, merged

2023-11-09 12:12 UTC, deleonio commented
Hi Christian,

da ich an Deinen Fork nicht herankomme, konnte ich die Änderung nicht reinholen. Leider musste ich diesmal, alles an Dich zurückschieben.

Bei Aspekte sind gut für die Contributor-Readme:
- nur relevante Änderungen einchecken
- Features für v1 und v2 immer von `release/v1to2-branch` abzweigen