[v2] Allow propagation of keyup events on input elements
public-ui/kolibri pull request #5689
Opened 2023-12-04 11:48 UTC by sdvg

Allow propagation of keyup events on input elements in order not to break listeners higher up in the DOM. E.g. for closing tooltips on keyup escape

2023-12-04 11:48 UTC, sdvg commented on packages/components/src/components/tooltip/component.tsx
> +			getDocument().addEventListener('keyup', this.hideTooltipByEscape, { once: true });
Kleines Refactoring

2023-12-05 08:26 UTC, laske185 requested changes

2023-12-05 08:26 UTC, laske185 commented on packages/components/src/components/tooltip/component.tsx
> +			getDocument().addEventListener('keyup', this.hideTooltipByEscape, { once: true });
Mit jedem Tooltip öffnen wird ein weiterer Listener hinzugefügt, wenn er nicht über ESC geschlossen wird.

2023-12-05 08:33 UTC, sdvg commented on packages/components/src/components/tooltip/component.tsx
> +			getDocument().addEventListener('keyup', this.hideTooltipByEscape, { once: true });
Sehr guter Hinweis, der Tooltip kann natürlich nicht nur mit der Tastatur bedient werden 🙏

2023-12-05 09:37 UTC, deleonio requested changes

2023-12-05 09:37 UTC, deleonio commented on packages/components/src/components/tooltip/component.tsx
> +		getDocument().removeEventListener('keyup', this.hideTooltipByEscape);
Das würde doch dazu führen, dass der Listener immer wieder weggenommen wird. Nicht?

2023-12-05 09:51 UTC, sdvg commented on packages/components/src/components/tooltip/component.tsx
> +		getDocument().removeEventListener('keyup', this.hideTooltipByEscape);
Genau, so lange der Tooltip sichtbar ist, ist der Listener da, damit man ihn mit ESC schließen kann. Wurde er dann geschlossen (auf welche Art auch immer), wird der Listener wieder entfernt.

2023-12-05 10:10 UTC, laske185 commented on packages/components/src/components/tooltip/component.tsx
> +		getDocument().removeEventListener('keyup', this.hideTooltipByEscape);
Genau, bei showTooltip wird der Listener immer hinzugefügt und beim Verstecken wieder entfernt. Passt also.

2023-12-05 10:10 UTC, laske185 approved these changes

2023-12-05 11:17 UTC, deleonio approved these changes

2023-12-05 11:17 UTC, merged