Adjust radio example so all groups can be focused
public-ui/kolibri pull request #5758
Opened 2023-12-12 09:26 UTC by sdvg

2023-12-12 16:37 UTC, deleonio approved these changes

2023-12-12 16:38 UTC, deleonio requested changes

2023-12-12 16:38 UTC, deleonio commented on packages/samples/react/src/components/input-radio/partials/cases.tsx
> +				_options="[{'disabled':true,'label':'Frau','value':'Frau'},{'label':'Herr (disabled)'},{'label':'Firma','value':'Firma'}]"
Der Herr ist ja disabled, wenn dann müssten wir auch das Label ändern?

2023-12-13 07:36 UTC, sdvg commented on packages/samples/react/src/components/input-radio/partials/cases.tsx
> +				_options="[{'disabled':true,'label':'Frau','value':'Frau'},{'label':'Herr (disabled)'},{'label':'Firma','value':'Firma'}]"
Richtig, ist jetzt angepasst.

2023-12-13 21:08 UTC, deleonio approved these changes

2023-12-13 21:08 UTC, merged