5658  input range auf schieber wird ausgegeben
public-ui/kolibri pull request #5765
Opened 2023-12-13 09:31 UTC by cyrinermd

@sdvg

2023-12-13 09:45 UTC, sdvg requested changes

2023-12-13 09:45 UTC, sdvg commented on packages/components/src/components/input-range/component.tsx
>  	private ref?: HTMLInputElement;
Bitte refactoren zu `refInputNumber` damit der Unterschied zwischen den beiden Refs klar wird.

2023-12-13 09:45 UTC, sdvg commented on packages/components/src/components/input-range/component.tsx
> +	private refInputange?: HTMLInputElement;
```suggestion
	private refInputRange?: HTMLInputElement;
```
typo

2023-12-13 09:45 UTC, sdvg commented on packages/components/src/components/input-range/component.tsx
> +			propagateFocus(this.host, element);
@deleonio  Das war nicht spezifiziert, ergibt aber vermutlich Sinn. Siehst du das auch so?

2023-12-13 09:45 UTC, sdvg commented on packages/components/src/components/input-range/component.tsx
> +				this._value = parseFloat(this.refInputange.value);
(Warum) Benötigen wir das zusätzlich zu Zeile 52, in der wir den Wert bereits in den State übernehmen?

2023-12-13 09:46 UTC, sdvg commented
Issue: https://github.com/public-ui/kolibri/issues/5658

2023-12-13 10:54 UTC, sdvg approved these changes, later dismissed

2023-12-14 05:59 UTC, deleonio requested changes

2023-12-14 05:59 UTC, deleonio commented on packages/components/src/components/input-range/component.tsx
> +			propagateFocus(this.host, element);
@cyrinermd Die Code-Zeile `propagateFocus` darf nicht für das RangeInput gesetzt werden. Da nur eine `forwardRef` pro Input gesetzt werden darf. Und hier wollen wir, dass das NumberInput an fokussiert wird.

2023-12-14 11:30 UTC, deleonio approved these changes

2023-12-14 11:31 UTC, merged