Update README and adjust BadgeButton label text
public-ui/kolibri pull request #5772
Opened 2023-12-13 14:25 UTC by cyrinermd

2023-12-13 14:29 UTC, sdvg commented
Issue: https://github.com/public-ui/kolibri/issues/5705

2023-12-13 14:31 UTC, sdvg approved these changes, later dismissed

2023-12-13 14:31 UTC, sdvg commented on packages/samples/react/src/components/badge/button.tsx
> +const createBadgePROPS = (label: String) => ({
```suggestion
const createBadgeProps = (label: String) => ({
```

2023-12-13 14:31 UTC, sdvg commented on packages/samples/react/src/components/badge/button.tsx
> +	<div>
```suggestion
	<>
	//...
	</>
```

Hier wäre ein Fragment ausreichend.

2023-12-13 14:43 UTC, sdvg approved these changes, later dismissed

2023-12-13 21:15 UTC, deleonio approved these changes
👍 thanks

Please fix the CI

2023-12-14 06:06 UTC, deleonio requested changes

2023-12-14 06:06 UTC, deleonio commented on packages/samples/react/src/components/badge/button.tsx
> +const createBadgeProps = (label: String) => ({
Bitte `string` kleinschreiben ;-)

2023-12-14 11:35 UTC, deleonio approved these changes

2023-12-14 11:35 UTC, merged