5675 table headings
public-ui/kolibri pull request #5780
Opened 2023-12-15 13:13 UTC by sdvg

2023-12-19 05:04 UTC, deleonio commented
Hier ein aktuelles Test-Deployment zum Nachtesten: https://65804134a6dfa73ecab101e8--magenta-gingersnap-274e19.netlify.app/

2023-12-19 14:01 UTC, deleonio commented
@sdvg kannst du bitte die snapshots noch fixen. Danke
den Test habe ich schon beauftragt

2023-12-19 15:10 UTC, fohi17 commented
Nachtest: 
Mega cool, die Spaltensortierung wird jetzt auf dem Tabellenkopf ausgegeben und nicht beim Wechsel zwischen den Zellen. Ich habe noch Kleinere Problemchen/Hinweise:

- Im Hinweistext beim sortieren scheint es noch ein Problemchen zu geben, da steht "Die Spalte X ist aufsteigen{{multi}} sortiert. Das "multi" sollte da sicher nicht sein. 
- Durch die Verwendung von aria-live="assertive" wird jetzt direkt beim Aufruf der Seite der Sortierhinweis ausgegeben. Das ist bei einer produktiv-Seite sicher verwirrend und nicht gewollt.
-  Eigentlich sollte mit aria-sort auch bei Änderung die Sortierung direkt ausgegeben werden, womit der Live-Text nicht notwendig wäre. Das passiert aber, zumindest mit NVDA, nicht zuverlässig (bei JAWS hat es geklappt). Daher finde ich die Lösung mit dem live-text eigentlich ganz schön. Für JAWS-Nutzer kommt die Sortierrichtung dann allerdings immer doppelt.

Ich hab versucht das jetzt zügig zu Recherchieren und wollte das schnell mitteilen. Aber vielleicht habt ihr ja auch einfach fix ne schöne Lösung : ) Ansonsten schau ich mal noch weiter, vielleicht liegt es auch wieder an meinen NVDA-Einstellungen oder der Performance.

2023-12-20 08:55 UTC, deleonio commented
@sdvg siehst Du hier noch Handlungsbedarf? Ggf. das Beispiel optimieren, erster Anstrich?

2023-12-20 09:53 UTC, sdvg commented
@deleonio Ich habe mir die drei Punkte angeschaut, kann sie nachvollziehen und würde sie gerne adressieren.

Bei mir wird auch mit NVDA die Sortierung doppelt ausgegeben (einmal für aria-sort und einmal für aria-live).
Die Lösung für alle drei Probleme scheint mir daher zu sein, die aria-live region ganz zu entfernen. Dazu können wir uns vorab vielleicht kurz besprechen, wenn du Zeit hast.

Etwaiges unzuverlässiges Vorlesen der Sortierung mit NVDA würde ich ggf. separat betrachten und beheben, bzw. an das NVDA-Team melden?

2023-12-20 10:26 UTC, fohi17 commented
@deleonio @sdvg Nachtrag von mir: Das Problem mit aria-sort in Chrome ist bekannt seit 2020 und gemeldet https://github.com/nvaccess/nvda/issues/10890. Traurig, dass es dann immer noch besteht. In Firefox funktioniert es tatsächlich wunderbar : )

2023-12-20 14:28 UTC, deleonio commented
- [ ] Wir setzen Punkt 3 um und erledigen damit auch die Punkte 1 und 2.
- [ ] Wir dokumentieren das Problem mit dem manchmal nicht Vorlesen in den `KNOWN_ISSUES.md` file.

2023-12-21 08:17 UTC, laske185 approved these changes, later dismissed

2023-12-21 09:37 UTC, deleonio approved these changes

2023-12-21 09:37 UTC, deleonio commented
Hallo @fohi17,

bitte retesten, danke.

2023-12-21 14:45 UTC, deleonio requested changes
Ich muss erst die Style-Änderungen in das neue Theme-Repo übernehmen.

2023-12-22 05:35 UTC, deleonio approved these changes

2023-12-22 05:35 UTC, merged