Implement error list in KolForm
public-ui/kolibri pull request #5799
Opened 2023-12-19 14:53 UTC by cyrinermd

2023-12-19 14:57 UTC, cyrinermd commented
Issue: https://github.com/public-ui/kolibri/issues/5571

2023-12-19 15:31 UTC, sdvg requested changes

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/types/props/error-list.ts
Bitte analog zu den anderen prop types anlegen. `access-key.ts` ist ein gutes Beispiel.

- Der Type, den du schon definiert hast, sollte `ErrorListPropType` heißen.
- Zusätzlich sollte es einen type `PropErrorList` geben, der auch den Prop-Namen (über den Key) definiert.
- Eine `validateErrorList`-Funktion wäre auch gut hier zu haben.

2023-12-19 15:31 UTC, sdvg commented on packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
> +type ErrorListPropType = {
type bitte aus `@public-ui/components` importieren

2023-12-19 15:31 UTC, sdvg commented on packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
> +	function createErrorList(formikErros: Record<string, string>): ErrorListPropType[] {
```suggestion
	function createErrorList(formikErrors: Record<string, string>): ErrorListPropType[] {
```
Kleiner typo, bitte einmal überall suchen & ersetzen :)

2023-12-19 15:31 UTC, sdvg commented on packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
> -					<ErrorList errors={form.errors} />
Kann die Komponente `ErrorList` dann gelöscht werden oder wird sie an anderer Stelle noch verwendet?

2023-12-19 15:31 UTC, sdvg commented on packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
> -						setSectionSubmitted(true);
Brauchen wir das nicht mehr?

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/types.ts
> +	errors: ErrorListProps[];
Bitte auch zu den `OptionalStates` hinzufügen

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/component.tsx
> +	@Prop() public _errors?: ErrorListProps[];
@deleonio Wäre hier ein `Stringified<>` notwendig bzw. sinnvoll?

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/component.tsx
> +	@Prop() public _errors?: ErrorListProps[];
Bitte noch JSDocs, analog zu den anderen Props, hinzufügen (auf Englisch).

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/component.tsx
> +				{this._errors && Object.keys(this._errors).length > 0 && (
Ist das hier noch korrekt, sollte `this._errors` jetzt nicht ein Array sein?
Funktionieren tut der Check natürlich auch für ein Array, aber das `Object.keys` ist unnötig, denke ich.

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/component.tsx
> +						Bitte korrigieren Sie folgende Fehler:
Bitte `translate()` verwenden

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/component.tsx
> +						<nav aria-label="Fehlerliste">
Hier ebenfalls `translate()` verwenden, bitte

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/component.tsx
> +								{Object.entries(this._errors).map(([field, error]) => (
`Object.entries` sollte mit der neuen Datenstruktur nicht mehr notwendig sein

2023-12-19 15:31 UTC, sdvg commented on packages/components/src/components/form/component.tsx
> +										{' '}
Wofür brauchen wir dieses Leerzeichen?

2023-12-20 06:58 UTC, cyrinermd commented on packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
> -					<ErrorList errors={form.errors} />
sie ist an andere Stelle verwendet

2023-12-20 06:59 UTC, cyrinermd commented on packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
> -						setSectionSubmitted(true);
ja

2023-12-21 08:15 UTC, sdvg commented on packages/components/src/locales/en.ts
> +	'error-list': 'Error List',
```suggestion
	'error-list': 'Error list',
```

2023-12-21 15:11 UTC, deleonio approved these changes
Sieht gut aus. Ich schau es mir noch mal lokal an.

2023-12-22 05:21 UTC, merged