Resolved inconsistent error handling and message linjing across form inputs and radio button.
public-ui/kolibri pull request #5843
Opened 2024-01-02 10:36 UTC by cyrinermd

2024-01-02 10:37 UTC, cyrinermd commented
@sdvg

2024-01-03 07:50 UTC, sdvg requested changes

2024-01-03 07:50 UTC, sdvg commented on packages/samples/react/src/scenarios/appointment-form/PersonalInformationForm.tsx
> +								if (event.key === 'Tab') void form.setFieldTouched('salutation', true);
Wir sollten hier stattdessen das `blur` event verwenden.

Die aktuelle Lösung wird nur funktionieren, wenn tatsächlich `<tab>` gedrückt wird, aber nicht, wenn der User z.B. in das nächste Feld klickt.

2024-01-22 10:00 UTC, sdvg requested changes
Mir sind beim Testen noch folgende Probleme aufgefallen:

* Die Blur-Validierung für Stadtteil funktioniert nicht
* Wenn man bei "Persönliche Daten" über die Fehler tabbt ohne sie auszufüllen, erscheinen die Fehler für Name und E-Mail-Adresse auf einmal (beim Blur von Name)

2024-02-06 12:58 UTC, sdvg approved these changes

2024-02-06 12:58 UTC, merged