5743 bug/appointment form focus issue
public-ui/kolibri pull request #5908
Opened 2024-01-17 16:06 UTC by deleonio

2024-01-23 07:36 UTC, deleonio commented
## Beschreibung des Fehlers
Fehler im zweiten Tab:

1. Wenn ein nicht verfügbarer Termin ausgewählt wird, kann die Fehlerliste nicht mehr mit "Tab" verlassen werden
2. Durch das neu Rendern der Radiobuttons bei der Erstellung einer Fehlermeldung an den Radiobuttons bzw. das entfernen von diesen, wechselt der Bedienmodus des Screenreaders. Dadurch werden nach dem neu Rendern werden einzelne Buchstaben vorgelesen.
3. Bei der Auswahl der Uhrzeit kann kein Radiobutton nach dem vierten Radiobutton ausgewählt werden

Fehler im dritten Tab:

1. Beim Verlassen des Feldes „Vor und Zuname“ werden die Felder „Vor und Zuname“ und „E-Mail“ validiert.
2. Fehlerliste hat einen nicht sprechenden Link. Links zu Formularfeldern sollten in der Fehlerliste heißen wie die Label vom Betroffenen Feld. Daher den Link „Namen“ in „Vor und Zuname“ ändern. Gleiches gilt für „Email“ und „E-Mail-Adresse“
3. Bestehende Fehlerlisten werden beim Verlassen eines Tabs in einen anderen Tab mit übertragen. Der Link funktioniert in dem neuen/anderen Tab nun nicht mehr
4. Wenn aus der Fehlerliste in „Persönliche Daten“ in das Feld „Vor und Zuname“ gesprungen wird, kann nur ein Buchstabe eingetragen werden. Danach wird der Nächste Link der Fehlerliste Fokussiert. (Gilt auch für Datum im vorherigen Tab)

## Reproduktion
https://65a7fbb1c5ca3b00785e767a--kolibri-public-ui.netlify.app/#/scenarios/appointment-form

Schritte zum Reproduzieren des Verhaltens:
Fehler im zweiten Tab:

1. Datum: 01.01.2024. Zeit 08:00 Uhr (nicht verfügbarer Termin). Weiter mit Enter. Die Fehlerliste wird nun erzeugt und der Fokus springt auf die Fehlerliste. Der Sprung zum nächsten Element via "Tab" ist nun nicht mehr möglich.
2. Mit Tab auf die Radiobutton Liste. Mit Pfeiltasten können andere Termine ausgewählt werden. Wenn ein neu ausgewählter Termin nicht mehr verfügbar ist, rendert KoliBri eine Fehlermeldung dazu. Der Screenreader verlässt dadurch den Formularmodus und liest die einzelnen Buchstaben der Fehlermeldung vor
3. Wenn eine Fehlermeldung wieder entfernt wird (Weil ein verfügbarer Termin ausgewählt wird) wird die Radiobutton group neu gerendert und verliert den Fokus. Beim neu betreten der Radiobutton Group wird wieder das erste Element fokussiert. Dadurch kann keine Radiobutton nach dem vierten ausgewählt werden. 

Fehler im dritten Tab:

1. Formularfeld "Vor und Zuname" mit der Tastatur auswählen. keinen Eintrag vornehmen und weiter Tabben.
2. Fehlerliste erzeugen (ohne Eintrag in den Formularfeldern den "weiter" Schalter betätigen)
3. Fehlerliste erzeugen und dann den vorherigen Tab auswählen.
4.  Fehlerliste erzeugen und über den Link in das Formularfeld „Vor und Zuname“ springen.

## Erwartetes Verhalten
Fehler im zweiten Tab:

1. Fehlerlisten müssen immer auch mit Tab verlassen werden können
2 + 3. Beim neu Rendern der Radiobutton Group muss ich nach dem Rendern wieder an der gleichen stelle stehen wie vorher. Dadurch sollten beide Probleme gelöst sein

Fehler im dritten Tab:

1. Das Feld "E-Mail" darf nicht mit Validiert werden
2. Erwartetes verhalten steht in der Problem Beschreibung
3. Fehlerlisten sollten bei einem Tab Wechsel entweder Gelöscht oder ausgeblendet werden, damit nur Fehler des jeweiligen Tab angezeigt werden
4. Ich darf nicht am eintragen von Inhalten gehindert werden

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows
- Browser: Chrome
- Version 120.0.6099.200 (Offizieller Build) (64-Bit)

2024-01-26 07:14 UTC, laske185 requested changes

2024-01-26 07:14 UTC, laske185 commented on packages/components/src/components/form/component.tsx
> +	errorListElement!: HTMLElement;
Das müsste doch nullable sein, da es `undefined` bleibt, wenn es keine Fehler in der Liste gibt. Also `errorListElement?: HTMLElement;`

Weiter unten in Zeile 134 prüfst du es ja sogar.

2024-01-26 07:14 UTC, laske185 commented on packages/components/src/components/form/component.tsx
> +				this.errorListElement.focus();
Die Funktion könnte auch ein Zweizeiler sein:
```ts
if (this._errorList?.length > 0) {
    this.errorListElement?.focus();
}
``` 

Meiner Meinung nach besser lesbar.

2024-01-26 07:14 UTC, laske185 commented on packages/components/src/components/form/component.tsx
> +	errorListElement!: HTMLElement;
Vom Coding-sytle fände ich es sehr angenehm, wenn fields immer oben in der Klasse definiert werden und danach die Methoden und Funktionen. Und mit accessor wäre noch schön. :)

2024-02-05 06:55 UTC, laske185 approved these changes

2024-02-06 07:07 UTC, deleonio commented
Was genau ist bei diesem PR noch offen?

2024-02-06 07:08 UTC, deleonio reviewed
Was genau ist bei diesem PR noch offen?

2024-02-06 12:19 UTC, merged