Alert html:  Fix heading hierarchy
public-ui/kolibri pull request #5962
Opened 2024-01-26 10:21 UTC by cyrinermd

2024-01-26 10:30 UTC, cyrinermd commented
#5962

2024-01-26 10:31 UTC, cyrinermd commented
#5747

2024-01-26 10:45 UTC, deleonio requested changes
H2
 H3
 H3
 
So ist es gedacht. Überschriften lassen nur H4 auf H3 ändern.

2024-01-29 13:14 UTC, deleonio requested changes

2024-01-29 13:14 UTC, deleonio commented on packages/samples/react/src/components/alert/html.tsx
> +					<h2>Text in einer linken Spalte</h2>
Bitte nur `h4` auf `h3` ändern.

2024-01-29 13:14 UTC, deleonio commented on packages/samples/react/src/components/alert/html.tsx
> +					<h2>Text in einer rechten Spalte</h2>
Bitte nur `h4` auf `h3` ändern.

2024-01-29 13:14 UTC, deleonio commented on packages/samples/react/src/components/alert/html.tsx
> -			<h2 className="mt-2 mb-3">Hier wird eine H2-Überschrift ausgegeben</h2>
`h2` belassen.

2024-01-29 16:17 UTC, deleonio approved these changes

2024-01-29 18:05 UTC, merged