Create breadcrump sample page
public-ui/kolibri pull request #5982
Opened 2024-01-30 14:27 UTC by anicyne

2024-01-30 14:33 UTC, sdvg requested changes

2024-01-30 14:33 UTC, sdvg commented on packages/samples/react/src/App.tsx
> +						<Route path="breadcrumb/sample-page" element={<SamplePage />} />
```suggestion
						<Route path="sample-page" element={<SamplePage />} />
```

2024-01-30 14:33 UTC, sdvg commented on packages/samples/react/src/components/breadcrumb/basic.tsx
Bitte auch andere Beispiel mit Links beachten und "kaputte" Links auf diese Seite abändern. (Bitte alle Beispiele einmal durch gehen)

2024-01-31 05:54 UTC, deleonio commented
Hallo @cyrinermd,

gerne erstmal fertig machen. Wir werden diese Änderungen auch für `v1` benötigen.

2024-02-01 15:25 UTC, sdvg commented
Bis auf den Konflikt passt es von meiner Seite 👍

2024-02-05 09:38 UTC, sdvg approved these changes

2024-02-05 09:39 UTC, merged