Bug/5986 bug input radio akzeptiert keine stringifizierten zahlenwerte
public-ui/kolibri pull request #6013
Opened 2024-02-05 10:36 UTC by KawaiiMochiAhri

2024-02-05 10:43 UTC, sdvg commented
@KawaiiMochiAhri Den Titel des PR bitte einmal so anpassen, dass er später direkt in den Changelog übernommen werden kann (Englisch, ohne Referenz auf die Ticketnummer)

2024-02-06 06:22 UTC, deleonio requested changes

2024-02-06 06:22 UTC, deleonio commented on pnpm-lock.yaml
Bitte keine `pnpm-lock.yaml` mit einchecken.

2024-02-06 06:22 UTC, deleonio commented on packages/components/src/components/input-radio/controller.ts
> +				nextState.set('_value', String(newValue));
Nicht die Werte hier manipulieren.

2024-02-06 06:22 UTC, deleonio commented on packages/components/src/components/input-radio/controller.ts
> +		return options.find((option) => option.value === value as string) !== undefined || options.find((option) => option.value == value) !== undefined;
Die Validierung sollte weiterhin typsicher bleiben. Die für die Ticket-Behebung notwendig Änderung muss an einer anderen Stelle gemacht werden.

Irgendwo auf dem Weg wird der String `'123'` einfach auf eine Zahl `123` geändert. Dort liegt das Problem.

2024-02-06 08:22 UTC, sdvg commented on packages/components/src/components/input-radio/controller.ts
> +		return options.find((option) => option.value === value as string) !== undefined || options.find((option) => option.value == value) !== undefined;
@deleonio Der Cast kommt ziemlich sicher aus `mapString2Unknown`, ist also grundsätzlich gewollt, so wie ich es verstehe.
Ich würde vorschlagen, dass wir hier einmal zu dritt über die nächsten Schritte und die ideale Lösung sprechen.

2024-02-12 07:23 UTC, deleonio commented
Wir schließen den PR

2024-02-12 07:23 UTC, closed without merging