Split themes into scss
public-ui/kolibri pull request #6033
Opened 2024-02-09 10:11 UTC by KawaiiMochiAhri

2024-02-12 15:18 UTC, sdvg requested changes

2024-02-12 15:18 UTC, sdvg commented on packages/components/src/components.d.ts
Ich wundere mich ein bisschen, wo diese Änderungen her kommen. Könntest du bitte noch mal einen Build der Components ausführen und ggf. entstandene Änderungen committen? Dann passt es in jedem Fall.

2024-02-12 15:18 UTC, sdvg commented on packages/themes/tsconfig.json
> -	"include": ["src/**/*.ts", "src/**/*.tsx", "src/globals.d.ts"],
Was hat es mit dieser Änderung auf sich?

2024-02-14 07:42 UTC, KawaiiMochiAhri commented on packages/themes/tsconfig.json
> -	"include": ["src/**/*.ts", "src/**/*.tsx", "src/globals.d.ts"],
Ich hatte mich da an Cyrines Änderungen Orientiert. Sie hatte das include auch nicht. Und dadurch hat der Build der CI-Pipeline keinen Fehler mehr geworfen

2024-02-15 07:58 UTC, sdvg commented on packages/components/src/components.d.ts
@KawaiiMochiAhri Ich bekam hier immer noch Änderungen angezeigt. Habe es jetzt mal selber gepushed, nicht wundern.

2024-02-22 08:25 UTC, deleonio commented
@sdvg oder @laske185 bitte mal reviewn.

2024-02-22 08:34 UTC, sdvg approved these changes

2024-02-23 08:05 UTC, sdvg commented
@laske185 Möchtest du hier auch noch drauf schauen oder können wir mergen?

2024-02-27 06:21 UTC, deleonio commented
Hi @sdvg, Du hast das schon gereviewed. Wenn es weiterhin passt, dann bitte durchmergen. Danke Dir.

2024-02-27 07:34 UTC, merged