Resolved inconsistent error handling and message linking across form inputs and radio button.
public-ui/kolibri pull request #6044
Opened 2024-02-12 08:07 UTC by anicyne

2024-02-12 08:13 UTC, deleonio requested changes

2024-02-12 08:13 UTC, deleonio commented on packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
> +							onBlur={() => {
Das `onBlur` muss in das `_on`-Binding.

2024-02-12 10:37 UTC, deleonio approved these changes, later dismissed
Implementierung passt.

2024-02-20 09:22 UTC, fohi17 commented
------------- **A11y-Test Erfolgreich für v1** -------------

2024-02-20 11:03 UTC, deleonio approved these changes

2024-02-20 11:04 UTC, merged