Improve checkbox visibility with transparent border in forced color mode
public-ui/kolibri pull request #6049
Opened 2024-02-12 11:55 UTC by anicyne

2024-02-12 18:01 UTC, deleonio approved these changes

2024-02-12 18:02 UTC, deleonio requested changes
Hallo @sdvg,

ich glaube so einfach ist das eigentlich nicht, da wir hier den Border noch einmal um 1px nach außen vergrößern. So wird aus einem Element immer seine Größe plus 2px. Gibt es da nicht mit CSS eine Variante, sodass der Border innenliegend ist?

2024-02-14 08:31 UTC, AntnSaj commented
Ursprünglicher Fehler ist behoben. Mit Benutzerdefinierten Einstellungen in Firefox und in der Normalen Ansicht gibt es jedoch keinen Sichtbaren Tastaturfokus auf den Checkboxen.

2024-02-14 10:21 UTC, deleonio commented
@AntnSaj Bitte dazu ein neues Ticket anlegen. Danke

2024-02-14 10:21 UTC, merged