Refactor: Switch tag selectors to classes
public-ui/kolibri pull request #6070
Opened 2024-02-14 10:03 UTC by anicyne

2024-02-14 11:34 UTC, deleonio commented
Bitte den Conflict lösen, Danke Dir.

2024-02-21 07:09 UTC, deleonio requested changes

2024-02-21 07:09 UTC, deleonio commented on packages/components/src/components/@shared/form-field-msg.tsx
> +			'kol-alert': true,
Die Klasse wird von der Komponente selbst ("von innen") gesetzt und muss somit nicht bei der Verwendung gesetzt werden.

2024-02-21 07:09 UTC, deleonio commented on packages/components/src/components/abbr/component.tsx
> +				<abbr aria-labelledby={this.nonce} role="definition" tabindex="0" title={this.state._label} class="kol-abbr">
Die Klassen nur am `Host` setzen.

2024-02-21 07:09 UTC, deleonio commented on packages/components/src/components/button-link-text-switch/component.tsx
> +	private button = (button: ButtonWithChildrenProps): JSX.Element => <kol-button-wc {...button} class="kol-button-wc"></kol-button-wc>;
Kann  weg.

2024-02-21 07:09 UTC, deleonio commented on packages/components/src/components/button-link-text-switch/component.tsx
> +	private link = (link: LinkWithChildrenProps): JSX.Element => <kol-link-wc {...link} class="kol-link-wc"></kol-link-wc>;
Kann weg.

2024-02-21 07:09 UTC, deleonio commented on packages/components/src/components/button-link-text-switch/component.tsx
> +	private text = (text: TextWithChildrenProps): JSX.Element => <kol-span-wc {...text} class="kol-span-wc"></kol-span-wc>;
Kann weg.

2024-02-27 12:14 UTC, sdvg requested changes
Ich finde noch ein paar Stellen, die bisher nicht angepasst sind. Am besten einmal selber durchgehen.

Methode: Ich habe nach dem Regex `[^.]kol-` in den Dateien `*.css,*.scss` gesucht.
Beispiel: `packages/components/src/assets/style.css`

2024-02-28 08:52 UTC, sdvg approved these changes

2024-02-28 12:27 UTC, deleonio approved these changes
👍

2024-02-28 12:27 UTC, merged