fix: condition to register kolibri once
public-ui/kolibri pull request #6087
Opened 2024-02-19 06:25 UTC by deleonio

2024-02-19 10:46 UTC, laske185 requested changes

2024-02-19 10:46 UTC, laske185 commented on packages/components/src/utils/dev.utils.ts
> +	🚹 The accessible HTML-Standard | 👉 https://public-ui.github.io | 2.0.6
Revert please.

2024-02-21 10:09 UTC, sdvg requested changes

2024-02-21 10:09 UTC, sdvg commented on packages/components/src/utils/dev.utils.ts
> +			initMeta();
Wie vorhin gesehen, müsste auch noch aus dem Condition-Block entfernt werden

2024-02-21 14:28 UTC, merged