Set focus to error list on form submission
public-ui/kolibri pull request #6092
Opened 2024-02-19 11:22 UTC by anicyne

2024-02-22 09:12 UTC, deleonio commented
Hi @anicyne,
wir sollten das `KolAlert` außerhalb des `form`s machen, damit das `Return` nicht zum `onSubmit` führt.

2024-03-08 06:40 UTC, deleonio requested changes

2024-03-08 06:40 UTC, deleonio commented on packages/samples/react/src/scenarios/appointment-form/AppointmentForm.tsx
> +		// console.log(_values, formik);
Entfernen, bitte.

2024-03-08 10:23 UTC, AntnSaj commented
Fokus wird auf die Liste gesetzt. Screenreader sagt die Fehlermeldung auch richtig an, jedoch ist die Fehlerliste bei der Terminauswahl als Liste mit einem Eintrag umgesetzt. Listen sollen erst ab zwei Einträgen genutzt werden .Außerdem ist der Submit Button bei der Terminauswahl nicht im vorwärts Tabben fokussierbar, weil dieser nach dem Tabben validiert wird. Man komm also nur im rückwärts Tabben auf den Button.

2024-03-08 11:22 UTC, deleonio commented
@AntnSaj bitte neues Ticket anlegen. Für mich ist das mergebar.

2024-03-08 15:00 UTC, merged