Fix sidebar prev button on first page
public-ui/kolibri pull request #6095
Opened 2024-02-20 12:21 UTC by anicyne

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title for the release notes
- [x] Pull request is linked to an issue
- [x] All changes relate to the issue
- [x] A11y tests performed successfully
- [x] Code review carried out successfully
- [x] Manual test performed successfully

2024-02-22 08:16 UTC, deleonio requested changes

2024-02-22 08:16 UTC, deleonio commented on packages/samples/react/src/components/Sidebar.tsx
> +		const nextIndex = currentIndex === 0 || currentIndex < 0 ? routeList.length - 1 : currentIndex - 1;
Hier schlage ich `<=` vor. Ein weiteres Problem ist jedoch, dass ich immer direkt auf dem Handout landen möchte.

2024-02-22 08:17 UTC, deleonio commented on packages/samples/react/src/components/Sidebar.tsx
> +		const nextIndex = currentIndex === 0 || currentIndex < 0 ? routeList.length - 1 : currentIndex - 1;
Bitte das ausprobieren: https://stackoverflow.com/questions/63690695/react-redirect-is-not-exported-from-react-router-dom

2024-02-27 06:09 UTC, deleonio requested changes

2024-02-27 06:09 UTC, deleonio commented on packages/samples/react/src/App.tsx
> +						<Route path="*" element={<Navigate to={ROUTE_LIST[0]} replace />} />
Das scheint als Fallback zu funktionieren. 👍

2024-02-27 06:09 UTC, deleonio commented on packages/samples/react/src/App.tsx
> +						<Route path="/" element={<KolAlert _type="info">This code example has not been migrated yet - it&#39;s coming soon!</KolAlert>} />
Aber das hier soll ja auch auf Handout - also quasi weg. ℹ️

2024-02-27 07:24 UTC, deleonio approved these changes

2024-02-27 07:25 UTC, merged

2024-02-27 07:28 UTC, anicyne commented on packages/samples/react/src/App.tsx
> +						<Route path="*" element={<Navigate to={ROUTE_LIST[0]} replace />} />
Kannst du mir bitte erklären, was du mit 'als Fallback funktioniert' meinst? Soll ich das so lassen oder brauchen wir eine andere Lösung?