Fix: Replace kol-alert with kol-alert-wc in Input Error Message
public-ui/kolibri pull request #6149
Opened 2024-03-01 10:00 UTC by anicyne

2024-03-04 06:43 UTC, deleonio requested changes

2024-03-04 06:43 UTC, deleonio commented on packages/components/src/components/input/component.tsx
> +	styleUrls: {
Das Styling erfolgt bei KoliBri nur über Shadow-Komponenten (`shadow: true`). Ich vermute, dass wenn diese Zeile weg ist, trotzdem alle Tests grün sind.

2024-03-06 18:50 UTC, deleonio commented
@anicyne dieser PR war abhängig von dem tag classes PR. Bitte noch einmal anpassen.

2024-03-07 15:32 UTC, deleonio requested changes

2024-03-07 15:32 UTC, deleonio commented on packages/themes/bmf/src/index.ts
> +			border-width: 0 !important;
@sdvg Wir wollen ja `!important` vermeiden. Warum ist das notwendig?

2024-03-07 16:13 UTC, sdvg commented on packages/themes/bmf/src/index.ts
> +			border-width: 0 !important;
Die Änderung hat sich wohl ergeben, weil sich die Spezifität des Selektors von TYPE zu CLASS geändert hat.

Ich würde das `!important` auch lieber vermeiden und stattdessen vorschlagen, die `border-width` nur wo sie benötigt wird, also für die `.card` Variante zu definieren.

2024-03-07 16:14 UTC, sdvg commented on packages/themes/bmf/src/index.ts
>  		.msg {
Die doppelten Selektoren sollten auch nicht notwendig sein :)

2024-03-07 16:36 UTC, deleonio commented on packages/themes/bmf/src/index.ts
> +			border-width: 0 !important;
Ich habe dazu jetzt eine dediziertes neues Ticket angelegt. Da ja sonst alles okay ist.

https://github.com/public-ui/kolibri/issues/6169

2024-03-07 16:41 UTC, deleonio approved these changes, later dismissed

2024-03-07 16:45 UTC, merged