Update KolInputRadio value type to unknown and add example with object as value in React sample app
public-ui/kolibri pull request #6199
Opened 2024-03-12 10:04 UTC by anicyne

2024-03-18 15:23 UTC, sdvg requested changes

2024-03-18 15:23 UTC, sdvg commented on packages/samples/react/src/components/input-radio/objectValue.tsx
> +				In Diesem Beispiel für <code>KolInputRadio</code> werden die Werte der Optionen als Objekte definiert.
Sample App Text sollten auf Englisch sein (siehe https://github.com/public-ui/kolibri/issues/5811)

2024-03-18 15:23 UTC, sdvg commented on packages/samples/react/src/components/input-radio/objectValue.tsx
> +			<SampleDescription>
Würde ich als einfaches `<p>`-Tag umsetzen, wir haben normal nur eine SampleDescription pro Seite.

2024-03-18 15:23 UTC, sdvg commented on packages/components/src/components/input-radio/controller.ts
> -			this.setFormAssociatedValue(value as string);
Ich glaube das sollte bleiben. Die `beforePatch` kann raus.

2024-03-18 16:26 UTC, sdvg requested changes

2024-03-18 16:26 UTC, sdvg commented on packages/components/src/components/input-radio/controller.ts
> +		if (typeof onChange === 'function') {
Das sieht für mich nicht richtig aus: Vorher wurde onChange aufgerufen, wenn die Optionen sich geändert haben, jetzt direkt on load?

Ich vermute, wir können dieses Code-Fragment einfach entfernen, weil onChange bereits in der Komponente selbst aufgerufen wird. Das sollte aber (in der Sample App) getestet werden.

2024-03-19 06:03 UTC, deleonio requested changes

2024-03-19 06:03 UTC, deleonio commented on packages/samples/react/src/components/input-radio/routes.ts
> +		object: InputRadioObjectValue,
Bitte noch ein weiteres Beispiel, wo der Value nicht gesetzt wurde und somit kein Radio-Button selected ist.

2024-03-20 16:33 UTC, deleonio approved these changes, later dismissed

2024-03-21 08:51 UTC, sdvg submitted a review, later dismissed

2024-03-22 05:45 UTC, deleonio requested changes

2024-03-22 05:45 UTC, deleonio commented on packages/samples/react/src/components/input-radio/objectValue.tsx
Bitte separiere das Beispiel mit der keine Auswahl in ein eigenes Beispiel, z.B. `no preselection`.

Und füge beide Beispiele in die Testliste hinzu: https://github.com/public-ui/kolibri/blob/3dbb96c4b1abe12d4663592e372ca0f8bd940282/packages/tools/visual-tests/tests/sample-app.routes.js#L183

2024-03-22 16:38 UTC, deleonio approved these changes

2024-03-22 16:39 UTC, merged