Remove `nav` tag and make `_label` optional in KolLinkGroup
public-ui/kolibri pull request #6209
Opened 2024-03-13 10:15 UTC by anicyne

2024-03-14 14:17 UTC, deleonio commented on packages/components/src/components/link-group/style.scss
> +	ol.horizontal,
`:is(ol, ul)` ist auch eine smarte Notation

2024-03-14 14:41 UTC, deleonio approved these changes, later dismissed

2024-03-14 14:41 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +		_label: '',
Bitte `_label` auch aus den RequiredState entfernen. So wäre es `undefined` und würde im Leer nicht gerender als `aria-label=""`

2024-03-15 08:00 UTC, sdvg commented on packages/components/src/components/link-group/style.scss
> +	ul.horizontal {
Martin hatte Recht, wir können hier `:is` verwenden:

`:is(ol, ul).horizontal`

2024-03-18 15:19 UTC, sdvg commented on packages/components/src/components/link-group/component.tsx
@anicyne  @deleonio Hattet ihr hier besprochen, was mit dem Label passieren soll? Ich blicke nicht so ganz durch, gerade scheint es keinerlei Nutzen mehr zu haben?

Das Ticket verstehe ich so, dass es nur nicht mehr required sein soll, die bisherige Funktionalität aber erhalten bleiben soll?

2024-03-19 05:58 UTC, deleonio requested changes

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
Genau.

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +						aria-label=""
Bitte hier: `aria-label={this.state._label}`

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +						aria-label=""
Bitte hier: `aria-label={this.state._label}`

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> -import { addNavLabel, removeNavLabel } from '../../utils/unique-nav-labels';
Das soll bleiben und nicht entfernt werden.

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> -			removeNavLabel(this.state._label); // remove the current
Das soll bleiben und nicht entfernt werden.

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> -		addNavLabel(this.state._label); // add the state instead of prop, because the prop could be invalid and not set as new label
Das soll bleiben und nicht entfernt werden.

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
>  			required: true,
`required` muss weg

2024-03-19 05:58 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> -		removeNavLabel(this.state._label);
Das soll bleiben und nicht entfernt werden.

2024-03-19 09:57 UTC, sdvg commented on packages/components/src/components/link-group/component.tsx
>  			required: true,
@anicyne Kommentar ist noch offen

2024-03-19 10:03 UTC, sdvg commented on packages/components/src/components/link-group/component.tsx
> +					<ol
Optionaler Refactoring Vorschlag:
Statt das komplette Code-Fragment zu wiederholen, können wir auch nur den Tagnamen variabel machen:

```
const ListTag = this.isUl ? 'ul' : 'li';

return  <Host class="kol-link-group">
					<ListTag
[...]
```

2024-03-19 10:03 UTC, sdvg submitted a review, later dismissed

2024-03-20 16:37 UTC, deleonio requested changes
Bitte wie vorgeschlagen anpassen: https://github.com/public-ui/kolibri/pull/6209/files#r1530062937

2024-03-20 16:40 UTC, deleonio requested changes
Bitte noch letzte Hinweise korrigieren.

2024-03-21 08:04 UTC, sdvg submitted a review, later dismissed

2024-03-22 05:46 UTC, deleonio requested changes

2024-03-22 05:46 UTC, deleonio commented on packages/components/src/components/link-group/component.tsx
> +		const ListTag = this.isUl ? 'ul' : 'li';
Achtung: Es wird nur zwischen `ul` (unordered list) und `ol` (ordered list) unterschieden. Nicht `li` (list item).

2024-03-22 16:40 UTC, deleonio approved these changes

2024-03-22 16:40 UTC, merged