Überarbeitete Description für Spin Custom #6059
public-ui/kolibri pull request #6225
Opened 2024-03-15 15:39 UTC by Schollkolade

Sample Description erweitert.

2024-03-19 06:57 UTC, deleonio requested changes

2024-03-19 06:57 UTC, deleonio commented on packages/samples/react/src/components/spin/custom.tsx
> +				Hier ist ein von uns erstelltes Beispiel für eine Custom Animation. Diese kann nach eigenen Vorstellungen angepasst werden und ist nicht zwingend
@Schollkolade Hinweis: Die Animation ist nicht durch uns erstellt. Mittels des Expert-Slots ist es möglich, eigene Animationen einzufügen. Diese sind ...

2024-03-22 16:31 UTC, Schollkolade commented on packages/samples/react/src/components/spin/custom.tsx
> +				Hier ist ein von uns erstelltes Beispiel für eine Custom Animation. Diese kann nach eigenen Vorstellungen angepasst werden und ist nicht zwingend
Beschreibung angepasst

2024-03-22 16:43 UTC, deleonio approved these changes

2024-03-22 16:43 UTC, merged