Refactor: Remove `complex-form` and Resolve Focus Issue in `appointment-form`
public-ui/kolibri pull request #6226
Opened 2024-03-18 10:15 UTC by anicyne

2024-03-19 06:58 UTC, deleonio approved these changes

2024-03-19 07:01 UTC, deleonio requested changes
@anicyne Beim manuellen Test passt was nicht. Wenn ich bei eingeblendeter Fehlerliste durchtabbe komme ich immer wieder auf die Fehlermeldung und nicht auf den Weiter-Schalter.

https://65f814f3d3f04445b9eb9e1e--kolibri-public-ui.netlify.app/#/scenarios/appointment-form

2024-03-19 16:32 UTC, anicyne commented
> @anicyne Beim manuellen Test passt was nicht. Wenn ich bei eingeblendeter Fehlerliste durchtabbe komme ich immer wieder auf die Fehlermeldung und nicht auf den Weiter-Schalter.
> 
> https://65f814f3d3f04445b9eb9e1e--kolibri-public-ui.netlify.app/#/scenarios/appointment-form

@deleonio Das Problem mit dem Fokus, wurde behoben.

2024-03-20 16:53 UTC, deleonio approved these changes

2024-03-20 16:53 UTC, merged