Fix mouse events within tables
public-ui/kolibri pull request #6230
Opened 2024-03-19 09:22 UTC by sdvg

2024-03-19 12:06 UTC, deleonio requested changes

2024-03-19 12:06 UTC, deleonio commented on packages/components/src/components/table/component.tsx
> +				<div ref={(element) => (this.tableDivElement = element)} class="table" tabindex={this.tableDivElementHasScrollbar ? '-1' : undefined}>
Es können doch auch interaktive Elemente in der Tabelle sein, wenn kein Scollbar vorhanden ist?!

2024-03-19 13:08 UTC, sdvg commented on packages/components/src/components/table/component.tsx
> +				<div ref={(element) => (this.tableDivElement = element)} class="table" tabindex={this.tableDivElementHasScrollbar ? '-1' : undefined}>
Ja, richtig. Der Tabindex muss m.E. aber nur gesetzt werden, wenn die Tabelle scrollbar ist, weil man sie nur dann zum scrollen fokussieren muss. Auf die in der Tabelle liegenden Elemente sollte das keinen Einfluss haben.

Beantwortet das die Frage oder habe ich dich falsch verstanden?

2024-03-19 13:43 UTC, deleonio commented on packages/components/src/components/table/component.tsx
> +				<div ref={(element) => (this.tableDivElement = element)} class="table" tabindex={this.tableDivElementHasScrollbar ? '-1' : undefined}>
Ich habe `undefined` übersehen.

2024-03-20 16:55 UTC, deleonio approved these changes

2024-03-20 16:56 UTC, merged

2024-03-27 07:36 UTC, AntnSaj commented
------------- A11y-Test erfolgreich -------------