fixed textarea scrollbar issue
public-ui/kolibri pull request #6306
Opened 2024-04-15 12:18 UTC by Schollkolade

2024-04-16 15:37 UTC, deleonio approved these changes, later dismissed

2024-04-16 15:37 UTC, deleonio commented on packages/components/src/components/textarea/component.tsx
> +			if (this._adjustHeight) {
Ich würde im JS immer auf `true` prüfen.

2024-04-18 06:15 UTC, deleonio requested changes
Die Screenshots für Textarea Rows = 1 müssen genauso hoch bleiben, wie ein TextInput. Dazu müssen wir das Problem der Änderung im CSS analysieren.

2024-04-18 07:42 UTC, sdvg commented
> Die Screenshots für Textarea Rows = 1 müssen genauso hoch bleiben, wie ein TextInput. Dazu müssen wir das Problem der Änderung im CSS analysieren.

Aktuell ist keine Höhe definiert, weder über CSS noch über ein `rows`-Attribut. Daher wird die Höhe gerade standardmäßig auf "zwei Zeilen" gesetzt, was die Änderung zur vorherigen Implementierung zur Folge hat.

Wenn der Standard "eine Zeile" sein soll, könnte die einfachste Lösung sein, die `rows` auf 1 zu setzen, so lange nicht anders definiert ist:

```diff
if (this._adjustHeight === true && this.ref /* SSR instanceof HTMLTextAreaElement */) {
	this._rows = this.state?._rows && this.state._rows > increaseTextareaHeight(this.ref) ? this.state._rows : increaseTextareaHeight(this.ref);
-}
+} else if (!this._rows) {
+	this._rows = 1;
+}```

2024-05-28 08:55 UTC, deleonio approved these changes

2024-05-28 08:57 UTC, merged