Component: Conversion of the ComboBox
public-ui/kolibri pull request #6354
Opened 2024-04-24 14:24 UTC by anicyne

2024-04-25 12:31 UTC, sdvg commented on packages/schema/src/components/combo-box.ts
> +	 * @deprecated Will be removed in v3. Use `msg` instead.
Können wir bei neuen Komponenten direkt weglassen.

2024-04-25 12:31 UTC, sdvg commented on packages/schema/src/components/combo-box.ts
> +	PropOptionsWithOptgroup & // PropOptionsWithOptgroup becomes required with 2.0
Direkt als required umsetzen, da neue Komponente.

2024-04-25 12:31 UTC, sdvg commented on packages/schema/src/components/combo-box.ts
> +export type ComboBoxAPI = Generic.Element.ComponentApi<RequiredProps, OptionalProps, RequiredStates, OptionalStates>;
Wir sollten uns auf eine Schreibweise beschränken. Üblich ist "Combobox" als ein Wort, denke ich.
`ComboBox` und `combo-box` werden also überall zu `combobox`.

2024-04-25 12:31 UTC, sdvg commented on packages/samples/react/src/components/combobox/routes.ts
> +import { ComboboxbBasic } from './basic';
typo
```suggestion
import { ComboboxBasic } from './basic';
```

2024-04-25 12:31 UTC, sdvg commented on packages/samples/react/src/components/combobox/basic.tsx
> +const SALUTATION_OPTIONS: SelectOption<string>[] = [
Hier passt der Select-Type leider doch nicht ganz. Es kann m.E. bei einer Combobox keine deaktivierten Optionen geben.

2024-04-25 12:31 UTC, sdvg commented on packages/samples/react/package.json
Was hat es mit diesem Änderungen auf sich?

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
Hier bitte auf lange Sicht das BEM-Styling nicht vergessen :)

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/readme.md
(Am Ende) bitte noch anpassen

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/controller.ts
> +	public validateMultiple(value?: boolean): void {
`Multiple` gibt es bei einer Combobox nicht, alles was damit zusammenhängt kann entfernt werden.

2024-04-25 12:31 UTC, sdvg commented on packages/samples/react/src/components/combobox/basic.tsx
> +const SALUTATION_OPTIONS: SelectOption<string>[] = [
Außerdem, auch abweichend vom Select, reicht als Option Type bzw. Value ein einfacher `string`. Das Objekt mit label/value ist nicht notwendig bzw. ergibt auch keinen Sinn bei freien Eingaben.

Das führt zu ein paar Änderungen ggü. Select, macht die Komponente aber insgesamt weniger komplex.

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +// const isSelected = (valueList: unknown[] | null, optionValue: unknown): boolean => {
Auskommentierten bzw. nicht benötigten Code, der von Select übernommen wurde, bitte bei Gelegenheit löschen.

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	private OnInput(event: Event) {
```suggestion
	private onInput(event: Event) {
```

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	private filtredOptions(query: string) {
```suggestion
	private setFilteredOptionsByQuery(query: string) {
```
Typo in `filtered`, außerdem bitte klarer benennen (was tut die Methode). Vorschlag siehe oben.

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +								<KolIconTag _icons="codicon codicon-triangle-down" _label={`dropdown`} />
Sinnvolles Label und Lokalisierung bitte nicht vergessen

2024-04-25 12:31 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +						<ul id="listbox" role="listbox" aria-label="" class={{ listbox: true, hidden: !this._isOpen }} tabindex="-1">
Wird die ID benötigt?

2024-04-30 12:13 UTC, sdvg commented
Wenn ich in das Eingabefeld klicke, kann ich die aktuelle Eingabe nicht erweitern. Ich muss erst Zeichen löschen, um frei schreiben zu können.

2024-04-30 12:16 UTC, sdvg commented
Auch wenn ich z.B. in das leere Eingabefeld klicke, würde ich erwarten, Text eingeben zu können. Sattdessen sehe ich nicht, was ich getippt habe und nur die Auswahl in den Vorschlägen ändert sich.

Beispiel:
<img width="438" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/1562ea8d-9dbf-4e96-b5b1-da2c6ed449b3">

Ich habe hier bereits die Buchstaben `Fr` eingegeben. Ich würde erwarten, dass diese im Eingabefeld sichtbar sind, und nur noch der Vorschlag "Frau" erscheint, weil die anderen rausgefiltert wurden.

2024-04-30 12:19 UTC, sdvg commented
Sobald ich eine Eingabe erzeugt habe, die nicht in den Vorschläge vorhanden ist, kann ich die Vorschlagsliste nicht mehr mit Klick öffnen.
<img width="430" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/de5a98c9-3a1f-474d-bc62-2f14d3fac8ac">

(Spec: "Bei Öffnen der Vorschlagsliste (ungeachtet eines eingegebenen Wertes) wird die Liste ungefiltert dargestellt.
")

2024-04-30 12:21 UTC, sdvg commented on packages/components/src/components/combobox/readme.md
Hier bitte noch die API-Änderung bei den Options berücksichtigen

2024-04-30 12:25 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
Das Styling hier geht schon weit über das Basis-Styling hinaus. Bitte auf das Minimum beschränken (Layout und Positionierung; keine festen Größen, Farben, oder ähnliches). Das individuell Styling kann dann gerne in die Themes eingefügt werden :)

Bzgl. Größen bitte einmal diese Seite lesen: https://github.com/public-ui/kolibri/wiki/Code-Style-and-Conventions

Hinweis: Die CSS Custom Properties, wie hier verwendet, sind nicht in allen Themes verfügbar.

2024-04-30 12:25 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +	.combobox__input[type='text'] {
```suggestion
	.combobox__input {
```

2024-04-30 12:26 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +	.combobox {
Bei BEM kann man gut mit Verschachtelung in Scss arbeiten:

```
.combobox {
  &__group {
    &--modifier {
    }
  }
}
```

2024-05-02 07:52 UTC, chrisalat requested changes

2024-05-02 07:52 UTC, chrisalat commented on packages/components/src/components/combobox/component.tsx
> +	}
Tiefe if/else-Verschachtelungen verschlechtern oft die Lesbarkeit von Funktionen. Meistens ist es am besten soweit wie möglich auf else zu verzichten und stattdessen mit return statements zu arbeiten, außer es geht nicht anders.

Als Beispiel: (Hab ich allerdings nicht direkt getest :))
```suggestion
private moveFokus(delta: number) {
	if (!this._filtredOptions) {
		return
	}
	let index = 0
	if (delta < this._filtredOptions.length) {
		const optionLength = this._filtredOptions.length
		index = (this._focusedOptionIndex + delta + optionLength) % optionLength;
		if (index < 0) {
			index = optionLength - 1;
		}
	}
	this._focusedOptionIndex = index
	this.focusOption(this._focusedOptionIndex);
}
```

2024-05-02 07:52 UTC, chrisalat commented on packages/components/src/components/combobox/style.scss
> +		padding: 5px 30px 5px 10px;
Haben wir für solche Werte globale Variablen?

2024-05-02 07:52 UTC, chrisalat commented on packages/components/src/schema/utils/prop.validators.ts
> +		},
Kann man durch eine inline condition etwas verkleinern:
```suggestion
(value): boolean => Array.isArray(value) ? value.every((item) => typeof item === 'string' && (typeof options?.maxLength === 'undefined' || value.length <= options.maxLength)) : false
```

2024-05-02 09:18 UTC, chrisalat requested changes

2024-05-02 09:18 UTC, chrisalat commented on packages/components/src/components/combobox/controller.ts
> +		}
```suggestion
		key === '_value' && this.setFormAssociatedValue(value as string);
```

2024-05-02 09:18 UTC, chrisalat commented on packages/components/src/components/combobox/component.tsx
> +									})}
Variablen bitte nur verwenden, falls der Wert wiederverwendet wird.
```suggestion
{this._filtredOptions && this._filtredOptions.map((option, index) => (
									<li key={`-${index}`} data-index={index} tabIndex={0} onClick={() => this.selectOption(option)} class="combobox__item">
										{option}
									</li>
								))}
```

2024-05-02 09:18 UTC, chrisalat commented on packages/components/src/components/combobox/component.tsx
> +	}
```suggestion
	handleWindowClick(event: MouseEvent) {
		(this.host as HTMLKolComboboxElement) && this.host != undefined && !this.host.contains(event.target as Node) && (this._isOpen = false);
	}
```

2024-05-02 09:18 UTC, chrisalat commented on packages/components/src/components/combobox/component.tsx
> +	}
Was hältst du davon? Da manche handler öfters ausgeführt werden.
```suggestion
	public handleKeyDown(event: KeyboardEvent) {
		const isOpen = this._isOpen;
		const handleEvent = (val?: boolean, callback?: () => void): void => {
			event.preventDefault();
			if (val !== undefined) {
				this._isOpen = val;
			}
			callback?.();
		};
		switch (event.key) {
			case 'Down':
			case 'ArrowDown': {
				handleEvent(true, () => this.moveFokus(1));
				break;
			}
			case 'Up':
			case 'ArrowUp': {
				handleEvent(true, () => this.moveFokus(-1));
				break;
			}
			case 'Esc':
			case 'Escape': {
				handleEvent(false);
				break;
			}
			case ' ':
			case 'Enter': {
				handleEvent(isOpen ? true : undefined, () => (isOpen ? this.selectFocusedOption() : undefined));
				break;
			}
			case 'Home': {
				handleEvent(undefined, () => {
					if (isOpen) {
						this._focusedOptionIndex = 0;
						this.focusOption(this._focusedOptionIndex);
					}
				});
				break;
			}
			case 'End': {
				handleEvent(undefined, () => {
					if (isOpen) {
						this._focusedOptionIndex = this._filtredOptions ? this._filtredOptions.length - 1 : 0;
						this.focusOption(this._focusedOptionIndex);
					}
				});
				break;
			}
			case 'PageUp': {
				handleEvent(undefined, () => isOpen && this.moveFokus(10));
				break;
			}
			case 'PageDown': {
				handleEvent(undefined, () => isOpen && this.moveFokus(-10));
				break;
			}
			default:
				if (event.key.length === 1 && /[a-z0-9]/i.test(event.key)) {
					this._isOpen = true;
					this.focusOptionStartingWith(event.key);
				}
				break;
		}
	}
```

2024-05-06 15:13 UTC, chrisalat reviewed
Insgesamt sieht es jetzt gut aus 👍
Das letzte wäre vielleicht noch die styles entsprechend @sdvg anzupassen und noch das dropdown _label in die Übersetzungen auszulagern.

2024-05-08 05:26 UTC, deleonio requested changes

2024-05-08 05:26 UTC, deleonio commented on packages/components/src/schema/components/combobox.ts
> +type RequiredProps = { options: string[] };
Bitte verwendet statt `options` das Property `suggestions`. Dafür gibt es auch schon ein Type in Schema

2024-05-08 05:26 UTC, deleonio commented on packages/components/src/schema/components/combobox.ts
> +	options: string[];
Bitte verwendet statt `options` das Property `suggestions`. Dafür gibt es auch schon ein Type in Schema

2024-05-15 07:37 UTC, AntnSaj commented
Beim Navigieren der Trefferliste springt der Fokus beim betätigen von "Pfeiltaste nach unten" immer auf den dritten oder zweiten Eintrag in der Liste und beginnt nicht von Vorne (Siehe Screenshot). Fokus sollte von Vorne beginnen.
![image](https://github.com/public-ui/kolibri/assets/126143994/984622e0-4a53-4dd4-a80c-b27d7d4a2d5b)

Nach dem Auswählen von einem Element aus der Trefferliste wird manchmal das Label mit dem neuen Eintrag vorgelesen und manchmal der Dokumententitel. Das vorlesen des Dokumententitels ist hier falsch. Es scheint so, als wäre die Ausgabe beim ersten mal richtig und beim zweiten mal falsch.
Reproduzierbarkeit Ausgabe Titel: deu in das Input Feld eingeben --> Deutschland auswählen (Screenreader Ausgabe siehe nachfolgenden Screenshot)
![image](https://github.com/public-ui/kolibri/assets/126143994/4b6acf66-b383-4e1e-91ae-0aa1122de848)

2024-05-16 04:07 UTC, deleonio requested changes

2024-05-16 04:07 UTC, deleonio commented on packages/components/src/components/combobox/style.scss
@anicyne @sdvg Wie ist hier der Stand?!

2024-05-16 10:32 UTC, sdvg requested changes

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +		display: block;
Ist bereits ein block element

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/readme.md
> +<kol-combobox _options="[{'label':'Herr','value':0},{'label':'Frau','value':1},{'label':'Firma','value':2}]" _value="1"> Auswahlfeld </kol-combobox>
_suggestions

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/readme.md
> +<kol-combobox _options="[{'label':'Herr','value':0},{'label':'Frau','value':1},{'label':'Firma','value':2}]" _value="1"> Auswahlfeld </kol-combobox>
Sind glaube ich auch keine Objekte -> Readme müsste hier einmal überarbeitet werden.

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +	//Block: .combobox
Kommentar kann auch meiner Sicht weg. Wurde glaube ich aus einer andere Komponente kopiert

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +			text-align: left;
Ist das wirklich notwendig, welche Property überschreiben wir?

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +			min-height: var(--a11y-min-size);
Redundt, da bereits auf dem Input gesetzt?

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +			cursor: text;
Redundant, oder?

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +			&--hidden {
Würde hier vorschlagen, stattdessen mit dem HTML-Attribut `hidden` zu arbeiten.
Verwenden wir auch an anderen Stellen, wäre also konsistenter.

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	private _filteredOptions?: SuggestionsPropType;
Für mehr Konsistenz würde ich das ebenfalls zu `_filteredSuggestions` umbenennen.

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	private _filteredOptions?: SuggestionsPropType;
(überall options -> suggestions)

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +			this._isOpen = this._filteredOptions && this._filteredOptions.length > 0 ? true : false;
```suggestion
	this._isOpen = this._filteredOptions && this._filteredOptions.length > 0;
```

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +			const optionElement = this.host.shadowRoot.querySelector(`li[data-index="${index}"]`) as HTMLElement;
Können wir hier refs verwenden, um DOM Operationen zu vermeiden?

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +		if ((index as number) >= 0) {
`index` kann `false` sein und sollte entsprechend behandelt werden, statt der type assertion.

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +			<Host class={{ 'kol-combobox': true, combobox: true }}>
(wofür) brauchen wir hier `combobox`? So ist es doppelt definiert (auf host und div)

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +									aria-expanded="false"
Müssen wir das nicht auf `true` setzen, wenn die Suggestions offen sind?

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +									title=""
Hat dieses Attribut eine Bedeutung?

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +												if (e.key === 'Enter' || e.key === ' ') {
Bitte auch `NumpadEnter` behandeln

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +												if (e.key === 'Enter' || e.key === ' ') {
` ` ist space? Da wäre ein Inline-Kommentar nützlich :)

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +		const handleEvent = (val?: boolean, callback?: () => void): void => {
Können wir für `val` einen sprechenderen Namen verwenden, z.B. `isOpen`?

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +		const handleEvent = (val?: boolean, callback?: () => void): void => {
(würde die Konstante aus L229 shadowen, aber die ist vielleicht nicht wirklich notwendig?)

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +		(this.host as HTMLKolComboboxElement) && this.host != undefined && !this.host.contains(event.target as Node) && (this._isOpen = false);
Die erste Expression ist eine no-op, glaube ich.
Außerdem würde ich vorschlagen, aus dem Einzeiler zwecks Lesbarkeit einen richtigen if-Block zu machen, aber das bleibt dir überlassen:

```
if (this.host != undefined && !this.host.contains(event.target as Node)) {
			this._isOpen = false;
		}
```

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	private readonly controller: ComboboxController;
Um den Lesefluss zu verbessern, würde ich diese drei Eigenschaften (controller und die states) vor den Methoden definieren.

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	@Prop() public _error?: string;
Bitte entfernen, da in anderen Komponenten bereits deprecated.

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	 * Suggestions the user can choose from, also supporting Optgroup.
```suggestion
	 * Suggestions the user can choose from.
```

2024-05-16 10:32 UTC, sdvg commented on packages/components/src/components/combobox/controller.ts
> +	protected readonly afterPatchOptions = (value: unknown, _state: Record<string, unknown>, _component: Generic.Element.Component, key: string): void => {
Kann es sein, dass diese Methode nicht verwendet wird?

2024-05-16 10:32 UTC, sdvg commented on packages/samples/react/package.json
> +		"@webpack-cli/init": "1.1.3",
Wo kommen diese Änderungen her bzw. warum sind sie notwendig?

2024-05-16 10:32 UTC, sdvg commented on packages/samples/react/src/components/combobox/basic.tsx
> +			Her&apos;s Combobox example: This Combobox merges a text input with a dropdown list, enabling users to type or select their choice.
Typo, aber ich würde den Anfang einfach weglassen.
> The Combobox merges a text input with a suggestion list, enabling users to type or select their choice.

2024-05-16 10:32 UTC, sdvg commented on packages/themes/bmf/src/components/combobox.scss
> +			border: none;
Doppelte Property

2024-05-16 10:32 UTC, sdvg commented on packages/samples/react/src/components/combobox/basic.tsx
Ich würde mir hier mehr Beispiel wünschen, analog input-text z.B.
Aktuell kann man nicht alle Props testen.

Ich habe z.B. testweise mal `_disabled` gesetzt und das funktioniert nicht korrekt.
<img width="1333" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/fedeb06f-2e70-4bbf-ba51-2d378ab846dd">

2024-05-21 07:53 UTC, sdvg commented on packages/samples/react/src/components/combobox/basic.tsx
Bei Disabled stimmen die Cursor noch nicht:

<img width="315" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/e34d32cc-e5e9-4031-8bfa-ba784a8a263c">
In der ersten Box wird ein `pointer` cursor gezeigt, in der zweiten `text`. Es sollte durchgängig, über die ganze Fläche der `not-allowed` cursor sein.

2024-05-21 07:53 UTC, sdvg commented on packages/themes/bmf/src/components/combobox.scss
> +			width: -webkit-fill-available;
Das funktioniert leider z.B. in Firefox nicht.

2024-05-21 08:49 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +			max-height: 15.625rem;
Hier müssen wir die `rem()`-Funktion verwenden (Siehe L6), sonst skaliert die Komponente ggf. falsch.

2024-05-21 08:49 UTC, sdvg commented on packages/components/src/components/combobox/readme.md
> +<kol-combobox _suggestions="['Herr','Frau','Firma']" _value="Herr"> Auswahlfeld </kol-combobox>
Die Labels funktionieren so nicht, müssten wenn dann im Expert Slot stehen. Besser wäre aber: `_label`-Property

2024-05-21 08:49 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	private _filteredOptions?: SuggestionsPropType;
@anicyne Dieser Kommentar ist noch offen

2024-05-21 08:49 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +			this._isOpen = this._filteredOptions && this._filteredOptions.length > 0 ? true : false;
@anicyne Dieser Kommentar ist noch offen

2024-05-21 13:55 UTC, sdvg commented on packages/components/src/components/combobox/component.tsx
> +	@Prop() public _error?: string;
Ist noch nicht vollständig entfernt, der Watcher ist noch da. Bitte auch andere Stellen prüfen.

2024-05-21 14:11 UTC, sdvg commented on packages/components/src/components/combobox/shadow.tsx
> +	private focusSuggestionstartingWith(char: string) {
```suggestion
	private focusSuggestionStartingWith(char: string) {
```

2024-05-21 14:13 UTC, sdvg commented on packages/themes/default/src/components/combobox.scss
> +			width: calc(100% - 2.5rem);
Bitte für alle `rem`-Wert noch die `rem`-Funktion benutzen (Gibt es aktuell für Component-Styles und das Default-Theme)

2024-05-22 08:54 UTC, sdvg commented on packages/components/src/components/combobox/readme.md
> +<kol-combobox _suggestions="['Herr','Frau','Firma']" _value="Herr"> Auswahlfeld </kol-combobox>
Das ungültige Label ("Auswahlfeld") ist noch da und sollte entfernt werden.
Um beim Beispiel zu bleiben fände ich als Label "Anrede" sinnvoll.

```
<kol-combobox _suggestions="['Herr','Frau','Firma']" _value="Herr" _label="Anrede"></kol-combobox>
```

2024-05-22 08:57 UTC, sdvg commented on packages/components/src/components/combobox/style.scss
> +			max-height: 15.625rem;
Die rem-Werte müsstest du dir noch einmal anschauen: Die rem-Funktion rechnet praktisch von px nach rem um. Du musst die Zahlen also entsprechend umrechnen, bevor du sie in die `rem`-Funktion gibst.
Aus `15.625rem` wird z.B. `rem(250)`

2024-05-22 09:34 UTC, sdvg approved these changes, later dismissed

2024-05-24 07:35 UTC, deleonio submitted a review, later dismissed

2024-05-24 07:40 UTC, merged