(#6258) Added documentation link to sample description
public-ui/kolibri pull request #6371
Opened 2024-04-26 08:17 UTC by chrisalat

2024-04-26 08:18 UTC, chrisalat commented
I have read the CLA Document and I hereby sign the CLA

2024-04-26 09:52 UTC, laske185 approved these changes

2024-04-26 09:55 UTC, laske185 requested changes

2024-04-26 09:55 UTC, laske185 commented on packages/samples/react/src/components/SampleDescription.tsx
> +				<KolLink _hideLabel _href={`${location.href}?hideMenus`} _label="Beispiel in neuem Tab öffnen" _target="_blank" className="mla flex-self-center" />
Ich empfände es als besser, wenn das Label nicht versteckt wird und dafür kürzer: „Dokumentation“ und „Beispiel“. Dass es in einem neuen Tab geöffnet wird, zeigt das Icon an.

2024-04-29 13:46 UTC, deleonio requested changes

2024-04-29 13:46 UTC, deleonio commented on packages/samples/react/src/components/SampleDescription.tsx
> +				<KolLink _hideLabel _href={`${location.href}?hideMenus`} _label="Beispiel in neuem Tab öffnen" _target="_blank" className="mla flex-self-center" />
@chrisalat den Vorschlag von Peter finde ich hier gut. Die Component macht das out-of-the-box.

2024-04-29 13:46 UTC, deleonio commented on packages/samples/react/src/components/SampleDescription.tsx
> +			<div className="links">
@chrisalat Hi Chris. Statt eine eigene CSS-Klasse gerne einfach `tailwindcss` Klassen verwenden.

`class="flex flex-wrap gap-2"`

2024-04-29 14:21 UTC, deleonio approved these changes

2024-04-29 14:21 UTC, deleonio commented on packages/samples/react/src/components/SampleDescription.tsx
> +			<div className="links">
thx

2024-04-29 14:21 UTC, merged