5859 table selection stateless
public-ui/kolibri pull request #6389
Opened 2024-04-30 10:29 UTC by sdvg

2024-05-02 08:00 UTC, laske185 requested changes

2024-05-02 08:00 UTC, laske185 commented on packages/components/src/components/table-stateless/readme.md
> +    label: (row: KoliBriTableCell[]) => `Selection for ${(row.data as Data).name}`,
Der Typ von `row` ist nicht korrekt.

Er müsste laut Definition so aussehen:
```ts
label: (row: KoliBriTableDataType) => string;
```

2024-05-14 08:32 UTC, sdvg commented on packages/components/src/components/table-stateless/readme.md
> +    label: (row: KoliBriTableCell[]) => `Selection for ${(row.data as Data).name}`,
Danke! Ist korrigiert.

2024-05-16 04:07 UTC, deleonio submitted a review, later dismissed

2024-05-16 04:08 UTC, deleonio commented
@laske185 Passt jetzt alles?!

2024-05-16 12:53 UTC, laske185 commented
> @laske185 Passt jetzt alles?!

Ja

2024-05-16 12:54 UTC, laske185 approved these changes

2024-05-16 12:54 UTC, merged