Implementation of Toolbar component
public-ui/kolibri pull request #6405
Opened 2024-05-08 06:57 UTC by chrisalat

2024-05-14 03:52 UTC, deleonio requested changes
Im Großen und Ganzen schon ganz gut.

Jetzt müssten wir das Szenario noch weiter für reale Szenarien ausbauen.

2024-05-14 03:52 UTC, deleonio commented on packages/components/src/components/toolbar/constants.ts
> +export const TOOLBAR_ITEM_TAG_NAME = 'kol-toolbar-item';
Das Auslagern sollten wir erst dann machen, wenn die Konstante in mehreren anderen Dateien verwendet wird.

2024-05-14 03:55 UTC, deleonio requested changes
Suche bitte mal die `stencil.config.js` dort muss noch die neue Toolbar-Komponente eingetragen werden.

https://github.com/public-ui/kolibri/blob/5728-toolbar-component/packages/components/stencil.config.ts

2024-05-14 03:55 UTC, deleonio commented on packages/components/src/components/toolbar/readme.md
Muss später noch ausführlicher werden.

2024-05-22 14:53 UTC, chrisalat commented
Vielleicht noch zwei Anmerkungen:

1. Sollen wir die Links im BMF-Theme weiß gestalten?
2. Lassen wir `aria-controls` erstmal weg oder sollen wir die noch umsetzen? Falls ja, über eine `id` gesteuert oder direkt als Attribut `_ariaControls`?

2024-05-24 07:48 UTC, sdvg commented
@chrisalat Ich würde die neuen Test-Routen gerne noch für das visuelle Testing aufnehmen. Siehe `packages/tools/visual-tests/tests/sample-app.routes.js`. Dort eintragen und anschließend [Snapshots erstellen](https://github.com/public-ui/kolibri/blob/develop/CONTRIBUTING.md#snapshot-testing-for-visual-changes).

2024-05-24 07:53 UTC, sdvg commented
@chrisalat Das disabled-Beispiel scheint mir nicht ganz richtig zu funktionieren:

<img width="525" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/0a063b7e-cd6d-4433-8d75-89b5d26010da">

Hier sind die Items 1 und 3 aktiv. Wenn ich 1 aktiviert habe, würde ich davon ausgehen, dass ich mit einmal `Pfeiltaste rechts` drücken zu Item 3 komme. Aktuell muss ich zwei mal drücken.

2024-05-24 08:26 UTC, sdvg requested changes

2024-05-24 08:26 UTC, sdvg commented on packages/components/src/components/toolbar/shadow.tsx
> +					{(this.state._items as ToolbarItemPropType[]).map(this.renderElement)}
Type assertion scheint nicht notwendig zu sein

2024-05-24 08:26 UTC, sdvg commented on packages/components/src/components/toolbar/shadow.tsx
> +		return this.host.shadowRoot?.querySelector('.toolbar');
Ich würde gerne alle DOM-Queries durch Refs ablösen, da diese nativ von Stencil unterstützt werden: https://stenciljs.com/docs/templating-jsx#getting-a-reference-to-a-dom-element

Betrifft `getToolbar` (die Methode wird dann überflüssig) und `getToolbarItems`

2024-05-24 08:26 UTC, sdvg commented on packages/components/src/components/toolbar/shadow.tsx
> +	private renderElement = (element: ToolbarItemPropType, index: number): JSX.Element => {
```suggestion
	private renderItem = (element: ToolbarItemPropType, index: number): JSX.Element => {
```
Dann ist es konsistent mit der übrigens Benennung :)

2024-05-24 08:26 UTC, sdvg commented on packages/components/src/components/toolbar/shadow.tsx
> +		toolbarItems?.forEach((item, index) => {
Perfekter use-case für `.find`, oder?

Und opinionated: Sollten wir nicht lieber in der "source of truth", den `this.state._items` suchen, statt in den gerenderten Elementen?

2024-05-24 08:26 UTC, sdvg commented on packages/components/src/components/toolbar/shadow.tsx
> +			return toolbar?.blur();
Welchen Effekt hat das bzw. wozu brauchen wir es?

2024-05-24 08:26 UTC, sdvg commented on packages/components/src/components/toolbar/shadow.tsx
> +	@Listen('focusin')
Wird diese Logik (focusin und blur) tatsächlich gebraucht?
Eigentlich sollten sich die toolbar-items durch die tabindexes bereits korrekt fokussieren lassen. So stelle ich es mir zumindest vor, korrigiere mich hier gerne.

2024-05-24 08:52 UTC, chrisalat commented
@sdvg Laut dem Beispiel von W3C müssen die disabled Elemente trotzdem fokussiert werden. Meine erste Logik war tatsächlich dafür gedacht die Element zu überspringen. Hab ich aber dann wieder entfernt :)

> @chrisalat Das disabled-Beispiel scheint mir nicht ganz richtig zu funktionieren:
> 
> <img alt="image" width="525" src="https://private-user-images.githubusercontent.com/971072/333501019-0a063b7e-cd6d-4433-8d75-89b5d26010da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDA1NjYsIm5iZiI6MTcxNjU0MDI2NiwicGF0aCI6Ii85NzEwNzIvMzMzNTAxMDE5LTBhMDYzYjdlLWNkNmQtNDQzMy04ZDc1LTg5YjVkMjYwMTBkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwODQ0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTUxMmU3YWIyMmM5YmNlMTNlOWEwNmE3OGIxYmU5ZDBlZDNhNTRmYWU5OTZjNDg5YzMwMTJmZWNiZmE0YTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._PnBQgu6a_0-fmjUwLfJcL0o6jDftceXEf2URiGpXNU">
> Hier sind die Items 1 und 3 aktiv. Wenn ich 1 aktiviert habe, würde ich davon ausgehen, dass ich mit einmal `Pfeiltaste rechts` drücken zu Item 3 komme. Aktuell muss ich zwei mal drücken.

2024-05-24 08:54 UTC, chrisalat commented on packages/components/src/components/toolbar/shadow.tsx
> +			return toolbar?.blur();
Durch den Keyboard-Listener wird derzeitig das `Tab`-Event ausgehebelt. Deshalb mach ich den blur manuell.

2024-05-24 08:59 UTC, deleonio requested changes

2024-05-24 08:59 UTC, deleonio commented on packages/components/src/components/toolbar/component.tsx
> +		return element.querySelector('kol-button, kol-link') as HTMLElement | null;
`return element.querySelector('button, a') as HTMLElement | null;`

2024-05-24 08:59 UTC, deleonio commented on packages/components/src/components/toolbar/component.tsx
> +			{'_href' in element ? <KolLinkTag {...element}></KolLinkTag> : <KolButtonTag {...element}></KolButtonTag>}
`{'_href' in element ? <KolLinkWcTag {...element}/> : <KolButtonTag {...element}/>}`

2024-05-24 08:59 UTC, deleonio commented on packages/components/src/components/toolbar/shadow.tsx
> +	@Listen('focusin')
Ich vermute, so ja auch bei den Tabs, dass man das Markup zwar ändert, aber der Fokus nicht automatisch mitgeht und somit explizit gesetzt werden muss.

2024-05-24 13:10 UTC, sdvg approved these changes, later dismissed

2024-05-24 13:53 UTC, sdvg approved these changes, later dismissed

2024-05-24 17:13 UTC, deleonio approved these changes

2024-05-24 17:13 UTC, merged