(#6186) Adjust input field behavior to keep placeholder text visible
public-ui/kolibri pull request #6406
Opened 2024-05-08 08:53 UTC by anicyne

2024-05-08 10:08 UTC, laske185 requested changes

2024-05-08 10:08 UTC, laske185 commented on packages/components/src/components/input-text/component.tsx
> +							onFocus={console.log}
console.log entfernen

2024-05-08 10:08 UTC, laske185 commented on packages/components/src/components/input-text/component.tsx
> +	private showPlaceholder = true;
`showPlaceholder` wird nie `false`

2024-05-14 03:46 UTC, deleonio requested changes
@anicyne / @laske185 

Könnt Ihr mal schauen, ob das "einfacher" ohne State und Methode umgesetzt werden kann?

Einfach:

```tsx
	maxlength={this.state._maxLength}
	name={this.state._name}
	pattern={this.state._pattern}
	placeholder={this.ref?.value === '' || this.ref?.value === undefined ? this.state._placeholder : undefined}
	readOnly={this.state._readOnly}
	required={this.state._required}
	size={this.state._size}
```

2024-05-14 03:46 UTC, deleonio commented on packages/components/src/components/input-text/component.tsx
> +	private readonly SetShowPlaceholder = () => {
Kleine Korrektur: Methoden-Namen beginnen immer mit einem kleinen Buchstaben.

2024-05-16 04:42 UTC, deleonio commented
@AntnSaj 

```ts
		/**
		 * Beim Screenreader NVDA wird der Placeholder mit
		 * vorgelesen. Somit kann es vorkommen, dass das
		 * Label und der Placeholder vorgelesen werden.
		 *
		 * Aufgrund dessen, dass das Label immer vorgelesen
		 * werden muss, kann das zusätzliche Vorlesen des
		 * Placeholders störend sein.
		 *
		 * Damit beim Fokussieren das "doppelte" vorlesen
		 * vermieden werden kann, wird der Placeholder für
		 * den fokussierten Feldstatus entfernt.
		 *
		 * Hinweis: Für alle Nutzenden müssen alle darge-
		 *          stellten Inhalte, also auch der Place-
		 *          holder, gleichermaßen zugänglich sein.
		 *          Das oben beschriebene Handling erfüllt
		 *          diese Anforderung nicht.
		 */
```

2024-05-16 09:02 UTC, AntnSaj commented
Auf Barrierefreiheit getestet. Es wurde kein Fehler hinsichtlich Barrierefreiheit gefunden

2024-05-16 11:12 UTC, deleonio reviewed
FYI @anicyne

2024-05-16 11:13 UTC, deleonio approved these changes
FYI @anicyne

2024-05-16 11:14 UTC, merged