Implement missing keyboard shortcuts for tree navigation
public-ui/kolibri pull request #6415
Opened 2024-05-13 09:23 UTC by anicyne

Refs: #6160

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title for the release notes
- [x] Pull request is linked to a problem
- [x] All changes relate to the problem
- [x] A11y tests performed successfully or not relevant
- [x] Manual test performed successfully (by reviewer) or not relevant

2024-05-14 09:45 UTC, sdvg requested changes

2024-05-14 09:45 UTC, sdvg commented on packages/components/src/components/tree/component.tsx
> +				const warpAroundItems = openItems.concat(openItems);
```suggestion
				const wrapAroundItems = openItems.concat(openItems);
```
typo, vermute ich 👀

2024-05-14 09:45 UTC, sdvg commented on packages/components/src/components/tree/component.tsx
> +					event.preventDefault();
`preventDefault` brauchen wir in jedem Fall, ist dupliziert -> Wir können es vor dem `if`-Block platzieren/

2024-05-14 09:45 UTC, sdvg commented on packages/components/src/components/tree/component.tsx
> +				if (!(await currentTreeItem.isOpen())) {
Zur besseren Lesbarkeit würde ich die `if` und `else`-Blöcke gerne umdrehen: Erst `if(await currentTreeItem.isOpen())`, dann der closed-Case.

Als Referenz/Erklärung (wir haben die Regel nicht aktiviert): https://eslint.org/docs/latest/rules/no-negated-condition

2024-05-15 08:03 UTC, sdvg submitted a review, later dismissed

2024-05-16 11:15 UTC, deleonio commented
@AntnSaj bitte testen

2024-05-27 13:45 UTC, fohi17 commented
@deleonio Ich gehe davon aus, dass es hier nur um die shortcuts ging und lasse daher Screenreader außen vor.
Es ist zwar nicht unbedingt ein BF-Tema, aber wenn man auf einem Unterpunkt Pfeil-Nach-Links drückt kommt man nur zur Parent-Node wenn es das erste Kind-Element ist. Ist man z.B. auf dem zweiten Unterelement in einer Ebene springt der Fokus mit Pfeil-Nach-Links zum Unterelement davor, statt auf den Parent.

2024-05-30 06:39 UTC, laske185 commented
Änderung:

- Mit Pfeil-Taste-Links springt man immer zum Parent-Node, wenn der aktuelle Knoten nicht aufgeklappt ist
Beispiel in Demo-App:
- Fokus auf 3.1.2 Coffee makers
- Pfeil Links
- Fokus geht zu 3.1Home

2024-05-30 11:48 UTC, laske185 approved these changes

2024-05-30 11:48 UTC, merged