Update Tag Names for kol-input Kol-tooltip
public-ui/kolibri pull request #6450
Opened 2024-05-21 14:21 UTC by anicyne

Refs: #6105

2024-05-22 13:14 UTC, laske185 requested changes
Ich finde es nicht gut, dass viele CSS Klassen umbenannt wurden. Denn jetzt muss jedes Theme (auch die internen) angepasst werden.

Mit dem Akzeptanzkriterium "Klassen-Name mit Wc bei allen Komponenten wo shadow: false ist" waren sicherlich die JS-Klassen gemeint. Nicht die CSS-Klassen.

2024-05-24 07:45 UTC, deleonio commented
@anicyne @sdvg @laske185 : Peter und ich hatten gestern darüber gesprochen. Wir sollten alle CSS-Klassen von dem Konzept Shadow- oder NoShadow-Component (WC) unberührt lassen. Alles CSS-Klassen und die Styles sollen eh nur gegen die WC-Components definiert werden und die Shadow-Komponenten sind nur für den Schutz von außen.

Für `v3`sollten alle CSS-Klassen kein `-wc` mehr haben.

Daher hier, bitte alles CSS-Klassen zurücksetzen.

2024-05-30 04:59 UTC, deleonio approved these changes

2024-05-30 08:26 UTC, laske185 approved these changes

2024-05-30 08:26 UTC, merged