Implement selection feature for KolTableStateful
public-ui/kolibri pull request #6477
Opened 2024-05-28 14:25 UTC by anicyne

2024-05-30 08:24 UTC, laske185 requested changes

2024-05-30 08:24 UTC, laske185 commented on packages/components/src/components/table-stateful/shadow.tsx
> +			if (keyPropertyName) selectedData = this.state._sortedData.filter((item) => value.includes(item[keyPropertyName] as string));
Das Ermitteln der selektierten Daten wird an zwei Stellen gemacht. Es wäre schön, wenn das in eine private Funktion ausgelagert und dann hier im `handleSelectionChange` und in `public async getSelection()` verwendet wird.

2024-05-30 08:24 UTC, laske185 commented on packages/components/src/components/table/shadow.tsx
> +				_selection={this._selection}
Die `_on`-Prop fehlt.

2024-05-30 11:52 UTC, laske185 approved these changes

2024-05-30 12:00 UTC, laske185 requested changes
Die Demo zeigt immer andere Selektionen an, als gerade wirklich angehakt sind.

2024-06-05 10:35 UTC, deleonio requested changes
Get Selection auch bei https://6659bd80497f3a2b8aaaf936--kolibri-public-ui.netlify.app/#/table/stateless-with-selection Beispiel

2024-06-06 13:20 UTC, laske185 approved these changes, later dismissed

2024-06-06 14:01 UTC, sdvg commented on packages/components/src/components/table/shadow.tsx
> +		console.log(this._selection);
Bitte noch entfernen

2024-06-07 07:23 UTC, sdvg approved these changes

2024-06-07 07:23 UTC, deleonio approved these changes

2024-06-07 07:23 UTC, merged