Issue discussion templates & workflow update
public-ui/kolibri pull request #6499
Opened 2024-06-04 07:50 UTC by chrisalat

2024-06-04 12:49 UTC, sdvg requested changes
Gefällt mir gut insgesamt! Habe eigentlich fast nur ein paar Formulierungsvorschläge.

2024-06-04 12:49 UTC, sdvg commented on packages/tools/kolibri-cli/README.md
> +  info						  Shows the system and KoliBri package informations
```suggestion
  info						  Shows the system and KoliBri package information
```

2024-06-04 12:49 UTC, sdvg commented on packages/tools/kolibri-cli/README.md
> +With the `info` command you can show the actual system and KoliBri package informations.
```suggestion
With the `info` command you can show the current system and KoliBri package information.
```

2024-06-04 12:49 UTC, sdvg commented on packages/tools/kolibri-cli/src/info/index.ts
> +	const relevantPackages = [
Vorschlag, damit wir es in Zukunft nicht so oft anpassen müssen: Können wir alles mit `@public-ui/*` matchen?

2024-06-04 12:49 UTC, sdvg commented on packages/tools/kolibri-cli/src/info/index.ts
> +		.description('This command returns informations about your system.')
```suggestion
		.description('This command returns information about your system.')
```

2024-06-04 12:49 UTC, sdvg commented on .github/DISSCUSSION_TEMPLATE/q-a.yml
> +        Any code snippets, error messages, or dependency details that may be related? (`kolibri info`)
Das mit der CLI würde ich versuchen, einfacher und klarer zu machen:
```suggestion
        Any code snippets, error messages, or dependency details that may be related? (Please run `$ npx @public-ui/kolibri-cli info` and paste the result)
```

2024-06-04 12:49 UTC, sdvg commented on .github/ISSUE_TEMPLATE/1.bug_report.yml
> +      label: Which theme(s) are affected? / Welche(s) Layout(s) ist/sind betroffen?
```suggestion
      label: Which theme(s) are affected? / Welche(s) Theme(s) ist/sind betroffen?
```
(Wir haben es auch auf dt. immer als Themes bezeichnet)

2024-06-04 12:49 UTC, sdvg commented on .github/ISSUE_TEMPLATE/1.bug_report.yml
> +      placeholder: Nativ (shadow), React, Angular, ...
```suggestion
      placeholder: Nativ (Web Component), React, Angular, ...
```

2024-06-05 10:30 UTC, deleonio requested changes

2024-06-05 10:30 UTC, deleonio commented on .github/ISSUE_TEMPLATE/1.bug_report.yml
> +      placeholder: Nativ (Web Component), React, Angular, ...
Bitte `Native` mit `e`.

2024-06-05 10:30 UTC, deleonio commented on .github/ISSUE_TEMPLATE/1.bug_report.yml
> +        - 'Logo'
kein `Logo` bitte

2024-06-05 10:30 UTC, deleonio commented on .github/ISSUE_TEMPLATE/1.bug_report.yml
> +        - 'Appointment-Form (Scenario)'
keine Szenarien bitte

2024-06-05 10:30 UTC, deleonio commented on .github/ISSUE_TEMPLATE/1.bug_report.yml
> +        - 'Handout'
kein `Handout` bitte

2024-06-05 10:30 UTC, deleonio commented on .github/ISSUE_TEMPLATE/1.bug_report.yml
> +        - 'Kolibri'
kein `Kolibri` bitte

2024-06-06 17:42 UTC, sdvg submitted a review, later dismissed

2024-06-06 18:08 UTC, deleonio submitted a review, later dismissed

2024-06-06 18:08 UTC, deleonio commented on packages/tools/kolibri-cli/src/info/index.ts
> +	yarn: getBinaryVersion('yarn'),
pnpm und yarn bitte noch tauschen.

2024-06-07 07:19 UTC, deleonio approved these changes

2024-06-07 07:20 UTC, sdvg approved these changes

2024-06-07 16:09 UTC, merged