Updated link.scss for underline issue
public-ui/kolibri pull request #6511
Opened 2024-06-07 07:03 UTC by Schollkolade

Refs: #6280

2024-06-07 16:08 UTC, deleonio requested changes
Bitte für alle Themes nachtesten und ggf. entsprechend anpassen.

2024-06-10 05:49 UTC, laske185 requested changes

2024-06-10 05:49 UTC, laske185 commented on packages/components/src/components/link.scss
>  	a:is(:focus, :hover):not([aria-disabled]),
`text-decoration-thickness: 0.2em;` muss nun auch auf das `kol-span` angewendet werden. Also das auch verschieben.

2024-06-26 06:41 UTC, laske185 approved these changes

2024-06-26 06:42 UTC, merged