Drawer component
public-ui/kolibri pull request #6553
Opened 2024-06-19 08:07 UTC by chrisalat

2024-06-25 08:55 UTC, sdvg commented on packages/samples/react/src/components/drawer/basic.tsx
Hier fände ich es noch gut, wenn man alle vier Ausrichtungen testen könnte.

Idealerweise ließe sich das auch über die URI (Search Param) ansteuern: Dann könnten wir die Ausrichtungen ebenfalls in den visuellen Snapshot-Tests abdecken.

2024-06-25 08:56 UTC, sdvg commented on packages/components/src/components/drawer/style.scss
Hatten wir leider vorher nicht erwähnt, aber bei neuen Komponenten sollten wir als CSS-Konvention direkt BEM verwenden, da wir mit der `v3` komplett darauf umstellen wollen.

https://css-tricks.com/bem-101/
https://getbem.com/introduction/

2024-06-25 09:41 UTC, chrisalat commented on packages/components/src/components/drawer/style.scss
Kenne ich setz ich selber ein ;)

2024-06-27 09:35 UTC, sdvg requested changes

2024-06-27 09:35 UTC, sdvg commented on packages/tools/visual-tests/tests/sample-app.routes.js
> +ROUTES.set('drawer/basic?align=bottom');
Die Routen mit Align scheinen nicht zu funktionieren, ich  sehe immer nur die Buttons.

2024-06-27 09:35 UTC, sdvg commented on packages/tools/visual-tests/tests/sample-app.routes.js
> +ROUTES.set('drawer/controlled', {
Bei den Routen ohne Align kann man immer nur die Buttons sehen. Hat m.M.n. keinen Mehrwert, würde ich aus dem Tests raus nehmen.

2024-06-27 09:35 UTC, sdvg commented on packages/samples/react/src/components/drawer/basic.tsx
Hier sehe ich als Anwender (Mensch) noch keine Möglichkeit, mir die verschiedenen Ausrichtungen anzuschauen. Würde ich z.B. über einen Radio-Button umsetzen.

2024-06-27 09:35 UTC, sdvg commented on packages/samples/react/src/components/drawer/controlled.tsx
> +					Hier ist ein Beispiel für einen kontrollierten Drawer. Dieser lässt sich öffnen und schließen über das Attribut _open. Ein Drawer als Modal (_modal)
Beschreibung ist nicht mehr aktuell (modal ist jetzt auch "kontrolliert" möglich).

2024-06-27 09:35 UTC, sdvg commented on packages/themes/default/src/components/drawer.scss
> +@layer kol-theme-component {
Ich fände es sinnvoll, auch eine Slide-Out-Animation zu haben.
Öffnen sieht jetzt super aus, Schleißen im Vergleich aber sehr abrupt.

2024-06-27 09:35 UTC, sdvg commented on packages/components/src/schema/props/modal.ts
> + * Makes the element not focusable and ignore all events.
Beschreibung passt nicht zur Prop

2024-06-27 09:35 UTC, sdvg commented on packages/components/src/components/drawer/style.scss
> +			padding: 0.5em;
Bitte rem (als Sass-function) verwenden

2024-06-27 09:35 UTC, sdvg commented on packages/components/src/components/drawer/shadow.tsx
> +		this._on?.onClose?.();
Sollte m.M.n. erst nach dem eigentlichen Schließen aufgerufen werden.

2024-06-27 09:35 UTC, sdvg commented on packages/components/src/components/drawer/shadow.tsx
> +			if (typeof value.onClose === 'function' || value.onClose === true) {
Wofür ist der `true`-Check?

2024-06-27 09:35 UTC, sdvg commented on packages/components/src/components/drawer/readme.md
> +<kol-drawer _label="Drawer" _open _modal _align="top" _on={{ onClose: () => void }}> </kol-drawer>
Das `_on`-Attribut funktioniert in der HTML-bzw. Webcomponent-Variante so leider nicht. Würde ich für das Beispiel wohl einfach weglassen.

2024-06-27 09:35 UTC, sdvg commented on packages/components/src/components/drawer/readme.md
> +    drawer._activeElement = drawerOpenButton;
`_activeElement` gibt es so als Prop nicht, oder?

2024-07-01 10:48 UTC, sdvg requested changes
Bei den Snapshots sehe ich noch die Buttons, keine Drawer.

2024-07-01 10:48 UTC, sdvg commented on packages/components/src/components/drawer/shadow.tsx
> +		const wrapper = this.dialogElement?.querySelector('.drawer__wrapper');
QuerySelector würde ich gerne wo es geht vermeiden. Ich denke, wir können hier direkt das Host-Element referenzieren: https://stenciljs.com/docs/host-element

2024-07-01 10:48 UTC, sdvg commented on packages/components/src/components/drawer/shadow.tsx
> +		if (!wrapper || wrapper === null) return;
Der zweite Check scheint mir redundant, da `null` bereits ein `falsy`-Wert ist.

2024-07-01 10:48 UTC, sdvg commented on packages/components/src/components/drawer/shadow.tsx
> +				class={`drawer__wrapper drawer__wrapper--${this.state._align as string} ${this.state._open ? 'drawer__wrapper--open' : `drawer__wrapper--${this.state._align as string}--close`}`}
Könnten wir da noch valides BEM draus machen, also die doppelten Modifier `--...--` vermeiden?

Entweder als regulärer modifier: `drawer__wrapper--left-close`
Oder, vielleicht klarer, als state, der dann mit dem Modifier kombiniert werden kann: `drawer__wrapper--left is-closing`

(Ich fände `is-closing` auch präziser als `close`).

2024-07-01 10:48 UTC, sdvg commented on packages/components/src/components/drawer/shadow.tsx
> +					class={`drawer__dialog drawer__dialog--${this.state._align as string} ${isOpen ? 'drawer__dialog--open' : `drawer__dialog--${this.state._align as string}--close`}`}
Siehe vorheriger Kommentar. Persönlich würde ich die Modifier nur einmal auf dem Host-Element definieren, aber das ist vielleicht Geschmackssache..

2024-07-01 10:48 UTC, sdvg commented on packages/components/src/components/drawer/shadow.tsx
> +			this._on?.onClose?.();
Hier fände ich es gut, wenn wir klar machen könnten, dass es das selbe Code-Fragment wie in L45 ist. Z.B. durch eine neue Methode. Sonst passt man zukünftig ggf. nur eine der beiden Stellen an.

2024-07-02 08:29 UTC, sdvg approved these changes

2024-07-02 08:30 UTC, merged