Tree: Add missing link aria-attribute
public-ui/kolibri pull request #6598
Opened 2024-07-04 07:43 UTC by sdvg

Refs: #6164

2024-07-08 10:51 UTC, laske185 requested changes

2024-07-08 10:51 UTC, laske185 commented on packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tree-basic-home-firefox-linux.png
Da der Link jetzt ohne Shadow ist muss er gestylt werden.

2024-07-08 12:17 UTC, sdvg commented on packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tree-basic-home-firefox-linux.png
Das kommt dann in: https://github.com/public-ui/kolibri/issues/6163
Ich habe das Styling hier bewusst ausgeklammert, weil es in #6163 komplett überarbeitet wird.

2024-07-10 11:55 UTC, laske185 approved these changes

2024-07-10 11:55 UTC, merged