Improve validation for input-date
public-ui/kolibri pull request #6622
Opened 2024-07-15 12:36 UTC by anicyne

2024-07-16 04:23 UTC, deleonio commented
Für Bugs wollen wir ja zukünftig immer Tests einführen, damit die Bugs nicht wiederkehren.

@sdvg: Hierfür könnten wir doch einen Playwright-Test schrieben?

2024-07-16 04:24 UTC, deleonio reviewed
Funktioniert. Ggf. noch Test nachziehen.

2024-07-16 07:50 UTC, sdvg commented on packages/components/src/components/input-date/controller.ts
> +			(value): boolean => {
Das Problem mit dieser Lösung ist, dass sich der Wert nicht mehr "von außen", als über die `_value`-prop zurücksetzen lässt. Vorher war es explizit erlaubt, den Wert auf `undefined`, `null` oder `''` zu setzen, das geht jetzt nicht mehr.

Das eigentliche Problem scheint mir hier zu liegen: https://github.com/public-ui/kolibri/blob/release/1.7/packages/components/src/components/input-date/component.tsx#L409

Ich weiß nicht, was der Code bezwecken sollte, wenn ich ihn entferne scheint mir aber alles zu passen.

2024-07-16 07:50 UTC, sdvg requested changes
https://github.com/public-ui/kolibri/pull/6622/files#r1678924320

2024-07-18 08:21 UTC, sdvg approved these changes

2024-07-18 08:23 UTC, merged