Expansion table selection
public-ui/kolibri pull request #6634
Opened 2024-07-17 06:26 UTC by chrisalat

2024-07-18 03:47 UTC, deleonio requested changes

2024-07-18 03:47 UTC, deleonio commented on packages/components/src/locales/de.ts
> +	'table-selection-intermediate': 'Teilweise Auswahl',
Ich empfehle: `Alle auswählen bei teilweiser Auswahl`

2024-07-18 03:47 UTC, deleonio commented on packages/components/src/locales/de.ts
> +	'table-selection-none': 'Alles abwählen',
Ich empfehle: `Alle abwählen`

2024-07-18 03:47 UTC, deleonio commented on packages/components/src/locales/de.ts
> +	'table-selection-all': 'Alles auswählen',
Ich empfehle: `Alle auswählen`

2024-07-18 03:47 UTC, deleonio commented on packages/components/src/locales/en.ts
> +	'table-selection-all': 'Select all',
Entsprechend Deutsch anpassen

2024-07-18 03:47 UTC, deleonio commented on packages/components/src/components/table-stateless/component.tsx
> +			key = dataKey ? `${dataKey}-${this.horizontal ? colIndex : rowIndex}` : key;
👍

2024-07-18 03:48 UTC, deleonio commented
Funktional scheint es zu passen ;-)

2024-07-18 08:39 UTC, sdvg commented on packages/samples/react/src/components/table/stateful-with-selection.tsx
Nur ein kleine Anmerkung:

Brauchen wir diese Änderung tatsächlich? Ich sehe gerade nicht, wo der neue State in diesem Beispiel genutzt wird. Das Konzept von TableStateless ist (unter anderem), dass sie den State intern speichern kann und man dann z.B. nur auf die Events reagieren kann. Es ist nicht in jedem Fall notwendig, den State nach außen zu reflektieren.

Falls wir den State hier tatsächlich benötigen, würde ich es bevorzugen, nur die sich tatsächlich ändernden Daten (`selectedKeys`) im State zu speichern, nicht das komplette `KoliBriTableSelection`-Objekt einschließlich label-Funktion.

2024-07-19 04:51 UTC, deleonio approved these changes

2024-07-19 04:51 UTC, merged