(#6207) Implemented @stencil-community/eslint-plugin
public-ui/kolibri pull request #6647
Opened 2024-07-18 14:06 UTC by chrisalat

2024-08-06 06:38 UTC, chrisalat commented
**Absprache**: `_alerts` in KolInputs werden erstmal mit eslint-disable-rule ignoriert

2024-08-08 15:57 UTC, sdvg commented on packages/components/src/components/@deprecated/input/controller.ts
> +					if (typeof hideError === 'boolean' && hideError) {
Ich glaube hier brauchen wir eine Grundsatzentscheidung, wie wir mit der Regel `@stencil-community/strict-boolean-conditions` umgehen wollen.

Die jetzt umgesetzte Lösung finde ich ein wenig problematisch, weil sie die Logik verändert.
Die in meinen Augen "korrekte" Lösung um die Regel zufrieden zu stellen wäre im einfachsten Fall:
```
if (Boolean(this.component.state._hideError)) {
```

Das steht aber leider im Konflikt zu Prettier, dass den Boolean Constructor (m.M.n. zurecht) entfernt. Wir bräuchten z.B. eine weitere Konstante als Workaround.

(Alternativ könnten wir auch versuchen die Types zu fixen, so dass die State-Properties nicht mehr `unknown` sind, das wäre aber eine andere Baustelle.)

2024-08-08 16:09 UTC, sdvg commented on packages/components/src/components/button/test/html.mock.ts
> +	<button${ariaControls != null ? ' aria-controls="nonce"' : ''}${
Die `!= null`-Operatoren würde ich lieber alle type-sicher umschreiben. Siehe auch: https://github.com/public-ui/kolibri/issues/6716
Die wurden jetzt leider an sehr vielen Stellen eingefügt.

2024-08-08 16:13 UTC, sdvg commented on packages/components/src/components/input-date/controller.ts
> +		if ((value !== '' && value !== null) !== Boolean(this.component._value)) {
Warum nicht wie vorher, mit Boolean-Constructor statt `!!`?

2024-08-08 16:16 UTC, sdvg commented on packages/components/src/components/input-range/controller.ts
> +		this.validateAutoComplete(this.component._autoComplete),
Was hat es mit dieser Änderung auf sich?

2024-08-08 16:17 UTC, sdvg commented on packages/components/src/components/input-range/shadow.tsx
> +			if (this._value !== undefined && typeof this.refInputNumber?.value === 'string') {
```suggestion
			if (this._value === undefined && typeof this.refInputNumber?.value === 'string') {
```
Müsste es nicht so herum sein?

2024-08-08 16:18 UTC, sdvg commented on packages/components/src/components/input-range/shadow.tsx
> +		if (this._value !== undefined && typeof this.refInputRange?.value === 'string') {
Siehe https://github.com/public-ui/kolibri/pull/6647/files#r1709860257

2024-08-08 16:21 UTC, sdvg requested changes
(siehe Einzelkommentare)

2024-10-28 09:07 UTC, closed without merging