Refactoring selection of table component
public-ui/kolibri pull request #6665
Opened 2024-07-24 14:47 UTC by chrisalat

2024-07-29 15:09 UTC, sdvg requested changes

2024-07-29 15:09 UTC, sdvg commented on packages/samples/react/src/components/table/stateful-with-single-selection.tsx
Könnten wir das neue Beispiel bitte auch in die visuellen Tests aufnehmen?

2024-07-29 15:09 UTC, sdvg commented on packages/samples/react/src/components/table/stateful-with-single-selection.tsx
> +		console.log('Selection change via callback', selection);
Wenn ich das Beispiel teste, sehe ich zwei mal das Event, aber nicht das Callback in der Konsole.
Zudem ist der Data-Type bei den beiden Events scheinbar verschieden.
![screenshot 2024-07-29-16 52 43@2x](https://github.com/user-attachments/assets/c86d0a75-8d01-4ce8-bc34-a9cbcff1818e)

2024-07-29 15:09 UTC, sdvg commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
Könnten wir hier Mixins verwenden, um die Checkbox/Radio-Styles nicht duplizieren zu müssen? Gilt für alle Themes.

2024-07-29 15:09 UTC, sdvg commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
> +			align-content: center;
Wofür brauchen wir diese Style-Änderungen, die über den Scope von der Selektion hinaus gehen? Kann das keine Auswirkungen auf bestehende Styles bzw. Nutzungen haben?

2024-07-29 15:09 UTC, sdvg commented on packages/components/src/components/@shared/_kol-table-stateless-mixin.scss
> +		.input {
Ich habe hier ein paar kleinere Styling-Probleme festgestellt:

- Bei InputRadio ist "unstyled" der checked-State nicht zu erkennen
- Bei InputCheckbox stimmt der Cursor nicht (sollte pointer sein)

Sofern hier Styles mit den Original-Komponenten geteilt werden: Würde es Sinn machen, Mixins zu verwenden?

2024-07-29 15:09 UTC, sdvg commented on packages/components/src/components/table-stateful/shadow.tsx
> +	private getSelectedData(selectedKeys: string[] | string): null | KoliBriTableDataType | KoliBriTableDataType[] {
Sollte `selectedKeys` (plural) nicht immer ein Array sein, wozu brauchen wir hier den `string` type? In der Verwendung (Sample App) hatte ich gesehen, dass die Selektion immer eine Array ist, auch bei `multiple: false`. Das fand ich okay und würde es so durchziehen.

2024-07-29 15:09 UTC, sdvg commented on packages/components/src/components/table-stateful/shadow.tsx
> +				if (keyPropertyName) return data;
`else if ()`? :)

2024-07-29 15:09 UTC, sdvg commented on packages/components/src/components/table-stateless/component.tsx
> +					<KolTooltipWcTag aria-hidden="true" class="input-tooltip" _align="right" _id={`${keyProperty}-label`} _label={label}></KolTooltipWcTag>
Wenn der Tooltip aria-hidden ist, haben wir für Screenreader kein sichtbares Label mehr, oder?

2024-07-29 15:09 UTC, sdvg commented on packages/components/src/components/table-stateless/component.tsx
> +									selections = this.state._data;
(Vorschlag) Wäre ein guter use case für einen ternary operator

2024-08-01 15:00 UTC, chrisalat commented on packages/samples/react/src/components/table/stateful-with-single-selection.tsx
> +		console.log('Selection change via callback', selection);
Jetzt ist die Frage. Geben wir nur die ID's aus oder das Dataset?

2024-08-01 15:13 UTC, chrisalat commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
> +			align-content: center;
Wollte damit einen Fehler lösen, welcher mit in Prod aufgefallen ist.

![image](https://github.com/user-attachments/assets/52baa33e-9dcb-444a-aa5c-c80ea741a8af)

2024-08-01 15:23 UTC, chrisalat commented on packages/components/src/components/table-stateful/shadow.tsx
> +	private getSelectedData(selectedKeys: string[] | string): null | KoliBriTableDataType | KoliBriTableDataType[] {
String-Wert ist hier tatsächlich eine Altlast, aber wir sollten nochmal bzgl. der Ausgabe sprechen, also was wir genau zurückgeben. Im Ticket steht nämlich das die Ausgabe unterschiedlich sein soll: `ReturnType getSelection: null | Item | Item[]`, aber die Frage ist, ob das für alle Funktionen gelten soll oder nur speziell für die `getSelection`

2024-08-01 15:30 UTC, chrisalat commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
Ich hatte tatsächlich auch duplicated styles in den Radios und Checkbox Komponenten gefunden. Sollen wir hier vielleicht ein neues Issue aufmachen für ein generelles refactoring oder das alles in dem Ticket abarbeiten?

2024-08-01 15:43 UTC, chrisalat commented on packages/components/src/components/@shared/_kol-table-stateless-mixin.scss
> +		.input {
Kannst du mir zu dem Punkt `Bei InputCheckbox stimmt der Cursor nicht (sollte pointer sein)` sagen wo genau? Weil eigentlich ist `cursor: pointer` bereits direkt auf dem input definiert.

2024-08-05 08:07 UTC, sdvg commented on packages/samples/react/src/components/table/stateful-with-single-selection.tsx
> +		console.log('Selection change via callback', selection);
Ich glaube ursprünglich war es mal so angedacht, dass die Stateless-Tabelle IDs zurückgibt und Stateful die Datesets. So sehe ich as auch in der Implementierung: https://github.com/public-ui/kolibri/pull/6477/files#diff-fe119f78e745e66aec0e2b7319b43f6570b18dd7525981c30f948b156c8394cdR522
Daran würde ich mich orientieren.

2024-08-05 08:08 UTC, sdvg commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
Ich würde es in diesem Ticket behandeln, weil wir die Situation sonst nur verschlimmern. Wenn es zu lange dauert, kannst du es auch in ein neues Ticket schreiben, das würde ich dann aber gerne bald einplanen.

2024-08-05 08:11 UTC, sdvg commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
> +			align-content: center;
Danke, da ergibt die Änderung natürlich Sinn. Könnten wir den Scope dennoch auf die Selektion-Checkbox beschränken, satt sämtlichen `td`-Content zu adressieren (möglicher Breaking-Change)?

2024-08-05 08:13 UTC, sdvg commented on packages/components/src/components/@shared/_kol-table-stateless-mixin.scss
> +		.input {
Gerade sieht es bei mir so aus (Netlify, Default theme). Da wo ich es eingezeichnet habe, bitte einen default cursor hindenken 😅 
![screenshot 2024-08-05-10 12 24@2x](https://github.com/user-attachments/assets/24f579aa-d84f-4b3f-b913-b2f3ee92933c)

2024-08-05 08:15 UTC, sdvg commented on packages/components/src/components/table-stateful/shadow.tsx
> +	private getSelectedData(selectedKeys: string[] | string): null | KoliBriTableDataType | KoliBriTableDataType[] {
Ja, am besten mal in der größeren Runde, z.B. im Daily. Ich fände wichtig, dass Event und `getSelection` einheitlich sind. Mit Präferenz auf `Item` statt `Item[]` im single-selection-Modus.

2024-08-06 06:25 UTC, chrisalat commented on packages/components/src/components/table-stateless/component.tsx
> +					<KolTooltipWcTag aria-hidden="true" class="input-tooltip" _align="right" _id={`${keyProperty}-label`} _label={label}></KolTooltipWcTag>
Wurde mit Screenreader getestet und Tooltip-Labels werden vorgelesen

2024-08-06 06:27 UTC, chrisalat commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
> +			align-content: center;
Absprache: Align-Content rückgängig machen und Checkboxen oben ausrichten

2024-08-06 06:28 UTC, chrisalat commented on packages/themes/bmf/src/mixins/kol-table-stateless-wc.scss
Wird erstmal nicht umgesetzt, da die Komponenten zu verschieden sind

2024-08-06 10:15 UTC, sdvg commented
@chrisalat Die Daten sollen wie folgt aus der Tabelle rausgegeben werden:

<table>
	<tr>
		<td colspan="2"></td>
		<th>
			KolTableStateless
		</th>
		<th>
			KolTableStateful
		</th>
	</tr>
	<tr></tr>
	<tr>
		<th rowspan="3">Multi Selection</th>
	</tr>
	<tr>
		<th>Event</th>
		<td>Array of IDs</td>
		<td>Array of Objects</td>
	</tr>
	<tr>
		<th>getSelection</th>
		<td>Array of IDs</td>
		<td>Array of Objects</td>
	</tr>
	<tr></tr>
	<tr>
		<th rowspan="3">Single Selection</th>
	</tr>
	<tr>
		<th>Event</th>
		<td>Single IDs</td>
		<td>Single Object</td>
	</tr>
	<tr>
		<th>getSelection</th>
		<td>Single ID</td>
		<td>Single Object</td>
	</tr>
</table>

2024-08-09 07:28 UTC, laske185 submitted a review, later dismissed

2024-08-09 15:51 UTC, chrisalat commented
#6610 wurde direkt in diesem Branch gelöst. Testbar unter https://66b635972c58d1152523cb6d--kolibri-public-ui.netlify.app/#/table/selection-key-by-data und deshalb erneute Review nötig.

2024-08-27 10:53 UTC, sdvg approved these changes

2024-08-28 06:02 UTC, deleonio commented on packages/components/src/components/@shared/_kol-table-stateless-mixin.scss
> +				cursor: pointer;
👍 Das war das, was ich wollte. Du hattest noch darauf hingewiesen und ich hatte nachgetestet. Es wurden Anmerkungen ungelöst resolved ... Danke!

2024-08-28 06:06 UTC, merged