Update input-radio with hint and description
public-ui/kolibri pull request #6695
Opened 2024-08-02 10:07 UTC by anicyne

Refs: #6455

2024-08-02 18:33 UTC, deleonio requested changes
Bitte in der Sample App alles auf Englisch  schreiben.

2024-08-06 09:47 UTC, deleonio submitted a review, later dismissed

2024-08-08 07:33 UTC, sdvg requested changes

2024-08-08 07:33 UTC, sdvg commented on packages/components/src/components/input-radio/shadow.tsx
> +						<span class="hint" id={`${this._id}-hint`}>
Wofür wird diese ID verwendet?

2024-08-08 07:33 UTC, sdvg commented on packages/components/src/schema/props/options.ts
> +export type RadioOptionPropType = Stringified<RadioOption<StencilUnknown>[]>;
Bitte bei allen neuen types mal den plural/singular checken. Hier sollte es `RadioOptionsPropType` heißen, oder?

2024-08-08 07:33 UTC, sdvg commented on packages/themes/bmf/src/components/input-radio.scss
> +		font-size: 0.875rem;
Bitte `rem()`-Funktion verwenden

(!) Bitte selber überall checken, ich will es nicht so oft kommentieren :)

2024-08-08 07:33 UTC, sdvg commented on packages/components/src/schema/types/input/types.ts
> +	description?: string;
@deleonio Ich sehe hier eine kleine API-Inkonsistenz: Die Property auf KolInput, für die wir die Description verwenden, heißt "hint", nicht "description". Wir vermischen also beide Begriffe. Wollen wir das angleichen, solange wir noch die Möglichkeit haben?

2024-08-08 07:33 UTC, sdvg commented on packages/themes/default/src/components/input-radio.scss
> +		display: grid;
Warum ist das jetzt ein Grid? Ist die Änderung wirklich notwendig? Ich sehe keine visuelle Änderung, wenn ich Property entferne.

2024-08-08 07:33 UTC, sdvg commented on packages/themes/ecl/src/components/ecl-ec/input-radio.scss
> +		display: grid;
Siehe Kommentar in Basis-Styles.

Bitte auch allgemein keine Styles in die Themes duplizieren, die bereits im Basis-Style definiert sind. Bitte auch andere Properties und Themes einmal auf Redundanzen prüfen.

2024-08-08 08:17 UTC, deleonio commented on packages/components/src/schema/types/input/types.ts
> +	description?: string;
@anicyne Ja, bitte immer Einheitlichkeit First. - Like: https://public-ui.github.io/docs/concepts/properties

Wir nehmen hier `hint`.

2024-08-08 08:39 UTC, anicyne commented on packages/components/src/schema/types/input/types.ts
> +	description?: string;
![image](https://github.com/user-attachments/assets/75b10929-5d7b-48de-9891-71757d3ec2a6)
Ich habe es wie im Ticket beschrieben und wie im Refinement besprochen umgesetzt. Aber kein Problem, ich ändere das auf "hint".

2024-08-08 09:17 UTC, deleonio commented on packages/components/src/schema/types/input/types.ts
> +	description?: string;
@anicyne Alles gut ... kein Vorwurf - war im Ticket noch nicht perfekt bedacht.

2024-08-08 11:52 UTC, anicyne commented on packages/themes/default/src/components/input-radio.scss
> +		display: grid;
ohne: 
![image](https://github.com/user-attachments/assets/349adb63-9899-475c-8576-64a1e35e5acc)
mit: 
![image](https://github.com/user-attachments/assets/e1f5f92b-fb35-4cc6-8554-954d2a6d4369)

2024-08-08 14:32 UTC, deleonio requested changes

2024-08-08 14:32 UTC, deleonio commented on packages/components/src/components/input-radio/shadow.tsx
> +					{hasHint && <span class="hint">{this._hint}</span>}
Achtung: `this.state._hint`

2024-08-08 14:32 UTC, deleonio commented on packages/components/src/components/input-radio/test/html.mock.ts
> +							{this._hint}
Achtung: `this.state._hint`

2024-08-08 14:32 UTC, deleonio commented on packages/components/src/components/input-radio/test/snapshot.spec.tsx
> +				{ label: 'Field 2', value: 2, description: 'description' },
hint

2024-08-09 14:01 UTC, deleonio submitted a review, later dismissed

2024-08-26 14:10 UTC, sdvg approved these changes

2024-08-26 14:10 UTC, merged