Add keyboard navigation in table-stateless
public-ui/kolibri pull request #6699
Opened 2024-08-05 06:35 UTC by anicyne

Refs: #6567

2024-08-06 07:20 UTC, anicyne commented
Bitte warten, bis [#6617](https://github.com/public-ui/kolibri/issues/6617) abgeschlossen ist.

2024-09-17 10:32 UTC, sdvg requested changes

2024-09-17 10:32 UTC, sdvg commented on packages/components/src/components/table-stateless/component.tsx
> +			if (focusedElement && this.checkboxRefs.includes(focusedElement)) {
(Vorschlag) Könnte vereinfacht werden zu
```suggestion
			if (index > -1) {
```

2024-09-17 10:32 UTC, sdvg commented on packages/components/src/components/table-stateless/component.tsx
> +					} catch (e) {
Ich würde hier im Normalfall keine Exceptions erwarten. Wenn doch welche auftreten, haben wir einen Bug, den ich nicht durch das try/catch "verstecken" sondern lieber throwen lassen würde, damit sie sofort auffallen und auch von Tools wie Sentry verarbeitet werden können.
Empfehlung: try/catch ganz entfernen.

2024-09-17 10:32 UTC, sdvg commented on packages/samples/react/src/components/table/stateful-with-selection.tsx
> +				_data={DATA.map((item) => ({ ...item, action: <KolButton _label={`click ${item.id}`}></KolButton> }))}
Das verstehe ich nicht. Die JSX-Node wird gar nicht gerendert, oder? Da wir sowieso die oben definierte Render-Funktion verwenden, scheint mir das ganze `map` nicht notwendig zu sein?

(Bitte auch die anderen Beispiele berücksichtigen)

2024-09-17 10:32 UTC, sdvg commented on packages/samples/react/src/components/table/stateful-with-selection.tsx
> +							{ key: 'action', label: 'Action', textAlign: 'left', render: (element) => renderButton(element) },
```suggestion
							{ key: 'action', label: 'Action', textAlign: 'left', render: renderButton },
```

(Bitte auch die anderen Beispiele berücksichtigen)

2024-09-17 14:25 UTC, sdvg submitted a review, later dismissed

2024-09-17 14:56 UTC, sdvg approved these changes

2024-09-17 14:56 UTC, merged