Replace dropdown with kolPopoverWc in Split-Button
public-ui/kolibri pull request #6726
Opened 2024-08-12 14:57 UTC by anicyne

Refs: #6725

2024-08-14 13:34 UTC, laske185 commented
Bitte einen playwright Test in components-Projekt schreiben. Als Vorlage kannst du dir den Test im Abbr anschauen: `packages\components\src\components\abbr\abbr.e2e.ts`

2024-08-26 09:12 UTC, laske185 requested changes

2024-08-26 09:12 UTC, laske185 commented on packages/components/src/components/popover/style.scss
> +	.kol-popover-wc {
Bei den CSS-Klassen bitte nicht das `-wc`-Suffix einbauen, da wir hier die Unterscheidung nicht haben.

2024-08-27 13:27 UTC, laske185 approved these changes

2024-08-27 13:31 UTC, laske185 requested changes
Open-State ist nicht immer synchron:
1. Splitbutton-Popover öffnen
2. Mit der Maus daneben klicken -> Popover geht zu
3. Auf den Pfeil des Splitbuttons mit der Maus gehen: Tooltip: "Hide options" - *FEHLER*
![image](https://github.com/user-attachments/assets/6cc26959-7327-44cc-844f-2346c4626f1d)
4. Auf Pfeil klicken -> Tooltip ändert sich in "Show options" 
5. Popover geht nicht auf - *Fehler*

2024-08-28 06:15 UTC, deleonio commented
Hi @Makko74, bitte übernimm diese Aufgabe. Danke Dir

2024-09-05 06:17 UTC, laske185 approved these changes

2024-09-05 06:17 UTC, merged