Git hooks precommit
public-ui/kolibri pull request #6730
Opened 2024-08-15 12:23 UTC by Makko74

ref #6661

2024-08-26 09:08 UTC, deleonio commented
@sdvg Hier hätte ich gerne Dein Feedback. Danke

2024-08-26 10:12 UTC, sdvg requested changes

2024-08-26 10:12 UTC, sdvg commented on .husky/pre-push
(Wozu) brauchen wir die leere Datei?

2024-08-26 10:12 UTC, sdvg commented on package.json
> +	"husky": {
Hier bitte noch formatieren (Prettier)

2024-08-26 10:12 UTC, sdvg commented on package.json
> +		"pre-push": "pnpm test"
Laut Ticket soll das nicht ausgeführt werden. Hat sich hier etwas geändert, muss das Ticket ggf. angepasst werden?

2024-08-26 10:12 UTC, sdvg commented on packages/components/package.json
> +		"*.ts|tsx|js|jsx": ["prettier --list-different src", "pnpm lint"],
Ich glaube, dass wir auch noch css, scss und md möglich sind. Könnten wir das noch prüfen?

2024-08-26 10:12 UTC, sdvg commented on packages/components/package.json
> +		"*.ts|tsx|js|jsx": ["prettier --list-different src", "pnpm lint"],
Im allgemeinen konfigurieren wir Tools in separaten Dateien, nicht in der package.json. Ich würde das auch hier gerne so fortführen, und die Konfiguration in eine .lintstagedrc verschieben: https://github.com/lint-staged/lint-staged?tab=readme-ov-file#configuration

2024-08-26 10:12 UTC, sdvg commented on packages/components/package.json
> +		"*.ts|tsx|js|jsx": ["prettier --list-different src", "pnpm lint"],
Wenn ich es teste, scheint es mit mit `pnpm lint` nicht korrekt zu funktionieren.
Mein Setup:

- Ich füge Linting-Fehler in zwei .ts-Dateien im Components-Package ein.
- Ich stage nur eine der Dateien.
- Alle Dateien im Package werden gelintet, beide Fehler ausgegeben.

Meine Vorstellung wäre gewesen, dass nur die "staged" Datei gelintet wird.

![screenshot 2024-08-26-12 11 44@2x](https://github.com/user-attachments/assets/66225a08-0081-45e1-991f-1470a75c3b40)

2024-10-23 06:58 UTC, laske185 requested changes

2024-10-23 06:58 UTC, laske185 commented on packages/components/src/components/combobox/test/html.mock.ts
> +	<div class="combobox__group">
Diese Änderung sollte rückgäng gemacht werden.

2024-10-25 09:55 UTC, laske185 approved these changes

2024-10-25 09:55 UTC, merged