Combobox unit test
public-ui/kolibri pull request #6734
Opened 2024-08-16 13:59 UTC by anicyne

Refs: #6452

2024-08-26 07:12 UTC, deleonio requested changes

2024-08-26 07:12 UTC, deleonio commented on packages/components/src/components/combobox/test/html.mock.ts
> +import { ComboboxProps, ComboboxStates, showExpertSlot } from '../../../schema';
Bitte für Types `import type` verwenden.

2024-08-27 08:14 UTC, sdvg approved these changes

2024-08-28 06:13 UTC, deleonio approved these changes

2024-08-28 06:13 UTC, merged