avatar: In chrome, the visible texts in the avatar shift when the font size is changed manually
public-ui/kolibri pull request #6742
Opened 2024-08-26 07:56 UTC by Makko74

Refs: #6638

vi als fontsize größe zusätzlich hinzugefügt (falls Browser es nicht unterstützen, wird weiterhin die alte fontsize verwendet)

2024-08-26 09:24 UTC, deleonio requested changes

2024-08-26 09:24 UTC, deleonio commented on packages/components/src/components/avatar/style.scss
> +		font-size: 2.7706vi;
Hi, warum nicht einfach: `font-size: 2.5rem;`

2024-08-26 09:48 UTC, Makko74 commented on packages/components/src/components/avatar/style.scss
> +		font-size: 2.7706vi;
2.5rem lösst nicht das Problem, höchstens ein fester Wert, also z.b 40px

2024-08-26 09:58 UTC, sdvg commented on packages/components/src/components/avatar/style.scss
> +		font-size: 2.7706vi;
> 2.5rem lösst nicht das Problem, höchstens ein fester Wert, also z.b 40px

Fände ich hier korrekt, weil wir uns ja auch auf eine fixe Größe (`100px`) beziehen.

2024-08-27 07:28 UTC, deleonio requested changes

2024-08-27 07:28 UTC, deleonio commented on packages/components/src/components/avatar/style.scss
> +		font-size: 2.7706vi;
Ich habe `2.5rem` natürlich vorher ausprobiert und `2.5rem` entsprechen bei `16px` Basis-Font-Size genau `40px`. Bitte `40px` einstellen, da dies das homogenere Maß für `100px` ist.

2024-08-27 08:38 UTC, deleonio approved these changes

2024-08-27 10:55 UTC, sdvg approved these changes

2024-08-27 10:55 UTC, merged