alert: typo in the alternative text of the close button
public-ui/kolibri pull request #6745
Opened 2024-08-26 08:34 UTC by Makko74

Refs: #6632

2024-08-26 09:12 UTC, deleonio requested changes

2024-08-26 09:12 UTC, deleonio commented on packages/components/src/components/alert/component.tsx
> +							_label={translate('kol-close-alert', { placeholders: { label: trimmedLabelforTranslation } })}
Folgende Zeile Code, hätte m.E. gereicht, nicht? - `this.state._label?.trim() || ''`

2024-08-26 10:59 UTC, Makko74 commented on packages/components/src/components/alert/component.tsx
> +							_label={translate('kol-close-alert', { placeholders: { label: trimmedLabelforTranslation } })}
nein, ich hab das translation template angepasst und das leerzeichen vor dem {{}label} entfernt und setzte es hier wieder, sobald ein Text da ist. So vermeide ich auf einfachen Weg das doppelte Leerzeichen

2024-08-27 07:18 UTC, deleonio requested changes

2024-08-27 07:18 UTC, deleonio commented on packages/components/src/components/alert/component.tsx
> +							_label={translate('kol-close-alert', { placeholders: { label: trimmedLabelforTranslation } })}
Ja, es ist korrekt, dass bei der einfachen Variante ohne Label 2 Leerzeichen sind. Das wird im Browser aber immer als 1 Leerzeichen dargestellt und stellt somit kein Problem dar. Daher bitte einfach nur die Zeile 101 anpassen und den Rest verwerfen.

2024-08-27 08:37 UTC, deleonio approved these changes

2024-08-27 13:24 UTC, laske185 approved these changes

2024-08-27 13:24 UTC, merged