docs: update snapshot workflow doc
public-ui/kolibri pull request #6751
Opened 2024-08-27 07:16 UTC by deleonio

Refs: #6341

2024-08-27 07:21 UTC, sdvg requested changes

2024-08-27 07:21 UTC, sdvg commented on CONTRIBUTING.md
Ich kann die Zeilen nicht direkt kommentieren. Die CLI-Aufrufe müssten noch wie folgt angepasst werden:

```
gh workflow run update-snapshots.yml -r `git rev-parse --abbrev-ref HEAD`
gh workflow run update-snapshots.yml -r `git rev-parse --abbrev-ref HEAD` -f purge_snapshots=true
```

2024-08-28 05:50 UTC, laske185 approved these changes

2024-08-28 05:57 UTC, laske185 requested changes

2024-08-28 05:57 UTC, laske185 commented on CONTRIBUTING.md
Oder `-r $YOUR_BRANCH`, wenn man nicht den aktuell ausgecheckten Branch nehmen will oder gar nicht mit der CLI im Git-Verzeichnis ist.

2024-08-28 06:10 UTC, deleonio commented on CONTRIBUTING.md
@laske185 Kannst Du die Anpassung bitte vornehmen. Ich habe mit `gh` noch nicht gearbeitet. Danke.

2024-08-29 07:09 UTC, sdvg approved these changes

2024-08-30 06:02 UTC, laske185 approved these changes

2024-08-30 06:02 UTC, laske185 commented on CONTRIBUTING.md
@deleonio Erledigt

2024-09-02 06:08 UTC, merged