switch option label entweder links oder rechts
public-ui/kolibri pull request #6754
Opened 2024-08-27 13:03 UTC by Makko74

ref #6083

2024-09-03 12:49 UTC, sdvg commented
@Makko74 Hier müsste der PR-Titel bitte noch angepasst werden (für den Changelog).

2024-09-03 12:52 UTC, sdvg commented on packages/samples/react/src/components/input-checkbox/basic-label-align.tsx
Wollen wir diese Variante nicht vielleicht einfach in die bestehenden Samples integrieren? Drei neue Routen nehmen hier m.M.n. etwas viel Raum ein. Auch die `hideLabel`-Variante in den "align"-Beispielen noch mal zu zeigen, finde ich zu viel.

Ich könnte mir gut vorstellen, dass wir pro Checkbox-Variante einfach die Align-Varianten "links, "rechts" und "ohne" (hide) zeigen.

2024-09-03 12:53 UTC, sdvg commented on packages/themes/bmf/src/components/input-checkbox.scss
> +		&.default[data-label-align='left']:not(.hide-label) {
@deleonio Wie gehen wir hier mit den data-Attributen für den Moment um? Ändern zu BEM?

2024-09-04 20:56 UTC, Makko74 commented on packages/samples/react/src/components/input-checkbox/basic-label-align.tsx
durch die hideLabel Varianten die Render Bugs gefunden und gefixt.

Für mich ist es halt pro Variante eine neue Story. hideLabel wird anders dargestellt. Im Grunde ohne Alignment. Allerdings muss geprüft werden das jeweils bei gesetzten alignment zu links und rechts richtig dargestellt wird.

2024-09-06 03:40 UTC, deleonio requested changes

2024-09-06 03:40 UTC, deleonio commented on packages/components/src/components/input-checkbox/shadow.tsx
> +	@Prop() public _labelAlign?: LabelAlignPropType;
default wert noch setzen

2024-09-06 03:40 UTC, deleonio commented on packages/themes/bmf/src/components/input-checkbox.scss
> +		&.default[data-label-align='left']:not(.hide-label) {
@sdvg, @Makko74, @laske185 lasst uns das bitte auch noch einmal zusammen entscheiden. Aktuell vermeiden wir diese Form des Stylings.

2024-09-06 03:40 UTC, deleonio commented on packages/components/src/components/input-checkbox/shadow.tsx
> +	@Prop() public _labelAlign?: LabelAlignPropType;
?

2024-09-06 03:40 UTC, deleonio commented on packages/samples/react/src/components/input-checkbox/basic-label-align.tsx
Bitte in einer Story umsetzen und einfach dann 4 Boxen.

- Links oben: left mit label
- Rechts oben: left ohne label
- Links unten: right mit label
- Rechts unten: right ohne label

> Ja, ohne label wird erwartungsgemäß gleich aussehen

2024-09-06 12:00 UTC, deleonio requested changes

2024-09-06 12:00 UTC, deleonio commented on packages/themes/bmf/src/components/input-checkbox.scss
> +		&.default[data-label-align='left']:not(.hide-label) {
Wir lassen das jetzt so und sprechen zu BEM demnächst.

2024-09-10 09:00 UTC, sdvg requested changes

2024-09-10 09:00 UTC, sdvg commented on packages/tools/visual-tests/tests/sample-app.routes.js
> +ROUTES.set('input-checkbox/switch-label-align', null);
Diese Routen gibt es nicht mehr.

2024-09-10 09:00 UTC, sdvg commented on packages/samples/react/src/components/input-checkbox/partials/variants.tsx
> +					<legend>Label algin &quot;left&quot; with label</legend>
```suggestion
					<legend>Label align &quot;left&quot; with label</legend>
```

2024-09-10 09:00 UTC, sdvg commented on packages/samples/react/src/components/input-checkbox/partials/variants.tsx
> +					<legend>Label algin &quot;right&quot; with label</legend>
```suggestion
					<legend>Label align &quot;right&quot; with label</legend>
```

2024-09-10 09:00 UTC, sdvg commented on packages/components/src/components/input-checkbox/shadow.tsx
> +					data-label-align={this.state._labelAlign?.trim() || 'right'}
Wozu brauchen wir hier ein trim? Die Eigenschaft kann doch sowieso nur die zwei Werte `left` und `right` einnehmen?

2024-09-10 09:00 UTC, sdvg commented on packages/tools/visual-tests/tests/sample-app.routes.js
> +ROUTES.set('input-checkbox/switch-label-align', null);
Die entsprechenden Snapshots sind auch leer. Snapshots bitte immer reviewen.

2024-09-10 11:54 UTC, sdvg approved these changes

2024-09-10 18:53 UTC, deleonio approved these changes

2024-09-10 18:54 UTC, merged