Update CONTRIBUTING.md
public-ui/kolibri pull request #6818
Opened 2024-09-12 15:17 UTC by AlexanderSchmidtCE

Refs: #6813

2024-09-13 08:17 UTC, deleonio requested changes

2024-09-13 08:17 UTC, deleonio commented on CONTRIBUTING.md
> +12. To watch for changes navigate to `samples/react/` an run `pnpm serve`
Bitte Punkt 12 überarbeiten, Punkt 13 würde entfallen 

- execute in an other console ...
- pnpm start
- it will be open http://loc... automatically

2024-09-16 07:13 UTC, AlexanderSchmidtCE commented on CONTRIBUTING.md
> +12. To watch for changes navigate to `samples/react/` an run `pnpm serve`
Hab es angepasst

2024-09-16 10:32 UTC, deleonio approved these changes

2024-09-16 10:32 UTC, merged