Marked Indented Text as deprecaten and removed from other components
public-ui/kolibri pull request #6829
Opened 2024-09-16 06:49 UTC by AlexanderSchmidtCE

Refs:#6768

2024-09-16 10:30 UTC, deleonio requested changes

2024-09-16 10:30 UTC, deleonio commented on packages/components/src/components/details/shadow.tsx
> +						<div class="kol-indented-text">
Könnten wir hier auch auf einen `div` optimieren?

2024-09-16 15:18 UTC, AlexanderSchmidtCE commented on packages/components/src/components/details/shadow.tsx
> +						<div class="kol-indented-text">
ja, hab es angepasst.

2024-09-17 07:20 UTC, sdvg requested changes

2024-09-17 07:20 UTC, sdvg commented on packages/components/src/components/details/shadow.tsx
> +						class="content kol-indented-text"
Hier würde ich gerne noch den Klassennamen `kol-indented-text` entfernen (refactoren), da er sich auf eine nicht mehr existierende Komponente bezieht.

2024-09-17 07:20 UTC, sdvg commented on packages/components/src/components/indented-text/component.tsx
> + * @deprecated This component has been deprecated as it ist just styling.
Vorschlag:

```suggestion
 * @deprecated Will be removed in v3. Replace with custom HTML and styling.
```
Ich beziehe mich hier auf die bestehende Konvention "Will be removed in v3." und die Beschreibung aus dem Ticket.

2024-09-17 07:20 UTC, sdvg commented on packages/components/src/components/details/shadow.tsx
> +						class="content kol-indented-text"
Der selbe Kommentar trifft z.B. auf die Form-Komponente und ggf. weitere Stellen zu.

Wir können hier einen Mixin verwenden. Es sollte aber (z.B. in zukünftigen Themes) auch problemlos möglich sein, die "indented texts"  in verschiedenen Komponenten unabhängig voneinander zu stylen. Daher würde ich auch lokale Klassennamen verwenden. In Form also z.B. `mandatory-fields-hint`, nicht `indented-text`.

2024-09-17 07:20 UTC, sdvg commented on packages/samples/react/src/components/SampleDescription.tsx
> +				<div className="kol-indented-text">{props.children}</div>
Brauchen wir das zusätzliche div? Bitte auch hier den Kommentar zum Klassennamen beachten.

2024-09-17 07:20 UTC, sdvg commented on packages/samples/react/src/style.scss
> +.kol-indented-text{
Bitte einmal schauen, ob alle diese Styles wirklich gebraucht werden. Inbesondere `border-left` und `width` sind mir ins Auge gesprungen.

2024-09-17 07:20 UTC, sdvg commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-details-basic-firefox-linux.png
Hier haben wir augenscheinlich den Container um ein paar Pixel verkleinert. Falls nicht zu umständlich, würde ich es so anpassen, dass die Styles identisch zu vorher sind.

2024-09-18 11:46 UTC, AlexanderSchmidtCE commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-details-basic-firefox-linux.png
Ich habe versucht die Größe anzupassen, aber keine gute Möglichkeit gefunden.

2024-09-18 12:38 UTC, sdvg requested changes

2024-09-18 12:38 UTC, sdvg commented on packages/components/src/components/details/shadow.tsx
> +					<div aria-hidden={this.state._open === false ? 'true' : undefined} class="content indented-text" ref={(element) => (this.contentElement = element)}>
Brauchen wir hier beide Klassennamen, `content` und `indented-text`?

2024-09-18 12:38 UTC, sdvg commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-indented-text-basic-firefox-linux.png
Hier scheinen wir einen Bug zu haben - das Styling für kol-indented-text fehlt

2024-09-18 12:38 UTC, sdvg commented on packages/themes/bmf/src/components/indented-text.scss
> +	@include indented-text;
Das scheint mir nicht zu funktionieren. Der mixin beinhaltet nur die Styles ohne Selektor, wir haben hier also Properties ohne Selektor.

2024-09-18 12:38 UTC, sdvg commented on packages/themes/bmf/src/mixins/indented-text.scss
> +	border-left: none;
Kurze Frage, weil ich es gerade nicht testen kann: Warum setzen wir diese Eigenschaft?

2024-09-18 13:11 UTC, AlexanderSchmidtCE commented on packages/themes/bmf/src/components/indented-text.scss
> +	@include indented-text;
Hab jetzt auch die IndentedText Samples angepasst. sollten jetzt alle styles haben

2024-09-18 14:53 UTC, AlexanderSchmidtCE commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-indented-text-basic-firefox-linux.png
Ist jetzt enthalten

2024-09-18 14:54 UTC, AlexanderSchmidtCE commented on packages/themes/bmf/src/mixins/indented-text.scss
> +	border-left: none;
Kann ich nicht sagen. Die Eigenschaften waren so schon drin, aber haben keinen Nutzen. Ich hab sie entfernt

2024-09-18 16:55 UTC, sdvg commented on packages/themes/bmf/src/mixins/indented-text.scss
> +	border-left: none;
Danke fürs nachschauen!

2024-09-18 16:57 UTC, sdvg commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-combobox-basic-firefox-linux.png
Diese Änderung in der Schriftgröße müssten wir noch korrigieren.

2024-09-19 00:39 UTC, deleonio requested changes

2024-09-19 00:39 UTC, deleonio commented on packages/components/src/components/details/shadow.tsx
❤️

2024-09-19 00:39 UTC, deleonio commented on packages/components/src/components/indented-text/component.tsx
> +/**
Achtung: Bitte nicht die `shadow.tsx` vergessen. Alle Komponenten haben eine Shadow- und Nicht-Shadow-Komponent (`component.tsx`, `shadow.tsx`).

2024-09-19 00:39 UTC, deleonio commented on packages/samples/react/src/style.scss
> +		box-shadow: -2px 0px 0px var(--color-primary-variant);
Bitte mal schauen, ob box-shadow gut ist. Lieber immer Border nehmen, da im Hochkontrast-Modus keine Shadows gerendert werden.

2024-09-19 00:39 UTC, deleonio commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-combobox-basic-firefox-linux.png
@sdvg im Netlifly passt die Font-Family von der Beschreibung ... nur irgendwie nicht in den Snapshots. Hast Du eine Idee, wieso?

2024-09-19 06:21 UTC, sdvg commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-combobox-basic-firefox-linux.png
@deleonio Kann ich so leider nicht bestätigen.

Wenn ich diese zwei Links öffne und direkt vergleiche, sehe ich einen deutlichen Unterschied:

https://66eadd6f7ae6541ea3cde867--kolibri-public-ui.netlify.app/#/combobox/basic
https://develop--kolibri-public-ui.netlify.app/#/combobox/basic

2024-09-19 06:37 UTC, deleonio commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-combobox-basic-firefox-linux.png
@sdvg sorry Du meinst die Mandatory Message ... ja da fehlt irgendwie die Font-Size

2024-09-19 22:50 UTC, deleonio submitted a review, later dismissed

2024-09-19 23:03 UTC, deleonio approved these changes, later dismissed

2024-09-24 09:55 UTC, deleonio approved these changes

2024-09-24 09:56 UTC, merged