Add automatic `role="alert"` handling for Inputs
public-ui/kolibri pull request #6839
Opened 2024-09-16 14:35 UTC by sdvg

2024-09-19 00:08 UTC, deleonio requested changes

2024-09-19 00:08 UTC, deleonio commented on packages/components/src/schema/props/msg.ts
> +		setState(component, '_msg', value);
Bitte hier den Validator belassen, siehe: https://github.com/public-ui/kolibri/blob/4b46a6d32031b3e320876a37d43ee3a4784d4f46/packages/components/src/schema/props/icons.ts#L71

2024-09-19 00:08 UTC, deleonio commented on packages/components/src/schema/components/textarea.ts
> -	PropMsg &
Hier würde es ggf. reichen, nur an dieser Stelle die Änderungen vorzunehmen und dafür nicht alle Schema anpassen zu müssen: https://github.com/public-ui/kolibri/blob/4b46a6d32031b3e320876a37d43ee3a4784d4f46/packages/components/src/schema/props/msg.ts#L14

2024-09-19 00:08 UTC, deleonio commented on packages/components/src/components/select/shadow.tsx
> +	@State() private inputHasFocus = false;
Wäre es auch möglich, `inputHasFocus` und `showAsAlert` im zentralen Controller umzusetzen?

s. https://github.com/public-ui/kolibri/blob/4b46a6d32031b3e320876a37d43ee3a4784d4f46/packages/components/src/components/%40deprecated/input/controller.ts#L238

2024-09-19 14:04 UTC, sdvg commented on packages/components/src/components/select/shadow.tsx
> +	@State() private inputHasFocus = false;
Ich denke nicht, weil man `@State` soweit ich weiß nur innerhalb der Komponenten so anpassen kann, dass neu gerendert wird. Vielleicht gibt es einen Weg, aber so hat es sich bei meinem Test verhalten.

2024-10-14 17:20 UTC, sdvg commented on packages/components/src/schema/components/textarea.ts
> -	PropMsg &
Wie heute morgen besprochen: Wir benötigen beide Types. Die Stringified-Variante für die äußeren Props, die normale Variante für die Props der internen Komponenten und der States.
Daher hat sich eine globale Änderung als unpraktisch erwiesen.

2024-10-15 17:14 UTC, deleonio submitted a review, later dismissed
Danke, morgen teste ich noch einmal mit Screenreader nach. 👍

2024-10-21 13:44 UTC, deleonio requested changes
Die Implementierung ist im Grund so, wie gewünscht.

Ich habe festgestellt, dass beim `blur` die Rolle `alert` gesetzt wird. Der NVDA liest aber dann trotzdem den Fehler des verlassenen Feldes nicht vor, da er mit dem Vorlesen des neuen Feldes beginnt.

Was machen wir nun?!

2024-10-28 09:15 UTC, deleonio commented
@sdvg bitte nur Konflikte lösen und dann wollen wir das mergen. Das Thema mit dem Vorlesen der Fehlermeldung gehen wir in einem neuen Ticket an.

2024-10-28 09:16 UTC, deleonio approved these changes, later dismissed

2024-10-28 14:32 UTC, merged