Bug/6842 Fix closePopup async eslint error
public-ui/kolibri pull request #6858
Opened 2024-09-20 08:50 UTC by Makko74

Refs: #6842

Async für die closePopup wurde gesetzt.

Damit der Fehler nicht mehr auftritt wurde auch die eslint rule  [@stencil-community/async-methods](https://github.com/stencil-community/stencil-eslint/blob/main/docs/async-methods.md)  aktiviert.
Alle andere Rules aus dem  @stencil-community package sind deaktivert und sind nicht Bestandteil dieses PR

2024-09-23 12:04 UTC, deleonio requested changes

2024-09-23 12:04 UTC, deleonio commented on packages/components/src/components/split-button/shadow.tsx
> +		return Promise.resolve();
Hi @Makko74, ich bin mir unsicher, ob wir das so beantworten sollen:

```
@Method()
	async focusErrorList(): Promise<void> {
		setTimeout(() => {
			if (this._errorList && this._errorList.length > 0) {
				this.errorListElement?.focus();
			}
		}, 300);
		return Promise.resolve();
	}
```

Auch diese Implementierung halte ich nicht für so günstig.

Lasst uns noch einmal genauer schauen, wie man diese Methoden implementiert.

2024-09-25 07:05 UTC, laske185 commented on packages/components/src/components/split-button/shadow.tsx
> +		return Promise.resolve();
Hierfür wurde ein neues Issue angelegt: #6872

2024-09-25 07:07 UTC, laske185 approved these changes

2024-09-25 07:08 UTC, merged