Feature/6159 Table: Spacer between body and footer
public-ui/kolibri pull request #6860
Opened 2024-09-20 10:56 UTC by Makko74

Refs: #6159

2024-09-23 12:10 UTC, deleonio requested changes

2024-09-23 12:10 UTC, deleonio commented on packages/themes/default/src/mixins/kol-table-stateless-wc.scss
Bitte sowohl Header-Spacer als auch Footer-Spacer im default-Theme umsetzen. Bisschen mehr als nur whitespace ... ggf. noch ein Border am oberen bzw. unteren Rand.

2024-09-26 21:23 UTC, deleonio commented
@Makko74 wie geht es hier weiter?

2024-10-07 11:33 UTC, laske185 commented on packages/themes/default/src/mixins/kol-table-stateless-wc.scss
Eine weitere Linie wird nicht benötigt. Zwischen Body und Footer ist nun etwas Platz. Bei weiteren Styling-Ideen machen wir ein neues Ticket auf.

2024-10-07 11:33 UTC, merged