KolButton with delegatesFocus
public-ui/kolibri pull request #6921
Opened 2024-10-10 07:24 UTC by Makko74

Refs: #6869

2024-10-11 12:30 UTC, sdvg requested changes
Ich denke wir sollten `delegatesFocus` nicht grundsätzlich überall setzen, sondern nur dort wo es wirklich gebraucht wird und getestet wurde.

Bei manchen Komponenten kann es ungewollte Nebeneffekte haben. Beispiel: https://670823c73725da559decc8b2--kolibri-public-ui.netlify.app/#/alert/basic

Wenn man hier auf den Text der Alert-Meldung klickt, wird der Tooltip des Schließen-Buttons aktiviert.

2024-10-15 09:21 UTC, sdvg commented
Ich finde hier leider noch mehr Nebeneffekte, von denen ich nicht sicher bin, ob sie akzeptabel sind.

Beispiel: Bei KolInputRadio kann jetzt auch die deaktivierte Option angeklickt werden und setzt den Fokus auf die erste Option:

![screenshot 2024-10-15-11 17 57@2x](https://github.com/user-attachments/assets/3dbf4a5b-d14c-4a0c-a395-efc32d1bff84)

@AlexanderSchmidtCE Könntest du das Thema bitte morgen einmal im Daily ansprechen?

2024-10-15 16:59 UTC, deleonio commented
> Ich denke wir sollten `delegatesFocus` nicht grundsätzlich überall setzen, sondern nur dort wo es wirklich gebraucht wird und getestet wurde.
> 
> Bei manchen Komponenten kann es ungewollte Nebeneffekte haben. Beispiel: https://670823c73725da559decc8b2--kolibri-public-ui.netlify.app/#/alert/basic
> 
> Wenn man hier auf den Text der Alert-Meldung klickt, wird der Tooltip des Schließen-Buttons aktiviert.

Aktuell sehe ich nur noch Komponenten, wo das Fokussieren relevant und passend wäre.

2024-10-15 17:02 UTC, deleonio requested changes

2024-10-15 17:02 UTC, deleonio commented on packages/samples/react/src/components/button/tabindex.tsx
Das Beispiel bitte zu einem Szenario umändern und alle geänderten Komponenten in das Beispiel aufnehmen. Die Tab-Reihenfolge ist dann einfach rückwärts. Vom Letzten zum ersten Element.

2024-10-25 12:20 UTC, deleonio approved these changes

2024-10-25 14:09 UTC, sdvg approved these changes

2024-10-25 14:10 UTC, merged