Refactoring change component snapshot tests (1/4)
public-ui/kolibri pull request #7024
Opened 2024-11-06 18:30 UTC by Makko74

ref #6963 

Die Tests für die Input Controls werden in einem separaten Branch überarbeitet

The A11y and PO reviews will only take place after all other DoD steps have been completed by the Developer:
- [x] Maturation completed and documented
- [x] Meaningful pull request title for the release notes
- [x] Pull request is linked to an issue
- [x] All changes relate to the issue
- [x] No TODOs or commented out code in the final commit
- [x] Tests to protect this code implemented (if applicable)
- [x] Manual test performed successfully (if applicable)
- [x] Documentation or migration has been updated (if applicable)

2024-11-07 08:40 UTC, sdvg requested changes
Finde die Test-Cases überwiegend gut, danke fürs Einpflegen.

Ich würde gern noch besprechen, wie wir zukünftig mit Property-Kombinationen umgehen wollen. Früher haben wir automatisch alle möglichen Kombinationen getestet, das hat aber auch zu sehr langen Laufzeiten der Tests geführt.
Jetzt haben wir auch generierte Kombination, wie z.B. bei input-email, wo knapp 12k Test herauskommen. Solche Stellen würde ich gerne zukünftig noch optimieren.

2024-11-07 08:40 UTC, sdvg commented on packages/components/tsconfig.json
Die Aliases würde ich jetzt nicht einfach so nebenher einführen wollen.
Wir wollten die zunächst evaluieren, dafür gibt es auch ein Ticket: https://github.com/public-ui/kolibri/issues/6985

2024-11-07 08:40 UTC, sdvg commented on packages/components/src/components/accordion/test/snapshot.spec.tsx
> +// _open: [true, false],
Auskommentierten Code bitte entfernen

2024-11-07 08:40 UTC, sdvg commented on packages/components/src/components/form/test/snapshot.spec.tsx
Ich bin nicht sicher, ob es aus dieser Datei kommt, sehe beim Ausführen der Tests aber folgenden Fehler:

```
 PASS  src/components/form/test/snapshot.spec.tsx
/[...]/kolibri/node_modules/.pnpm/@stencil+core@4.20.0/node_modules/@stencil/core/internal/testing/index.js:2076
var getValue = (ref, propName) => getHostRef(ref).$instanceValues$.get(propName);
                                                 ^

TypeError: Cannot read properties of undefined (reading '$instanceValues$')
    at getValue (/[...]/kolibri/node_modules/.pnpm/@stencil+core@4.20.0/node_modules/@stencil/core/internal/testing/index.js:2076:50)
    at KolAlertWc.get [as state] (/[...]/kolibri/node_modules/.pnpm/@stencil+core@4.20.0/node_modules/@stencil/core/internal/testing/index.js:2174:20)
    at patchState (/[...]/kolibri/packages/components/src/schema/utils/prop.validators.ts:75:69)
    at setState (/[...]/kolibri/packages/components/src/schema/utils/prop.validators.ts:116:5)
    at watchValidator (/[...]/kolibri/packages/components/src/schema/utils/prop.validators.ts:128:30)
    at watchBoolean (/[...]/kolibri/packages/components/src/schema/utils/prop.validators.ts:150:5)
    at KolAlertWc.validateAlert (/[...]/kolibri/packages/components/src/components/alert/component.tsx:55:35)
    at KolAlertWc.handleAlertTimeout (/[...]/kolibri/packages/components/src/components/alert/component.tsx:24:18)
    at Timeout._onTimeout (/[...]/kolibri/packages/components/src/functional-components/Alert/Alert.tsx:37:77)
    at listOnTimeout (node:internal/timers:573:17)

Node.js v20.15.0
```

2024-11-07 08:40 UTC, sdvg commented on packages/components/src/components/pagination/test/snapshot.spec.tsx
> +// _label: ['Label'],
Auskommentierten Code bitte entfernen

2024-11-07 08:40 UTC, sdvg commented on packages/components/src/components/skip-nav/test/snapshot.spec.tsx
> +				{ _href: 'www.google.de', _label: 'Zum Anfang' },
Fände gut, wenn wir zumindest für neue Test-Properties `https://example.com` (https://www.iana.org/help/example-domains) verwenden könnten.

2024-11-07 08:51 UTC, deleonio requested changes

2024-11-07 08:51 UTC, deleonio commented on packages/components/tsconfig.json
Diese Änderung bitte wieder rausnehmen.

2024-11-07 08:51 UTC, deleonio commented on packages/components/src/components/popover/test/snapshot.spec.tsx
> +executeSnapshotTests<PopoverProps>(KolPopoverWcTag, [KolPopover], [...['top', 'right', 'bottom', 'left'].map((_align) => ({ _align }) as PopoverProps)]);
Wirkt unleserlich. Bitte für Test immer einfach und klar hinschreiben. Im Zweifel redundant.

2024-11-07 08:51 UTC, deleonio commented on packages/components/src/components/alert/test/snapshot.spec.tsx
> +function buildByType(_type: 'default' | 'error' | 'info' | 'success' | 'warning') {
hier auch bitte einfach und leserlich schreiben, keinen builder bitte

2024-11-08 00:20 UTC, Makko74 commented on packages/components/src/components/form/test/snapshot.spec.tsx
keine Ahnung, tritt auch jedesmal bei einer anderen Datei auf. useFakeTimer hat auch nichts gebracht.

2024-11-08 08:27 UTC, sdvg requested changes

2024-11-08 08:27 UTC, sdvg commented on packages/components/src/utils/testing/snapshot-testing.tsx
> +		jest.spyOn(global, 'setTimeout');
fakeTimers kann ich nachvollziehen, scheint in diesem Kontext notwendig zu sein.

Das spyOn hat keinen Effekt, soweit ich es reproduzieren kann. Würde ich gerne entfernen.

2024-11-08 08:27 UTC, sdvg commented on packages/components/src/components/progress/test/snapshot.spec.tsx
> +	beforeAll(() => {});
Kann das nicht ganz raus?
Vermutlich können wir hier auch mal auf Snapshots umstellen, muss aber nicht in diesem PR passieren. Ist wohl ein Spezialfall.

2024-11-08 09:02 UTC, sdvg approved these changes

2024-11-08 10:32 UTC, deleonio approved these changes

2024-11-08 10:33 UTC, merged