Refactoring/6960 span component
public-ui/kolibri pull request #7027
Opened 2024-11-06 20:28 UTC by Makko74

ref #6960

2024-11-12 10:37 UTC, sdvg requested changes
Gefällt mir sehr gut 👍 
Habe nur ein paar ganz kleine Anmerkungen.

2024-11-12 10:37 UTC, sdvg commented on packages/components/src/functional-components/Span/Span.tsx
> +	let TopIconProps: IconType = null;
Das Refactoring gefällt mir. Die Variablennamen müssten m.E. noch kleingeschrieben werden.

2024-11-12 10:37 UTC, sdvg commented on packages/components/src/schema/components/badge.ts
>  } & PropIcons;
`icons` ist hier jetzt doppelt

2024-11-12 10:37 UTC, sdvg commented on packages/components/src/components/heading/shadow.tsx
> +	 * Setzt den Text einer weiteren Überschrift, einen Level kleiner, unter der Ersten.
Kommentare bitte auf Englisch

2024-11-12 12:53 UTC, Makko74 commented on packages/components/src/functional-components/Span/Span.tsx
> +	let TopIconProps: IconType = null;
gleiche Art, wie bei den Sub Props  in den Component Props Types

2024-11-12 12:54 UTC, Makko74 commented on packages/components/src/schema/components/badge.ts
>  } & PropIcons;
Musste ich hinzufügen, damit ich die icons aus dem State nehmen konnte und damit als objekt und nicht als string habe, damit ich es an den FC übergeben konnte

2024-11-12 13:05 UTC, Makko74 commented on packages/components/src/functional-components/Span/Span.tsx
> +	let TopIconProps: IconType = null;
aber geändert

2024-11-12 13:05 UTC, Makko74 commented on packages/components/src/components/heading/shadow.tsx
> +	 * Setzt den Text einer weiteren Überschrift, einen Level kleiner, unter der Ersten.
war nicht von mir

2024-11-13 15:36 UTC, sdvg approved these changes

2024-11-13 15:37 UTC, merged