Fix table column consistency
public-ui/kolibri pull request #7047
Opened 2024-11-08 10:47 UTC by anicyne

Refs: #6890

2024-11-14 10:29 UTC, deleonio commented
Hi @sdvg, @AlexanderSchmidtCE ,

irgendwie ist der Snapshot jetzt anders ... die Tabelle ist nicht mehr leer?

Wurde das Sample gefixed oder die Component?

2024-11-14 10:39 UTC, sdvg commented
> irgendwie ist der Snapshot jetzt anders ... die Tabelle ist nicht mehr leer?

Hier ist ein kleiner Abstand entstanden. Das sollte noch behoben werden.

![screenshot 2024-11-14-11 35 53@2x](https://github.com/user-attachments/assets/f736eb26-c02c-440e-96ec-7fc6164717bd)

> Wurde das Sample gefixed oder die Component?

Es wurde direkt in der Tabelle gefixt. Reviewed ist die Änderung noch nicht.

> Müsste das nicht [public-ui.github.io/v2/sample-react#/table/stateless](https://public-ui.github.io/v2/sample-react/#/table/stateless) fixen?

Um dieses Beispiel geht es im Ticket, ja. Da wurden jetzt leere Zellen eingefügt, wo vorher keine waren.

2024-11-20 13:51 UTC, deleonio commented
@sdvg ist das eher so, wie Du wolltest?

2024-11-20 17:09 UTC, sdvg commented
> @sdvg ist das eher so, wie Du wolltest?

Noch nicht so ganz:

Im Beispiel sind weiterhin die Spalten verschoben.
![screenshot 2024-11-20-18 02 20@2x](https://github.com/user-attachments/assets/5232e51d-7155-4186-a6ce-c90faa55b6c3)

Das ließe sich lösen, indem wir eine leere Headerspalte als Platzhalter für die vertikalen Header hinzufügen.
Dies würde wie folgt aussehen:

```diff
_headerCells={{
	horizontal: [
		[
+			{ label: '', asTd: true },
			{ key: 'left', label: 'left', textAlign: 'left', sortDirection: 'ASC' },
			{ key: 'center', label: 'center', textAlign: 'center', sortDirection: 'DESC' },
			{ key: 'right', label: 'right', textAlign: 'right', sortDirection: 'NOS' },
			{ key: 'nosort', label: 'no sort option' },
		],
	],
```

Wenn die Tabelle korrekt befüllt ist, ist es auch nicht mehr notwendig, Daten "abzuschneiden", die über die Header-Spalten herausragen, wie gerade implementiert. Diese Logik würde ich tatsächlich lieber wieder entfernen, weil ich es im Zweifelsfall besser fände, wenn Daten und Header nicht ganz zusammenpassen, als wenn Daten entfernt werden.

Für mich wäre eine solche Fehlerbehebung direkt im Beispiel ausreichend. Wenn wir zusätzlich Probleme in der Tabelle selbst abfangen wollen, würde ich gerne noch einmal über die Details sprechen (@deleonio).

2024-11-21 15:12 UTC, sdvg commented on packages/components/src/components/table-stateless/component.tsx
> +		}
Im Beispielfall siehts zunächst mal gut aus! Auch den Check von `label !== ''` finde ich sinnvoll, wenn wir so einen Breaking Change vermeiden.

Wie verhält es sich, wenn wir mehrere Header-Zeilen haben? Müssten wir dann noch colSpan bzw. rowSpan entsprechend erhöhen?
`colspan="1"` bzw. `rowspan="1"` entsprechen den Default-Werten uns sind in der Form redundant.

Eigentlich fände ich Tests hier sehr sinnvoll, um die Logik abzusichern. Ungünstig ist, dass wir hier noch gar keine Tests vorbereitet haben. Jest-Snapshots sollten aber schnell umsetzbar sein.

@deleonio Zwei Fragen in deine Richtung:

1) Siehst du hier das Risiko eines Breaking Change? Ich hoffe, dass wir ihn wie oben erwähnt durch den Check auf `label !== ''` vermeiden, bin mir aber nicht ganz sicher.
2) Sollen wir hier noch Zeit in Test stecken, oder machen wir das lieber später?

2024-11-21 16:06 UTC, deleonio commented on packages/components/src/components/table-stateless/component.tsx
> +		}
Wir machen hier definitiv zwei Beispieletests mit Jest, die sollten das covern.

Den Punkt mit dem label, muss ich nachdenken.

2024-11-23 09:37 UTC, deleonio requested changes
@sdvg Ich glaube, hier ist aus Versehen ein Fehler passiert.

2024-11-23 10:31 UTC, sdvg commented
> @sdvg Ich glaube, hier ist aus Versehen ein Fehler passiert. `v3`stuff containt

Danke für den Hinweis. Da war ich gestern noch auf dem falschen Branch unterwegs. Ist korrigiert.

2024-11-23 11:24 UTC, deleonio requested changes
@anicyne, @sdvg ich habe einen Test ergänzt und wenn der grün wird, dann sollte der Algorithmus passen.

2024-11-23 11:24 UTC, deleonio commented on packages/components/src/components/table-stateless/component.tsx
> +			headers.horizontal[0][0]?.label !== ''
Die Label-Prüfung muss raus. Um die leer Zelle muss sich nicht von Außen gekümmert werden und das war auch anfangs nicht so.

2024-11-23 18:08 UTC, anicyne commented on packages/components/src/components/table-stateless/component.tsx
> +		}
Wenn die Label-Prüfung entfernt wird zwei Elemente generiert. Diese Verhalten tritt auf, wenn man die Seite wechselt und anschließend zur Tabelle Seite zurückkehrt. 
![image](https://github.com/user-attachments/assets/83146005-a25d-4854-b6b7-84d8f455490e)

2024-11-23 23:32 UTC, deleonio commented on packages/components/src/components/table-stateless/component.tsx
> +		}
Vielen Dank @anicyne für den Hinweis.

Das Verhalten ist dadurch aufgetreten, weil wir die leere TD-Header-Cell in die originalen Header-Daten eingefügt haben - per Referenz. Wir dürfen diese nicht manipulieren. Sondern fangen das einfach in der Render-Funktion ab und fügen, wenn ja, eine `<td colspan rowspan></td>` einmalig ein. Now it works.

Ein 2. Fehler war in den Spacer - hier hat beim colSpan noch die Vertical-Header-Length gefehlt.

LG

2024-11-23 23:32 UTC, deleonio submitted a review, later dismissed
Ich gebe mal ok, für meins und das was ich von Euch gereviewt habe ;-)

2024-11-25 11:32 UTC, deleonio commented
Der PR ist noch nicht fertig, weil er noch die Selection-Col berücksichtigen muss. Das sieht man jetzt schön, wenn die Linie von den spacer-TR gezeichnet wird.

2024-11-25 15:26 UTC, sdvg requested changes
@deleonio Die Lösung ist nachvollziehbar und sieht für mich gut aus. Die neuen Unit-Tests finde ich super, die sollten auf jeden Fall helfen, die Render-Logik zu stabilisieren.

Ich habe ein paar Kleinigkeiten kommentiert, die mir unterwegs aufgefallen sind.

2024-11-25 15:26 UTC, sdvg commented on packages/samples/react/src/components/table/column-alignment.tsx
> -							{ label: '', asTd: true },
@deleonio Ich möchte nur noch einmal darauf eingehen, danach lasse ich das Thema gerne ruhen:

Bewirkt die Notwendigkeit, diese Platzhalter-Zellen zu entfernen, nicht einen Breaking Change in allen Anwendungen, die bereits komplexe Tabellen verwenden?

2024-11-25 15:26 UTC, sdvg commented on packages/components/src/schema/types/table.ts
> +	 * @deprecated It should be working without this property, too. (needs a refactoring)
Haben wir hierfür schon ein Follow-Up Ticket?
In #7015 sollten wir die Stelle vielleicht explizit ausnahmen, um den Umfang nicht zu sprengen.

2024-11-25 15:26 UTC, sdvg commented on packages/themes/default/src/mixins/kol-table-stateless-wc.scss
> +		table caption {
Ist die zusätzliche Linie bei der Caption ein bewusst gewollte Style-Änderungen für das Default Theme?

2024-11-25 15:26 UTC, sdvg commented on packages/components/src/components/table-stateless/component.tsx
> +		 */
Ist dieser Kommentar dafür gedacht, so im Code drin zu bleiben?

2024-11-25 15:26 UTC, sdvg commented on packages/components/src/components/table-stateless/component.tsx
> +											{rowIndex === 0 &&
Die Render-Methode ist ohnehin schon sehr komplex, daher würde ich vorschlagen, diese Expression analog der Spacer-Zellen in eine neue Methode auszulagern (`renderPlaceholderCell` z.B.).

2024-11-27 12:26 UTC, sdvg commented on packages/components/src/schema/types/table.ts
> +	 * @deprecated It should be working without this property, too. (needs a refactoring)
https://github.com/public-ui/kolibri/issues/7118

2024-11-27 13:10 UTC, deleonio commented on packages/samples/react/src/components/table/column-alignment.tsx
> -							{ label: '', asTd: true },
Ja, doch leider war es ursprünglich genauso umgesetzt. Es soll einfach reichen, die relevanten Infos anzugeben und keine asTd zu handeln. Das Property muss m.e. komplett weg und mind. aus public API.

https://github.com/public-ui/kolibri/issues/7118

2024-11-27 13:10 UTC, deleonio commented on packages/samples/react/src/components/table/column-alignment.tsx
> -							{ label: '', asTd: true },
Wir sollten es changelog explizit erwähnen, dass das ein konzeptioneller Bug war.

2024-11-27 13:10 UTC, deleonio commented on packages/components/src/schema/types/table.ts
> +	 * @deprecated It should be working without this property, too. (needs a refactoring)
Jetzt ja 😄 https://github.com/public-ui/kolibri/issues/7118

2024-11-27 13:10 UTC, deleonio commented on packages/themes/default/src/mixins/kol-table-stateless-wc.scss
> +		table caption {
In den Screenshots war die obere Linie m teilweise da und manchmal nicht. Ich vermute, dass das mal war, mal nicht und die für die Snapshot Test zu geringe Änderung war und auch mein Sichtreview übersehen wurden.

Ich habe einheitlich durchgezogen.

2024-11-27 13:10 UTC, deleonio commented on packages/components/src/components/table-stateless/component.tsx
> +		 */
Interessant: Ich wusste garnicht, daß die Primäre Orientierung implizit erfolgt. Das Property brauchen wir eigentlich, damit ich in 2 Dimens auch horizontal (rows von links nach rechts) renden kann.

Ist ein Theme für PO Meeting

2024-11-27 13:10 UTC, deleonio commented on packages/components/src/components/table-stateless/component.tsx
> +		 */
Den TODO nehme ich wieder raus, ich habe dafür ein Ticket angelegt, um das zu besprechen. https://github.com/public-ui/kolibri/issues/7120

2024-11-27 13:10 UTC, deleonio commented on packages/components/src/components/table-stateless/component.tsx
> +											{rowIndex === 0 &&
Erledigt.

2024-11-27 13:10 UTC, deleonio commented on packages/themes/default/src/mixins/kol-table-stateless-wc.scss
> +		table caption {
Das ist im Overview Snapshot gut zu sehen.

2024-11-27 13:13 UTC, sdvg approved these changes

2024-11-27 13:13 UTC, merged