Changes CSS classes to BEM
public-ui/kolibri pull request #7063
Opened 2024-11-13 08:16 UTC by AlexanderSchmidtCE

Refs: #7036

2024-11-13 13:04 UTC, sdvg commented on packages/components/src/components/abbr/shadow.tsx
>  			<Host class="kol-abbr">
Schon besprochen, zu Dokumentationszwecken:

In Fällen wie hier können wir das `<Host>`-Element auch "ausbauen" und die Block-Klasse direkt auf dem äußeren Element (hier `<abbr>`) setzen.

2024-11-13 13:04 UTC, sdvg commented on packages/components/src/components/abbr/style.scss
>  	:host {
`:host` sollten wir vermeiden und die Styles lieber in den "Block" verschieben

2024-11-14 08:08 UTC, sdvg commented on packages/components/src/components/abbr/shadow.tsx
> +			<Host>
Leeres `<Host>` kann raus

2024-11-19 11:15 UTC, sdvg requested changes

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/components/@shared/_kol-alert-mixin.scss
> +				div {
Tagname-Selektoren sollten mit BEM nicht notwendig sein. Bitte eine eigene Klasse verwenden.

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/components/badge/shadow.tsx
> +					'smart-button': typeof this.state._smartButton === 'object' && this.state._smartButton !== null,
Ist ein Modifier, oder? `kol-badge--has-smart-button`?

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/components/badge/style.scss
> +		.kol-button-wc {
Ist ein _Element_, bitte neuen Klassennamen verwenden

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/components/badge/style.scss
> +			button {
```suggestion
			.button {
```
(Aktueller Klassenname, vielleicht bietet es sich an, solche viel genutzten Komponenten möglichst früh zu refactoren, damit wir nicht später wieder alles anfassen müssen.)

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/components/breadcrumb/style.scss
> +		li,
Klassen verwenden

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/components/breadcrumb/style.scss
> +		.kol-icon::part(separator) {
Hier zur eindeutigen Identifizierung bitte auch eine neue Element-Klasse auf dem Element KolIconTag

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/components/button-group/component.tsx
button-group fliegt in V3 raus. Änderungen hier bitte reverten, damit wir uns (auch später in den internen Themes) keine unnötige Arbeit machen.

2024-11-19 11:15 UTC, sdvg commented on packages/components/src/functional-components/Alert/Alert.tsx
> +		class: clsx('kol-alert', 'alert', type, variant, { hasCloser: !!hasCloser }, classNames),
Hier bitte BEM beachten. `alert` ist redundant, `type` und `variant` und `hasCloser` scheinen nicht als Modifier ausgezeichnet zu sein.

2024-11-19 11:15 UTC, sdvg commented on packages/themes/bmf/src/components/badge.scss
> +		.kol-icon {
Element-Klassen verwenden

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/@shared/input-core.scss
> +		.kol-alert {
Das hier sind ja praktisch die Styles zur Komponente kol-input.

Ich würde daher `.kol-input` als den Block definieren, und Elemente wie dieses als _Element_ (`.kol-input__alert`). Funktioniert das?

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/components/badge.scss
> +			> span {
```suggestion
			.kol-span-wc {
```

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/components/breadcrumb.scss
> +			&:has(:is(.kol-breadcrumb__icon + .kol-breadcrumb__link, .kol-breadcrumb__icon + .kol-breadcrumb__list-element-span)) {
Kommt es nur mir so vor, oder könnten wir diesen ganzen Selektor wegoptimieren? 😇
Ich kann keinen Unterschied feststellen, aber lasst uns das gerne über die Snapshot-Tests validieren.

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/components/breadcrumb.scss
> +			&:last-child {
Auch das können wir wohl optimieren, es gibt nur einen `element-span` pro Breadcrumbs.

Ein sprechenderer Klassenname könnte hier auch `__current-page` oder dergleichen sein.

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/components/breadcrumb.scss
Ich hatte mit der Komponente ein wenig experimentiert und konnte sie am Ende wie folgt runteroptimieren:

```
@layer kol-theme-component {
	.kol-breadcrumb {
		font-family: var(--font-family);

		&__list-element-span {
			color: var(--color-subtle);
		}

		&__link {
			&::part(icon) {
				font-size: rem(20);
			}
		}

		&__icon {
			font-size: rem(12);
			color: var(--color-subtle);
		}
	}
}
```

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/components/input-checkbox.scss
Die Inputs sind noch nicht Teil, dieses PRs, richtig? Hier geht es nur um die Anpassung für alert?

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/mixins/alert-wc.scss
> +		&__close-button.close {
Wozu das `.close`?

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/mixins/alert-wc.scss
> +		&.kol-alert--error {
Hier bitte auf Nesting setzen, sonst haben wir zwei kombinierte Klassen-Selektoren statt einem

2024-11-20 17:54 UTC, sdvg commented on packages/themes/default/src/@shared/input-core.scss
> +		.kol-alert {
Kann auch später passieren, wenn Input noch gar nicht Teil dieses PR ist.

Eine Aufteilung der Liste im Ticket wäre super, damit man schneller sehen kann, welche Komponenten in welchem PR behandelt werden.

2024-11-21 07:28 UTC, AlexanderSchmidtCE commented on packages/themes/default/src/@shared/input-core.scss
> +		.kol-alert {
Input wird in einem anderen PR gemacht. Eine Auflistung, was in dem PR vorkommt, ist eine gute Idee. Ich würde das dann in den ersten Post des PRs packen.

2024-11-21 08:05 UTC, AlexanderSchmidtCE commented on packages/themes/default/src/mixins/alert-wc.scss
> +		&__close-button.close {
hab das anscheinend übersehen. kann raus

2024-11-21 14:25 UTC, sdvg commented on packages/themes/default/src/components/input-radio.scss
> +	.kol-alert.error {
```suggestion
	.kol-alert {
```

2024-11-21 14:25 UTC, sdvg commented on packages/themes/default/src/components/input-radio.scss
> +		.kol-alert.error {
```suggestion
		.kol-alert {
```

2024-11-21 14:25 UTC, sdvg commented on packages/themes/default/src/mixins/input-error.scss
> +	.kol-alert.error {
```suggestion
	.kol-alert {
```

2024-11-25 09:39 UTC, sdvg requested changes

2024-11-25 09:39 UTC, sdvg commented on packages/themes/itzbund/src/@shared/kol-alert-wc.scss
> +		.kol-alert__heading {
```suggestion
		&__heading {
```

2024-11-25 09:39 UTC, sdvg commented on packages/themes/itzbund/src/components/badge.scss
> +			span {
Hier bitte noch einen BEM-Selektor verwenden

2024-11-25 09:39 UTC, sdvg commented on pnpm-lock.yaml
`git restore --source origin/develop -- pnpm-lock.yaml`
sollte hier helfen :)

2024-11-25 12:51 UTC, sdvg approved these changes

2024-11-25 12:58 UTC, merged