Changes CSS classes to BEM 2
public-ui/kolibri pull request #7083
Opened 2024-11-18 16:53 UTC by AlexanderSchmidtCE

2024-11-18 18:02 UTC, deleonio requested changes
Achtung @AlexanderSchmidtCE (@sdvg ) der `develop` und `release/2` sind m.E. nicht mehr einheitlich. Wir können mit diesem Merge nicht "einfach" die Refectorings von `v3` in `v2` mergen.

Bitte immer von `release/2` für `v2` losbranchen und arbeiten und entsprechend von `develop` für `v3`.

2024-11-18 18:06 UTC, sdvg commented
@deleonio Richtig, das Merge-Target ist falsch. Dieses PR sollte nur in `develop` (V3) gemerged werden.

Lösung: Merge Target ändern, oder wenn es (wie so oft) Probleme macht, PR schließen und neu anlegen. `v2`-Label anschließend entfernen.

2024-11-18 18:21 UTC, deleonio commented
@sdvg ich hab den Branch auf `release/2` gestellt, weil es schon einen PR für `develop` gibt.

2024-11-18 18:28 UTC, sdvg commented
@deleonio Die beiden PRs sollten verschiedene Inhalte haben bzw. sich um verschiedene Komponenten kümmern. Es sind praktisch Part 1 und Part 2.

2024-11-27 11:23 UTC, sdvg requested changes

2024-11-27 11:23 UTC, sdvg commented on packages/components/src/components/button.scss
> +		:is(.kol-button__element) {
```suggestion
		&__element {
```

2024-11-27 11:23 UTC, sdvg commented on packages/components/src/components/button.scss
> +			.kol-button__text {
Können wir aus der Verschachtelung raus nehmen und ändern zu `&__text`, oder nicht?

2024-11-27 11:23 UTC, sdvg commented on packages/components/src/components/button/component.tsx
> +			<Host>
Das Element hat keinen Nutzen mehr, soweit ich erkennen kann

2024-11-27 11:23 UTC, sdvg commented on packages/components/src/components/button/component.tsx
> +					class={clsx('kol-button__element', {
Das hier ist ein bisschen durcheinander: Eigentlich sind wir auf dem block element, haben aber Klassennamen, die sich auf Block _und_ Elelement beziehen

2024-11-27 11:23 UTC, sdvg commented on packages/components/src/components/button/component.tsx
> +						class="kol-button__text button-inner"
Kann button-inner (schon) raus oder muss das für später im Ticket notiert werden?

2024-11-27 11:23 UTC, sdvg commented on packages/components/src/components/button/shadow.tsx
> +				class={clsx('kol-button')}
Die würde ich ganz raus nehmen, da sie nicht angesprochen werden kann, wenn wir nur die interne ButtonWc Komponente wiederverwenden.

2024-11-27 11:23 UTC, sdvg commented on packages/themes/default/src/components/button-link.scss
> +		.skip {
Die Klasse kann ich nirgends finden, kann raus?

2024-11-27 11:23 UTC, sdvg commented on packages/themes/default/src/components/button-link.scss
> +	.kol-button-link {
Die Verschachtelung ist eigentlich nicht notwendig. Tatsächlich bezieht sich einfach das ganze Styling auf kol-button, nur eben im Scope des button-link Shadow DOM.

2024-11-27 11:23 UTC, sdvg commented on packages/themes/default/src/components/button.scss
> +		.kol-button__text {
```suggestion
		&__text {
```

2024-11-27 11:23 UTC, sdvg commented on packages/themes/default/src/mixins/button.scss
> +			&:active {
Hier passt noch etwas nicht: Das Span hat keine active oder disabled styles

2024-11-27 11:23 UTC, sdvg commented on packages/themes/default/src/mixins/button.scss
> +			@at-root #{$root}--ghost.small & {
Gibt es small überhaupt (noch) als Klasse? Falls ja müsste es ein BEM-Modifier werden

2024-11-27 11:23 UTC, sdvg commented on packages/themes/default/src/mixins/button.scss
> +			@at-root #{root}__element.loading & {
Loading und transparent scheint es mir als Klassen ebenfalls nicht (mehr) zu geben. Sonst Modifier.

2024-11-27 11:23 UTC, sdvg commented on packages/themes/ecl/src/ecl-ec/components/button-link.scss
> +		.kol-button {
Wie bei button würde ich auch hier die Verschachtelung weglassen.

2024-11-27 11:23 UTC, sdvg commented on packages/themes/ecl/src/ecl-ec/components/button-link.scss
> +		.skip {
Kann vermutlich raus

2024-11-27 13:56 UTC, AlexanderSchmidtCE commented on packages/components/src/components/button/component.tsx
> +			<Host>
JSX Elemente brauchen einen Parent-Element. Hätten in dem Fall neben `<button>` noch `<KolTooltipWcTag>` auf der selben Ebene. Da ergibt es Sinn mit dem `<Host>` als Parent-Element.

2024-11-27 14:38 UTC, AlexanderSchmidtCE commented on packages/components/src/components/button/component.tsx
> +						class="kol-button__text button-inner"
button-inner wird in der css pagination genutzt. sollte also erstmal bleiben

2024-11-27 14:44 UTC, AlexanderSchmidtCE commented on packages/themes/default/src/components/button-link.scss
> +		.skip {
Habe auch keine Stelle gefunden wo skip auftaucht. Ich dachte dass ich vielleicht was übersehen habe, aber wenn dir das auch nichts sagt entferne ich es

2024-11-27 14:51 UTC, AlexanderSchmidtCE commented on packages/themes/default/src/mixins/button.scss
> +			@at-root #{root}__element.loading & {
Hab auch keine Auffinden können.

2024-11-27 14:52 UTC, AlexanderSchmidtCE commented on packages/themes/default/src/mixins/button.scss
> +			@at-root #{$root}--ghost.small & {
Ich denke, der ist raus. Ich habe zumindest keine gesehen.

2024-11-28 08:10 UTC, sdvg commented on packages/components/src/components/button/component.tsx
> +			<Host>
Den Tooltip hatte ich übersehen. Dann passt es so natürlich 👍

2024-11-28 08:12 UTC, sdvg commented on packages/components/src/components/button/component.tsx
> +						class="kol-button__text button-inner"
Alles klar. Könntest du solche Punkte dann nur bitte im Ticket notieren, damit wir sie zur gegebenen Zeit erledigen? Konkret können wir die Klasse dann ja entfernen, wenn wir an Pagination arbeiten.

2024-11-28 08:40 UTC, sdvg requested changes

2024-11-28 08:40 UTC, sdvg commented on packages/components/src/components/button.scss
Wir haben hier ja jetzt ein Mixin statt "globaler Styles" - was gut ist!

Um in der Konvention mit den anderen Mixins zu bleiben, würde ich mir nur noch folgende Änderungen wünschen:
1) Verschieben nach `@shared/_kol-button-mixin.scss`
2) Ändern des Mixin-Namens nach `kol-button-styles`
3) Layer (`@layer kol-component {`) in Mixin hinzufügen
4) Layer entfernen dort wo der Mixin verwendet wird (`packages/components/src/components/button/style.scss`)

2024-12-02 07:40 UTC, AlexanderSchmidtCE commented on packages/components/src/components/button/component.tsx
> +						class="kol-button__text button-inner"
Da das Pagination Refactor durch ist, entferne ich die klasse in dem PR.

2024-12-02 12:51 UTC, AlexanderSchmidtCE commented on packages/components/src/components/button/component.tsx
> +					class={clsx('kol-button__element', {
ist jetzt angepasst

2024-12-02 14:51 UTC, sdvg requested changes

2024-12-02 14:51 UTC, sdvg commented on packages/themes/ecl/src/ecl-ec/mixins/button.scss
> +				.kol-button__text {
Könnten wir diese Styles noch nach unten, in den eigentlichen __text-Block schieben?

2024-12-02 14:51 UTC, sdvg commented on packages/themes/ecl/src/ecl-ec/mixins/button.scss
> +				.kol-button__text {
Das gleich hier, könnten wir diese Styles noch nach unten, in den eigentlichen __text-Block schieben?

2024-12-02 14:51 UTC, sdvg commented on packages/themes/ecl/src/ecl-eu/mixins/button.scss
> +		&--primary {
Könntest du hier bitte noch die Modifier vor die Elements schieben?

2024-12-02 14:51 UTC, sdvg commented on packages/themes/itzbund/src/components/button-link.scss
> +			&--primary {
Auch hier am besten noch die Modifier vor die Elements schieben

2024-12-02 14:51 UTC, sdvg commented on packages/themes/itzbund/src/components/pagination.scss
> +	.kol-button__text {
Bitte noch verschachteln (`&__text`)
(Komponente gehört zwar nicht zum PR, ist aber eine, die schon "fertig" war)

2024-12-03 10:56 UTC, sdvg approved these changes

2024-12-04 09:20 UTC, deleonio approved these changes

2024-12-04 09:32 UTC, merged