Fix ShortKey, Accesskey and Event Handler in Button Component Example
public-ui/kolibri pull request #7086
Opened 2024-11-19 11:32 UTC by Makko74

2024-11-20 08:10 UTC, deleonio requested changes

2024-11-20 08:10 UTC, deleonio commented on packages/themes/default/snapshots/theme-default/snapshot-for-button-access-key-firefox-linux.png
Hier gibt es zweimal _b_ und b --- wieso. Es gibt doch nur entweder oder?!

2024-11-20 16:21 UTC, Makko74 commented on packages/themes/default/snapshots/theme-default/snapshot-for-button-access-key-firefox-linux.png
Vorher war es zweimal s und s. 
Der Text 'Very small s' wurde zu 'Very small b'
und der accessKey wurde von 's' zu 'b'

mehr habe ich nicht verändert

2024-11-21 12:05 UTC, deleonio approved these changes

2024-11-21 12:05 UTC, merged