7102 implementierung spellcheck v2
public-ui/kolibri pull request #7109
Opened 2024-11-23 09:23 UTC by deleonio

2024-11-25 10:34 UTC, sdvg requested changes
Ein Punkt aus den Acceptance Criteria ist nicht umgesetzt:

> Standardverhalten: spellcheck="true", außer wenn explizit deaktiviert.

Ich persönlich finde die aktuelle Implementierung aber richtig, und würde Spellcheck _nicht_ als Standard einschalten.

Wir sollten also entweder die AC oder die Implementierung noch angleichen.

2024-11-25 10:34 UTC, sdvg commented on packages/components/src/schema/props/spell-check.ts
> +export const validateSpellCheck = (component: Generic.Element.Component, value?: SpellCheckPropType): void => {
Die Methode wird nicht verwendet, beide Controller rufen watchBoolean direkt auf.
Würde vorschlagen, stattdessen diese Methode zu nutzen, dann ist es einheitlich.

2024-11-25 10:34 UTC, sdvg commented on packages/components/src/schema/props/spell-check.ts
> + * Defines whether the spellcheck should be enabled.
```suggestion
 * Defines whether the browser should check the spelling and grammar.
```
Vorschlag: Selben Kommentar wie in den Komponenten verwenden.

2024-11-25 17:30 UTC, deleonio commented on packages/components/src/schema/props/spell-check.ts
> +export const validateSpellCheck = (component: Generic.Element.Component, value?: SpellCheckPropType): void => {
Das war ein Versehen.

2024-11-25 17:36 UTC, deleonio commented
Kriterien angepasst: https://github.com/public-ui/kolibri/issues/7102#issuecomment-2493574635

2024-11-26 07:49 UTC, deleonio commented on packages/components/src/schema/props/spell-check.ts
> +export const validateSpellCheck = (component: Generic.Element.Component, value?: SpellCheckPropType): void => {
Erledigt.

2024-11-26 07:50 UTC, sdvg approved these changes

2024-11-26 07:50 UTC, merged