refactor: enhance input msg validation
public-ui/kolibri pull request #7113
Opened 2024-11-24 06:50 UTC by deleonio

Refs: #6977

2024-11-25 10:12 UTC, deleonio commented
@anicyne hab jetzt auch den Test gefixed. Müsste also jetzt grün werden.

Bitte schaut Euch mal den Diff an - @sdvg ich hoffe jetzt hab ich das so, wie Du es meintest.

Wenn der gemerged ist, dann kann der quasi auch in den `release/2`.

@laske185: wir müssen mal schauen, wie und wann wir von `release/2` in `develop` mergen und wie lange das noch funktioniert.

2024-11-25 15:57 UTC, deleonio commented
Hier the Placeholder-Sample has no `_touched`: https://github.com/public-ui/kolibri/blob/0e22cf8a529f80947310c1968ea18d1648a1104b/packages/samples/react/src/components/input-text/partials/cases.tsx#L40

2024-11-25 16:49 UTC, sdvg requested changes

2024-11-25 16:49 UTC, sdvg commented on packages/samples/react/src/components/input-date/show-hide-msg.tsx
> +					<KolButton _label="Toggle Hide Msg" _type="button" _on={onHideMsg} />
Ich weiß es ist nur ein Beispiel, aber ich fände es sehr viel leichter nachzuvollziehen, wenn wir hier drei Checkboxen statt Buttons hätten. Dann wäre auf den ersten Blick klar, welche Property welchen Status hat.

Davon abgesehen finde ich das neue Beispiel sehr hilfreich!

2024-11-25 16:49 UTC, sdvg commented on packages/components/src/components/input/component.tsx
> +				{showMsg && <KolFormFieldMsgFc _alert={this._alert} _hideError={this._hideError} _msg={this._msg} _id={this._id} />}
Mit dieser Änderung zeigen wir jetzt auch Messages wie Hints und Success nur noch bei _touched_ Feldern an. Das halte ich für nicht richtig.
Siehe auch: https://github.com/public-ui/kolibri/pull/7113/files#diff-b2d7899779383d1d13f910f4c83b42350724b91ebe083c2926442cfe15d14cc3

2024-11-25 16:49 UTC, sdvg commented on packages/components/src/schema/props/msg.ts
> +				defaultValue: {
Hierüber würde ich gerne noch einmal sprechen. Ist der gleiche Kommentar, den ich in der ersten Runde schon hatte, jetzt nur an anderer Stelle:

Meines Erachtens ist ein Objekt vom Type Error kein guter Default-Wert für eine Message. Intuitiver verständlich fände ich hier `undefined`.

Wenn ich beim Debuggen `{description: '', _type: 'error'}` sehe, denke ich, dass eine Fehlermeldung existiert, die keinen Text hat.

Auch Checks auf das Vorhandensein von Messages sind schwieriger. Ich kann nicht einfach `if(message)` schreiben, sondern muss immer auf die Length der Description prüfen (vgl. https://github.com/public-ui/kolibri/pull/7113/files#diff-7675cd850bcc473d2946ec363b9bd460f0e255e4f20e55770a89dda0b2c48bf1R51)

2024-11-26 07:57 UTC, deleonio commented on packages/components/src/schema/props/msg.ts
> +				defaultValue: {
@sdvg Da bin ich ganz bei Dir. Ich habe auf das Refactoring verzichtet, weil es m.E. nicht mit dem Fehler erstmal was zu tun hat. Für die gewünschte Behandlung müssten wir die Render-Funktion usw. refactorn. Ich würde gerne hierzu ein separates Ticket anlegen: https://github.com/public-ui/kolibri/issues/7122

2024-11-26 08:04 UTC, sdvg commented on packages/components/src/schema/props/msg.ts
> +				defaultValue: {
Das passt für mich natürlich, danke fürs Aufnehmen 👍

2024-11-26 08:17 UTC, deleonio commented on packages/components/src/components/input/component.tsx
> +				{showMsg && <KolFormFieldMsgFc _alert={this._alert} _hideError={this._hideError} _msg={this._msg} _id={this._id} />}
erledigt.

2024-11-26 09:36 UTC, deleonio commented on packages/samples/react/src/components/input-date/show-hide-msg.tsx
> +					<KolButton _label="Toggle Hide Msg" _type="button" _on={onHideMsg} />
Jetzt erledigt.

2024-11-27 08:29 UTC, sdvg approved these changes
Die Snapshot-Updates irritieren mich noch. Da es sich nur um BMF handelt, würde ich das aber mal ignorieren.

2024-11-27 08:42 UTC, merged