Apply BEM refactoring to progress, popover and nav
public-ui/kolibri pull request #7137
Opened 2024-11-28 16:22 UTC by anicyne

Refs: #7036

2024-12-16 16:13 UTC, sdvg requested changes
Hallo @anicyne, ich habe mich hier auch erst einmal nur auf die HTML-Struktur konzentriert. Das restliche CSS würde ich reviewen, wenn das angepasst ist.

2024-12-16 16:13 UTC, sdvg commented on packages/components/src/components/nav/shadow.tsx
> +			<div class={clsx('kol-nav__entry', { 'hide-label': hideLabel })}>
hide-label bitte noch als BEM modifier

2024-12-16 16:13 UTC, sdvg commented on packages/components/src/components/nav/shadow.tsx
> +					<KolLinkWcTag class="kol-nav__entry--item kol-nav__entry--link" {...entry} _hideLabel={hideLabel} _icons={icons} />
Bitte noch einmal die BEM Struktur prüfen: `__entry` ist bereits das parent element, hier kann es keine Modifier dazu geben

2024-12-16 16:13 UTC, sdvg commented on packages/components/src/components/nav/shadow.tsx
> +				class="kol-nav__entry--expand-button"
Das ist kein Modifier von `entry` sondern ein eigenständiges Element

2024-12-16 16:13 UTC, sdvg commented on packages/components/src/components/nav/shadow.tsx
> +					{ ' kol-nav__list--horizontal': props.deep === 0 && props.orientation === 'horizontal' },
Ein Objekt pro Klassenname ist eigentlich nicht notwendig, lieber wie oben in einem Objekt-Literal. Das Leerzeichen am Anfang der Zeile bitte auch entfernen.

2024-12-16 16:13 UTC, sdvg commented on packages/components/src/components/nav/style.scss
> +	:not(.kol-nav--is-compact) nav {
Bitte überall BEM-Selektoren verwenden

2024-12-16 16:13 UTC, sdvg commented on packages/components/src/components/popover/component.tsx
> +					<div class={`kol-popover__arrow ${this.state._align}`} ref={this.catchArrowElement} />
Für align bitte BEM verwenden

2024-12-16 16:13 UTC, sdvg commented on packages/components/src/components/progress/shadow.tsx
> +			<circle class="kol-progress__cycle--background" cx="60" cy="60" r="54.5" fill="currentColor" stroke="currentColor" stroke-width="8"></circle>
Bitte auch hier BEM korrekt einsetzen. Modifier sind nicht für Child Elements gedacht.

Eine mögliche Struktur für diese Komponente könnte sein:

```scss
.kol-progress {
	&__cycle {}
	&__cycle-background {}
	&__cycle-whitespace {}
	// ...
}
```

Du könntest aber auch drei Blöcke draus machen:

```scss
.kol-progress {}

.progress-cycle {
	&__background {}
	&__whitespace {}
	// ...
}

.progress-bar {}
```

2024-12-18 15:41 UTC, sdvg commented on packages/themes/itzbund/src/components/nav.scss
Hier habe ich den alten Stand verworfen, weil nichts mehr so recht zusammen gepasst hast.
Das Styling ist jetzt vereinfacht und farblich an die V1 angelehnt.

2024-12-19 17:21 UTC, deleonio approved these changes

2024-12-19 17:24 UTC, merged