Apply BEM refactoring to Span & Heading
public-ui/kolibri pull request #7154
Opened 2024-12-05 14:39 UTC by AlexanderSchmidtCE

Refs: #7036

The A11y and PO reviews will only take place after all other DoD steps have been completed by the Developer:
- [x] Meaningful pull request title for the release notes
- [x] Pull request is linked to an issue and all changes relate to the issue
- [x] Tests to protect this code implemented (if applicable)
- [x] Manual test performed successfully (if applicable)
- [x] Documentation or migration has been updated (if applicable)

2024-12-06 11:18 UTC, sdvg requested changes

2024-12-06 11:18 UTC, sdvg commented on packages/components/src/components/heading/test/__snapshots__/snapshot.spec.tsx.snap
> +    <strong class="kol-heading kol-heading--strong kol-heading__headline">
Ich kommentiere mal hier, weil man hier das Problem am besten sieht: Wir haben _Block_ und _Element_ auf einer Ebene.

2024-12-06 11:18 UTC, sdvg commented on packages/components/src/functional-components/Span/Span.tsx
> +		<span class={clsx('kol-span', { 'hide-label': hideLabel }, classNames)} {...other}>
hide-label sollte ein modifier sein

2024-12-06 15:48 UTC, sdvg requested changes

2024-12-06 15:48 UTC, sdvg commented on packages/components/src/components/accordion/test/__snapshots__/snapshot.spec.tsx.snap
> +      <div class="kol-heading">
Ich bin noch nicht so überzeugt davon, dass wir hier jetzt immer einen div-wrapper haben sollten. Vielleicht würden sich zwei verschieden BEM-Blöcke anbieten, für hgroup und h{n}?

2024-12-06 15:48 UTC, sdvg commented on packages/components/src/components/accordion/test/__snapshots__/snapshot.spec.tsx.snap
> +        <h1 class="collapsible__heading kol-accordion__heading kol-heading--h1 kol-heading__headline">
Hier passt es leider noch nicht zusammen: Die beiden Klassen `kol-heading--h1 kol-heading__headline"` beziehen sich auf zwei unterschiedliche Elemente.

2024-12-06 15:48 UTC, sdvg commented on packages/components/src/components/style.scss
> +	[class*='--hide-label'],
Warum brauchen wir das? Welche Elemente außer span sind hier noch relevant?

2024-12-09 07:55 UTC, AlexanderSchmidtCE commented on packages/components/src/components/style.scss
> +	[class*='--hide-label'],
Span ist tatsächlich das einzige Element was Relevanz hat. Hatte im Kopf, dass Buttons etc. auch die Möglichkeit haben ein hide-label zu setzen, aber das wird alles weiter zum dazugehörigen Span-Element weitergereicht.

2024-12-09 14:33 UTC, sdvg approved these changes

2024-12-09 14:34 UTC, merged