Enhance visual tests by adding snapshot tests for different viewport …
public-ui/kolibri pull request #7172
Opened 2024-12-10 04:45 UTC by deleonio

…sizes and zoom levels

2024-12-10 16:24 UTC, sdvg reviewed
@deleonio Ich hatte das PR heute morgen schon mal angeschaut: Funktioniert das Feature sicher schon wie gewünscht?

Bei den neuen Snapshots kann ich keinen Zoom erkennen.
Bei den bestehenden Snapshots fände ich es eigentlich schön, wenn die Viewport-Size gleich (=klein) bliebe. Bei den sehr großen VP mit viel Weißraum wird es schwieriger, Abweichungen zu sehen.

2024-12-10 21:30 UTC, deleonio commented
> @deleonio Ich hatte das PR heute morgen schon mal angeschaut: Funktioniert das Feature sicher schon wie gewünscht?
> 
> Bei den neuen Snapshots kann ich keinen Zoom erkennen. Bei den bestehenden Snapshots fände ich es eigentlich schön, wenn die Viewport-Size gleich (=klein) bliebe. Bei den sehr großen VP mit viel Weißraum wird es schwieriger, Abweichungen zu sehen.

Danke, ich habe es jetzt glaube besser hinbekommen 😄 .

2024-12-11 07:24 UTC, laske185 approved these changes

2024-12-11 08:12 UTC, sdvg requested changes

2024-12-11 08:12 UTC, sdvg commented on packages/themes/default/snapshots/theme-default/snapshot-for-skip-nav-basic-zoom-firefox-linux.png
Leerer Snapshot

2024-12-11 08:12 UTC, sdvg commented on packages/themes/default/snapshots/theme-default/snapshot-for-input-text-focus-zoom-firefox-linux.png
Leerer Snapshot

2024-12-11 08:30 UTC, sdvg approved these changes

2024-12-11 08:30 UTC, merged