refactor: update input components css  to use bem styles and mixins
public-ui/kolibri pull request #7180
Opened 2024-12-10 20:12 UTC by Makko74

ref #7178

2025-01-10 08:40 UTC, laske185 commented
**Inputs allgemein**:
Sobald man in den Root klickt, wird das Element fokussiert. Das macht bei Textfeldern den Effekt, dass man an beliebiger Stelle in die Nähe klickt und dann den Fokus auf das Input setzt. Extrem ist es bei Checkboxen. Nervig aber auch bei Input-File, da dort ein Dialog aufgeht, nur weil man auf den Hint oder die Message geklickt hat.
![image](https://github.com/user-attachments/assets/0f297619-1d58-48db-ab10-70161ed3fedf)

Die Labels, Messages, Hints sind nicht mehr selektierbar, sodass man den Text kopieren kann.


**Radio-Buttons**:
Bei der Navigation mit Tab wird meistens das zweite Element fokussiert. Der Fokus bleibt dann auch immer auf diesem Element hängen. Wählt man einen anderen Eintrag mit den Pfeiltasten aus, bleibt der Fokus auf dem Element. Ab dann ist man nicht mehr in der Lage, mit den Pfeiltasten ein anderes Element auszuwählen.
Klickt man mit der Maus auf das erste Element, wird dieses ausgewählt, der Fokus aber sofort auf das zweite gesetzt.

TBD;

2025-01-14 06:56 UTC, sdvg commented
@laske185 Das dürften beides Nebeneffekte von `delegatedFocus` sein, die ich so auch auf develop reproduzieren kann. Siehe auch: https://github.com/public-ui/kolibri/issues/6869#issuecomment-2426103597

2025-01-16 07:01 UTC, sdvg commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
Abstände bei Radio Buttons haben sich leicht geändert. Die Zentrierung wirkt jetzt besser.

2025-01-16 07:22 UTC, sdvg commented
Es gibt folgende Abweichungen in den Snapshots, die ich als Verbesserungen oder irrelevant sehen und demnach beibehalten würde:

- Allgemein:
    - Ornamente nehmen etwas mehr Platz ein durch Umstellung von Flex auf Grid
    - Hint-Texte werden wieder kursiv dargestellt
    - Messages sind wieder an der richteigen Position
- Radio: Abstände leicht angepasst bzw. ungewollte Abstände durch UA-Styles auf Label entfernt und Zentrierung verbessert
- Checkbox Button: Ecken wieder abgerundet, Layout-Fix bei langen Labels
- Checkbox Switch: Indeterminate-State ist jetzt blau, analog zu den normalen Checkboxen

2025-01-22 07:52 UTC, laske185 requested changes
Bis jetzt nicht fertig. Aber schau mal nach dem Layout im 400 % zoom. Danke

2025-01-22 07:52 UTC, laske185 commented on packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-static-form-zoom-firefox-linux.png
Der rechte Margin/Padding fehlt.

2025-01-22 10:42 UTC, sdvg commented on packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-static-form-zoom-firefox-linux.png
Das kam vom Input Range, das durch einen Bug immer das Number Input zu breit dargestellt hat, wenn kein `_max`-Value definiert war.
Im alten Layout war das Input aus dem Layout ausgebrochen, wenn zu wenig Platz war. Im neuen Layout wächst der ganze Container mit.
Durch den Fix tritt das Problem jetzt aber gar nicht mehr auf. Nur bei sehr großen Max-Werten braucht die Komponente entsprechend mehr Platz.

2025-01-22 10:44 UTC, sdvg commented on packages/components/src/components/input-range/shadow.tsx
> +			'--kolibri-input-range--input-number--width': `calc(${String(this.state._max ?? 1000).length}ch + 1.5em)`,
Zwei Problem gelöst:
* Wenn _max nicht definiert war, wurde die Länge vom String `'undefined'` (9) genommen, daher die breiten Inputs.
* Als Zeichenbreite wurde `em` angenommen, jetzt zu `ch` (Breit des Zeichens `0`) optimiert.

2025-01-22 12:16 UTC, laske185 requested changes

2025-01-22 12:16 UTC, laske185 commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-date-basic-zoom-firefox-linux.png
Überlappen darf sich nichts.

2025-01-22 12:16 UTC, laske185 commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-email-basic-zoom-firefox-linux.png
Hier überlappen sich die Icons mit dem Placeholder.
![grafik](https://github.com/user-attachments/assets/eba2ea12-5ce2-4fdc-95cd-bad61326b750)

2025-01-22 12:16 UTC, laske185 commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-password-show-password-zoom-firefox-linux.png
Das Auge-Icon wird überlappt.

2025-01-22 12:16 UTC, laske185 commented on packages/components/src/components/input-range/shadow.tsx
> +			'--kolibri-input-range--input-number--width': `calc(${String(this.state._max ?? 1000).length}ch + 1.5em)`,
Es sieht wenn die Komponente sehr schmal ist zwar etwas gequetscht aus, aber es sollte passen.
<img width="151" alt="image" src="https://github.com/user-attachments/assets/db90ca68-407e-47cd-b0f3-131efda1ec2b" />

2025-01-22 12:16 UTC, laske185 commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-range-basic-zoom-firefox-linux.png
Die Komponente verhält sich unterschiedlich in der Breite, je nachdem ob sie eine Warnung zeigt oder nicht.

2025-01-22 12:16 UTC, laske185 commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-disabled-interactive-scenario-zoom-firefox-linux.png
Beim Input-Date ist als einziges der Padding rechts nicht.

2025-01-22 12:16 UTC, laske185 commented on packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-button-firefox-linux.png
Der Text muss bei align left links einen Margin haben. Ticket anlegen oder gleich hier beheben?

2025-01-22 12:16 UTC, laske185 commented on packages/themes/default/snapshots/theme-default/snapshot-for-input-date-basic-zoom-firefox-linux.png
Überlappende Input-Dates.

2025-01-22 12:16 UTC, laske185 commented on packages/themes/default/snapshots/theme-default/snapshot-for-input-password-show-password-zoom-firefox-linux.png
Das hatte ich schon. Warum gibts das Testszenario mehrmals?

2025-01-22 12:16 UTC, laske185 commented on packages/themes/default/snapshots/theme-default/snapshot-for-input-range-basic-zoom-firefox-linux.png
Überlappung.

2025-01-22 12:22 UTC, laske185 requested changes

2025-01-22 12:22 UTC, laske185 commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-range-basic-firefox-linux.png
Die Breite des Input-Numbers ist je nachdem ob eine Message dran ist unterschiedlich.

2025-01-22 12:22 UTC, laske185 commented
@sdvg  wir können wo es für dich passt auch neue Tickets machen und die findings dann separat bearbeiten.

2025-01-23 08:48 UTC, sdvg commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-range-basic-firefox-linux.png
Jetzt habe ich auch ein bisschen rätseln müssen. Es hat tatsächlich nicht direkt etwas mit der Message zu tun:

Die "kleinen" Felder haben einen `_max`-Wert von `50` definiert, deshalb wird Platz für zwei Ziffern reserviert.
Die größeren Felder haben keinen `_max`-Wert definiert, für diesen Fall hatte ich einen Fallback von 4 Ziffern definiert.

2025-01-23 09:06 UTC, sdvg commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-date-basic-zoom-firefox-linux.png
Das wird sich ja erledigen mit: https://github.com/public-ui/kolibri/issues/7266

Hier ist noch zu erwähnen, das unsere Zoom-Testcases mit der CSS-Property `zoom` umgesetzt sind. Der native Browser-Zoom im Firefox verhält sich da anders und führt bei mir nicht zu Überkappungen.

2025-01-23 09:09 UTC, sdvg commented
> @sdvg wir können wo es für dich passt auch neue Tickets machen und die findings dann separat bearbeiten.

Habe die noch offenen Punkte jetzt durchgeschaut. Die würde ich tatsächlich gerne in einem neuen Ticket machen, weil sie sich teilweise mit der [Anpassung der Sample App ](https://github.com/public-ui/kolibri/issues/7266)(einspaltig) erledigen sollten. Die ganzen 400% Zoom-Themen würde ich vorschlagen in einem Ticket zusammenzufassen.

2025-01-23 12:06 UTC, laske185 commented on packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-date-basic-zoom-firefox-linux.png
Dann stellt mir sich aber schnell die Frage nach der Sinnhaftigkeit der Zoom-Tests, wenn diese sich anders als der richtige Browser-Zoom verhält.

2025-01-24 07:24 UTC, laske185 submitted a review, later dismissed
Nachdem die Snapshots aktualisiert sind kann gemergt werden. Für offene Themen sind neue Issues angelegt.

2025-01-24 07:41 UTC, laske185 approved these changes

2025-01-24 10:25 UTC, merged